### ISSUE TITLE
FX Diagram: clicking on units doesn't register the first time after clicking on something in a context menu

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4294] opened 2021-04-11 21:18 UTC
**Bug Description:**
Right after changing filter type, FX type, or choosing an option in the Surge menu, the first time I left-click on an FX unit to open its FX editor, or right-click on an FX unit to bypass it, it will not register. I have to click on it a second time on it for it to register.

**Surge Version**
Latest nightly, VST3 x64

**Config:**
 - OS: Windows 10 x64
 - Host: FL Studio 20.8.3 x64

**Additional Information:**
- This seems to only happen when opening menus with **left-click**, meaning it doesn't do it after right-clicking on parameters or right-clicking on an empty space to access the Surge Menu. It does it when left-clicking on the dedicated menu button, though.
- If I open a menu with left-click and then click away again to dismiss it, it will not do it. I guess that clicking to dismiss actually counts as the first click that would not have been detected, and then it works fine.

**Comment by mkruselj** [comment] 2021-04-11 21:27
Dupe of #4098

**Closed by mkruselj** 2021-04-11 21:27 UTC
Labels: Bug Report, UI
