### ISSUE TITLE
4 whole note delay gets it wrong

### ISSUE THREAD

**Issue by Janco-Verduin** [surge-synthesizer/surge#6415] opened 2022-07-24 15:24 UTC
**Bug Description:**
The delay in surge FX, when set on 4 whole notes messes up. It is shorter. When set on 2 bars it works fine. I have feedback set on 100%

**Surge XT Version**
1.0.1.60228e8

* Version:
* Plugin Type: AU
* Bitness: 64-bit

**Reproduction Steps:**
1. set delay on 4 whole notes (synced with your daw) and play something back
2. feedback set on 100%. 
3. It starts after 3 bars.

**Expected Behavior:**
To neatly repeat 4 bars every 4 bars

**Screenshots:**
not applicable

**Computer Information (please complete the following!):**
 - OS: MacOS 11.6.6
 - Host: Logic
 - Version: 10.7.4

**Additional Information:**

**Comment by baconpaul** [comment] 2022-07-24 15:27
Yes this is a duplicate of #2504 

the problem we face is an allocation probkem with very long delays and modulation. We obviously don’t want to pre allocate but allocate at modulation time is also hard so we have had this long standing bug with extreme temposync delay ranges 

thank you for the report but let me close this as a dup. Please feel free to subscribe to the other issue!

**Closed by baconpaul** 2022-07-24 15:27 UTC
Labels: Bug Report
