### ISSUE TITLE
Cannot compile on raspberry pi

### ISSUE THREAD

**Issue by phil123456** [surge-synthesizer/surge#4206] opened 2021-03-28 14:41 UTC
Hi,

I cannot compile on raspberry pi following the documentation

first I tried :

```
pi@raspberrypi:~/surge $ ./build-linux.sh build
ARM build activated. Using ARM_NATIVE=native settings; building in buildlin-armv7l
make: *** No rule to make target 'Surge-VST3-Packaged'.  Stop.
```

trying to build lv2

```
** Build of Surge-VST3-Packaged failed**
pi@raspberrypi:~/surge $ ./build-linux.sh build --project=lv2
ARM build activated. Using ARM_NATIVE=native settings; building in buildlin-armv7l
make: *** No rule to make target 'Surge-LV2-Packaged'.  Stop.

```

then I tried :

```
make -j 2 Surge-VST3-Packaged
...
In file included from /home/pi/surge/src/common/dsp/DspUtilities.h:20,
                 from /home/pi/surge/src/common/dsp/effect/Effect.h:18,
                 from /home/pi/surge/src/common/dsp/effect/BBDEnsembleEffect.h:17,
                 from /home/pi/surge/src/common/dsp/effect/BBDEnsembleEffect.cpp:16:
/home/pi/surge/src/common/globals.h:38:10: fatal error: simde/x86/sse2.h: No such file or directory
 #include "simde/x86/sse2.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

I tried to install **simde** package but it's not available

```
pi@raspberrypi:~/surge/build $ sudo  apt-get install libsimde-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libsimde-dev
pi@raspberrypi:~/surge/build $ sudo  apt-cache search simde
```

thanks for helping be resolving this

**Comment by baconpaul** [comment] 2021-03-28 14:44
Did you update Su modules before you built?

**Comment by mkruselj** [comment] 2021-03-28 14:46
Yeah first stronafter cloning the repo should be `git submodule update - - init - - recursive`

**Comment by baconpaul** [comment] 2021-03-28 14:46
Anyway from the readme on the pi once you have checked out and updated sh modules the commands are

cmake -Bbuild -DARM_NATIVE=native
cmake --build build --config Release --target Surge-VST3-Packaged

**Comment by mkruselj** [comment] 2021-04-02 07:37
@phil123456 Did you get it going?

**Comment by baconpaul** [comment] 2021-04-02 15:07
So I just confirmed that PI builds (I usually do at this point in the cycle even though we cross-compile on every install)

```
  719  mkdir tmp
  720  cd tmp/
  721  git clone https://github.com/surge-synthesizer/surge.git
  722  cd surge
  723  git submodule update --init --recursive
  724  cmake -Bbuild -DARM_NATIVE=native
  725  cmake --build build --config Release --target Surge-VST3-Packaged
  726  history
```

Those commands gave me a clean vst3 

```
pi@raspberrypi:~/tmp/surge $ uname -a
Linux raspberrypi 5.4.42-v8+ #1319 SMP PREEMPT Wed May 20 14:18:56 BST 2020 aarch64 GNU/Linux
```

So I'm going to close this issue since it really looks like that submodule step wasn't run.

@phil123456 if you have more info or a cleaner log or the above don't work please reopen it.

**Closed by baconpaul** 2021-04-02 15:07 UTC
Labels: User support request
