### ISSUE TITLE
SurgeFX Init can ask for incorrect Note

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4097] opened 2021-03-16 13:58 UTC
Linux/64bit/Reaper
NIGHTLY-2021-03-16-6da806f

Here is what i did:

- open Reaper in terminal
- new project
- load surge on new track
- remove surge from track
- insert SurgeEffectsBank (same track)
- crash (Segmentation fault (core dumped))

syslog says this:
[coredump.txt](https://github.com/surge-synthesizer/surge/files/6149527/coredump.txt)

**Comment by mynameismuhl** [comment] 2021-03-16 14:24
I forgot to mention:
This only happens if you load and remove Surge first.
Just inserting fx bank without that step works fine.

**Comment by baconpaul** [comment] 2021-03-16 15:55
Hmm thank you. That note tuning table is a static member of SurgeStorage so I wonder if the create / destroy / recreate i leaving it somehow out in the cold. Excellent report. Will look.

**Comment by baconpaul** [comment] 2021-03-19 14:35
Hi @mynameismuhl 

I just tried this at head 7e5975e1312 and had no problem running both plugin in either reaper or juce audio plugin host on linux.

I did fix a pretty big leak the other day on linux but that doesn't seem like the same thing.

Can you just confirm that you still see this at head and if so, I'll figure out a way to perhaps understand what you see that I don't?

**Comment by baconpaul** [comment] 2021-03-19 14:35
Oh and @tank-trax if you are online sometime and have a minute, can you see if you can run both latest surge and surge-fx in a single session without a crash too? Thanks!

**Comment by mynameismuhl** [comment] 2021-03-19 17:43
yes i still see this with nightly 0c44a80
but only following the exact steps in first post
lots of other combinations like running both together or loading fxplugin first 
don't crash here now.

**Comment by baconpaul** [comment] 2021-03-19 18:29
oh yeah. that does it here!

**Comment by baconpaul** [comment] 2021-03-19 18:32
oh and now i see it. stay tuned.

**Comment by baconpaul** [comment] 2021-03-19 18:36
cool what a truly excellent bug report. thank you.

**Comment by baconpaul** [comment] 2021-03-19 18:43
So here's what is happening

SampleRate is a global. I mean I don't have to say much more than that.
But destroying the surge leaves that global in a weird state
Reloading an SFX reads it
At play time this is fine - we do the right thing
but there's an init path which uses sample rate now
and that sees a 0 or a wierd number
and makes an array index

So the solution is to check the samplerate and if it is 0 set it to 44100 at construction time so we at least have a non-crashing value.

**Comment by baconpaul** [comment] 2021-03-19 19:27
f31146d contains a fix to this problem. Thanks again!

**Comment by tank-trax** [comment] 2021-03-19 21:30
my apologies had not had a change to test.... looks to be resolved though, 

I generally use 48kHz sample rate for recording/audio

**Comment by baconpaul** [comment] 2021-03-19 21:35
Yeah as soon as surge has to do any work it will set to the right thing. Just the constructor path can do a sample rate read before work is required so for now I did a precautionary set

**Comment by mynameismuhl** [comment] 2021-03-23 06:05
This came back.
Seen with nightly 3c241f2
Situation as before.
coredump also same as far as i can tell

**Comment by baconpaul** [comment] 2021-03-23 12:08
OKr reopening.

**Comment by mkruselj** [comment] 2021-03-30 20:53
[Surge_crash.txt](https://github.com/surge-synthesizer/surge/files/6232106/Surge_crash.txt)

**Comment by baconpaul** [comment] 2021-03-31 00:12
@mynameismuhl so I am still not sure why the delay is asking for a bad note and I want to find that but #4217 will be far more defensive in the event it does. If once that's merged you could re-test I'd appreciate it. 

We should leave this issue open thought. The FX init path shouldn't make that mistake. But the limit is a smart choice anyway

**Comment by baconpaul** [comment] 2021-03-31 01:39
Awesome so I have successfully swept the problem under the rug :)

imwill leave this open to keep chipping away at the root cause of course.

thank you for testing and confirming

**Closed** 2021-05-06 15:58 UTC
Labels: Bug Report, FX Plugin, Linux
