### ISSUE TITLE
Some AW effect sliders cause a lot of zipper noise

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3315] opened 2020-12-01 10:29 UTC
I know, we don't want to touch the AW DSP, but maybe this is something that can be looked into nonetheless.
Here is a (hopefully complete) list of sliders that are effected:

- Ambience:
	- Bright Ambience:
		- Start
		- Length
		- Dry/Wet
	- Melt
		- Dry/Wet
	- Pocket Verbs
		- Dry/Wet
	- Star Child
		- Sustain (This one might just be the buffer acting up, though)
		- Dry/Wet
- Clipping
	- AD Clip
		- Boost
	- One Corner Clip
		- Input
		- Pos Thr
		- Neg Thr
		- Dry/Wet
- Dynamics
	- Block Party
		- Pound
		- Dry/Wet
	- Butter Comp
		- Compress
		- Output
		- Dry/Wet
	- Compresaturator
		- Drive
		- Clamp
		- Expand
		- Output
		- Dry/Wet
	- Drum Slam
		- Drive
		- Output
		- Dry/Wet
	- Logical
		- Threshold
		- Ratio
		- MakeupGn
		- Dry/Wet
	- Mojo
		- Input
	- Point
		- Input Trim
	- Pop
		- Intenst
		- Dry/Wet
	- Pressure
		- Pressure
		- Mewiness
		- Output Gain
	- Pye Wacket
		- Input Gain
		- Output Gain
	- Surge
		- Surge
		- Dry/Wet
	- Vari-Mu
		- Intensty
		- Output
		- Dry/Wet
- Filter
	- Hombre
		- Intensity
	- Air
		- Output Level
		- Dry/Wet
	- Capacitor
		- Dry/Wet
- Lo-Fi
	- Deck Wrecka
		- Wreck
- Saturation
	- Buss Colors
		- Input Trim
		- Output Trim
		- Dry/Wet
	- Apicolypse
		- Drive
		- Output
	- Bass Drive (In this one, the zipper noise seems to go through the effect, which is super weird)
		- Presnce
		- High
		- Mid
		- Low
		- Drive
	- Cojones
		- Body
		- Output
		- Dry/Wet
	- Density
		- Density
		- Out Level
		- Dry/Wet
	- Drive
		- Drive
		- Out Level
		- Dry/Wet
	- Focus
		- Boost
		- Focus
		- Output
		- Dry/Wet
	- Fracture
		- Drive
	- Hard Vacuum
		- Drive
		- Output
		- Dry/Wet
	- Loud
		- Boost
		- Output Level
		- Dry/Wet
	- NC-17
		- LOUDER
		- Output
	- Spiral
		- Input
		- Output
		- Dry/Wet
	- Unbox
		- Input
		- Output
	- Single-Ended Triode
		- Dry/Wet
- Tape
	- Iron Oxide
		- Input Trim
		- Tape High
		- Tape Low
		- Output Trim
		- Inv/Dry/Wet
	- To Tape
		- Input
		- Head B
		- Flutter
		- Output
		- Dry/Wet

Surge Synthesizer
Version: 1.8.nightly.809a376
Build Info: Built on 2020-12-01 at 00:59:41, using pipeline host 'fv-az83-597'
System: Intel CPU, Windows VST3, 64-bit
Plugin Host: Ableton Live 10.1

**Comment by baconpaul** [comment] 2020-12-01 11:28
Sorry what is zipper noise?

**Comment by baconpaul** [comment] 2020-12-01 11:37
Note to self Basically lipol/ lag the fs in the way adapter

**Comment by baconpaul** [comment] 2020-12-01 15:45
Oooh somewhat of a bummer but cleverly I already put in laggers/smoothers when I implemented Airwindows.
just I only do it per block
lemme ponder and test. This one may be trickier than I thought.

**Comment by baconpaul** [comment] 2020-12-01 22:06
So some things to try

I set a rate (0.04*BLOCK_SIZE) in AirWinEffect.cpp. If you change it to (say) 0.1*BLOCK_SIZE does this get better or worse?

If however the problem is that over the block we keep values constant in airwindows another solution is to run the AWFX not in a BLOCK_SIZE but run them in (say) 4 BLOCK_SIZE/4 chunks updating params in between. This wouldn't be that much more expensive and would set constant-param zipper size to a quarter block. (We could also do the clever thing of if the params are all unchanged then run BLOCK_SIZE so CPU goes down on fixed values).

I'll do my best to find a good example where I can hear it from this list tomorrow. One of those two solutions is the ones we have hope for. If we have to dig into the individual AW we are in trouble.

Presume it zippers with modulation also? If you made a patch which showed an extreme zippering that would be interesting too.

**Comment by TheNerdyMusicGuy** [comment] 2020-12-01 22:12
Here is a simple patch that demonstrates the noise nicely, I think

[Zipper Example.zip](https://github.com/surge-synthesizer/surge/files/5625741/Zipper.Example.zip)

**Comment by baconpaul** [comment] 2020-12-03 18:46
Super duper useful. 

Anyway I have basically made it so rather than keeping params constant over the entire surge block and then running the entire block, I divide the surge block into 8 chunks and adjust parameters inside that. This makes your patch above lose all the high frequency noise and still leaves the AW block size at 4, which allows for some re-use of setup code per block. 

A bit of CPU but much more appropriate for surges modulation architecture.

Will close this when merged. If you find egregious cases, please re-open. In theory (although it would add complexity and a bit more CPU) I could choose different block sizes per AW type.

**Closed** 2020-12-03 19:45 UTC
Labels: Bug Report, Effects
