### ISSUE TITLE
Suggestion to add MIDI mapping/learn onto the step shuffle buttons.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2668] opened 2020-09-22 16:29 UTC
Since implementing host automation onto the step shuffle buttons is harder then implementing MIDI mapping/learn onto them, here comes that suggestion.

![midi mapping on these](https://user-images.githubusercontent.com/56724286/93909961-b400cc80-fd00-11ea-89c8-2b5572991fa1.gif)

Basically receive midi note = move one step

**Comment by mkruselj** [comment] 2020-09-22 16:51
Basically a duplicate of #1798 but MIDI learn focused. Closing this issue because the older one existed for a longer time, and just added note that instead of host automation MIDI learn could be implemented first, for the time being.

**Closed by mkruselj** 2020-09-22 16:51 UTC
Labels: Feature request
