### ISSUE TITLE
AppImage version for linux

### ISSUE THREAD

**Issue by djnotes** [surge-synthesizer/surge#5189] opened 2021-10-01 17:31 UTC
**Is your feature request related to a problem? Please describe.**
Official binaries don't support all linux distro and setting up build environment for unsupported distros is hard.

**Describe the solution you'd like:**
An AppImage version of the application will be very awesome. Could you please provide it?

**Describe alternatives you've considered:**
Setting up build env on my Fedora 34 is very challenging if not impossible. 

**Additional context:**
Dont know what equivalent package names for Fedora are.

**Comment by baconpaul** [comment] 2021-10-01 17:37
Hi

we don’t have resources to do this in the surge team. Ubuntu 20 binary packages as rpm or deb  or self build is what we provide. I also don’t know if appimage works for plugins.

but I think @KottV has set up surge in obs and that may help? 

Why is it hard to set up self build in fedora also? Our requirements are pretty minimal and nothing special.

**Comment by baconpaul** [comment] 2021-10-01 17:41
Oh tagging this won’t be done because we can’t do it in surge land with our ci platform. But keeping it open for conversation if there are other distro mechanisms which might be able to.

**Comment by djnotes** [comment] 2021-10-01 18:26
Hi Paul, 
 As far as I know, Ubuntu packages are deb format. Do you mean that you also provide rpm packages for rpm based OSes like Fedora?
From my experience in building lmms, I usually changed *dev package names to devel and it worked. But, that doesn't seem to work for surge. I'll try building on Fedora and maybe do a pull request for Fedora instructions. 

 
  On Fri, Oct 1, 2021 at 21:07, ***@***.***> wrote:   


Hi

we don’t have resources to do this in the surge team. Ubuntu 20 binary packages as rpm or deb or self build is what we provide. I also don’t know if appimage works for plugins.

but I think @KottV has set up surge in obs and that may help?

Why is it hard to set up self build in fedora also? Our requirements are pretty minimal and nothing special.

**Comment by baconpaul** [comment] 2021-10-01 18:46
Our new release packages as an rpm and a deb both. But they are all built with the ubuntu toolchain (we use ubuntu 18 for this build I think)

https://github.com/surge-synthesizer/releases-xt/releases/tag/Nightly

**Comment by baconpaul** [comment] 2021-10-01 18:51
And are still not prod stable

**Comment by KottV** [comment] 2021-10-01 22:36
I can make the same https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth  plus AppImagefor Surge XT

but this will be OBS
good news it has hooks for GH integration https://openbuildservice.org/2021/09/28/support-for-push-events/

**Comment by KottV** [comment] 2021-10-01 23:31
Sure, AppImage is for standalone executable only.

**Comment by baconpaul** [comment] 2021-10-02 14:26
So is there anything to be done here? It seems there isn’t other than perhaps a fedora user does a built at head and sends us doc tweaks right?

**Comment by KottV** [comment] 2021-10-02 23:25
If i understand right the issue is that Surge_XT plugin (or standalone?) doesn't work one some distros. I suppose it's mainly a problem of old Glibc, Ubuntu 18/Mint 19  for example. 

>So is there anything to be done here?

I think lowering build env to Ubuntu 18 is not way to go:)

It's not clear for me what the problem with Fedors, i'd rather cast @ycollet who maintains https://copr.fedorainfracloud.org/coprs/ycollet/audinux/

From my side - i can provide Ubuntu 18 - 21, Fedora 33-Rawhide packages (plugin) and AppImage in OBS. Is that a solution? I mean will be not an "official build"

**Comment by djnotes** [comment] 2021-10-03 23:16
@KottV The problem was Fedora packages were not provided in the download section. As I understand, AppImage is not an option here as Surge is a plugin? And what do you mean by OBS? Is that the free streaming app?

**Comment by KottV** [comment] 2021-10-03 23:34
Yes, AppImage is not an option for plugins.
OBS - open/opensuse build server
I provided an example of BespokeSynth repo https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth

I can make such repo with Surge_XT plugin's packages for Fedora.
But I strongly think that Fedora copr is more native.

**Comment by baconpaul** [comment] 2021-10-04 00:25
OK but it really seems that 'other than provide deb, zip, rpm, source tarball, and clear build instructions' (which for XT we do), there's nothing here for us to do on the surge team, so I'm going to close this issue if you don't mind?

**Closed by baconpaul** 2021-10-04 00:25 UTC
Labels: Linux, Won't Be Done

**Comment by djnotes** [comment] 2021-10-04 19:18
That would be awesome. Thanks Paul
 
 
  On Mon, Oct 4, 2021 at 3:56, ***@***.***> wrote:   


OK but it really seems that 'other than provide deb, zip, rpm, source tarball, and clear build instructions' (which for XT we do), there's nothing here for us to do on the surge team, so I'm going to close this issue if you don't mind?
