### ISSUE TITLE
Surge VST3 Crash in Ardour 6.5 after fiddling with some controls (GDB backtrace!)

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge#3741] opened 2021-01-28 16:42 UTC
**Bug Description:**
Surge crashed my Ardour instance.

**Surge Version**
VST3 on Linux, official 1.8 release.

* Version: 1.8
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**

(I have no idea)

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: Manajro Linux
 - Host: Ardour
 - Version: 6.5
 
**Additional Information:**
Here's a full gdb backtrace after Ardour crashed:
[gdb.log](https://github.com/surge-synthesizer/surge/files/5888712/gdb.log)

**Comment by tank-trax** [comment] 2021-02-10 20:57
just a few questions:

have you tried the 1.8.1 update? have you been able to replicate/reproduce this crash or did it happen only this one time?

**Comment by unfa** [comment] 2021-02-10 21:16
I've been using Surge a lot in past week and haven't had this issue repeated itself.

**Comment by tank-trax** [comment] 2021-02-10 22:16
I would think this would be problematic if it happened again, often or if others reported it

since it can't be reproduced, and there is no series of events that can be determined to cause the crash the only thing at the moment that I can suggest is to upgrade to version 1.8.1 (which fixed a few bugs) and see if that resolves it or if something similar recurs add it to this ticket

**Comment by mkruselj** [comment] 2021-02-27 10:47
Yes, let us know if this ends up somehow being reproducible, for now we will close the issue but if you get a consistent repro, reopen it please!

**Closed by mkruselj** 2021-02-27 10:47 UTC
Labels: Ardour, Bug Report, VST3
