### ISSUE TITLE
Have an issue from tune export

### ISSUE THREAD

**Issue by Ahmaddanesh6** [surge-synthesizer/surge#6319] opened 2022-06-27 15:24 UTC
**unable to save scl:**
I get the message unable to save when I want to get scl output from tunning editor.

* Version: XT 1.1
* Plugin Type: [VST3]
* Bitness: [ 64-bit]

**Reproduction Steps:**
1. Go to 'surge xt vst in fl studio'
2. Right Click on 'tune  and then tuning editor'
3. Scroll down to 'save scl'

**Expected Behavior:**

**Screenshots:**
![20220627_213440_copy_800x600](https://user-images.githubusercontent.com/108287167/176031438-b47d1ab3-c74c-4c02-a706-1edcc348c168.jpg)
![20220627_213346_copy_800x600](https://user-images.githubusercontent.com/108287167/176031449-c2711f4f-461b-4c25-b659-da4ee3cb2ce4.jpg)
![20220627_213252_copy_800x600](https://user-images.githubusercontent.com/108287167/176031450-fc179e87-6ad8-4b22-ac3c-5a5bd26d48e9.jpg)

**Comment by Ahmaddanesh6** [comment] 2022-06-27 15:36
Excuse me 
On tune editor

**Comment by baconpaul** [comment] 2022-06-27 16:53
Surges tuning editor export?

can you share a screenshot of the wrror?

thanks!

**Comment by Ahmaddanesh6** [comment] 2022-06-27 17:20
@baconpaul 
![Uploading 20220627_213252.jpg…]()

**Comment by mkruselj** [comment] 2022-06-27 18:58
That didn't upload properly, unfortunately.

**Comment by Ahmaddanesh6** [comment] 2022-06-27 20:39
> That didn't upload properly, unfortunately.

Hi I attached them.Thanks.

**Comment by baconpaul** [comment] 2022-06-30 07:16
Wow OK so did you even get a dialog asking you to select a file to save as?

**Comment by Ahmaddanesh6** [comment] 2022-06-30 08:22
Hi paul,
No it is not, because when I change the default tune I expect to be able to
save it as a scl file as a new tune. So it does not ask me to select a file
first.

**Comment by baconpaul** [comment] 2022-06-30 09:42
Ok I’ll have to look when I’m back at my computer in a week or so  

for now if you export html then the raw scl will be there and you can copy paste it

**Comment by Ahmaddanesh6** [comment] 2022-07-01 16:54
Ok, thanks.

**Comment by baconpaul** [comment] 2022-07-10 13:25
OK I just tried this on my mac and had no problem saving an SCL. Got an OS popup to locate the file.

Wonder if this is an FL / Windows issue? @mkruselj @VincyZed when you are next booted up can you try and export a scale from winFL?

**Comment by mkruselj** [comment] 2022-07-10 13:30
I tried it some time back and it seemed to work just fine...

**Comment by mkruselj** [comment] 2022-07-13 21:29
OK so - the dialog to save the tuning opens over here, but initially it opened on second monitor (the opposite one from which Surge GUI was being shown on). Not sure if this might be OP's case - dialog being shown out of display bounds?

**Comment by VincyZed** [comment] 2022-07-13 21:33
For me, the dialog opens fine and on my main screen, which is also the screen FL/Surge is on.

**Comment by mkruselj** [comment] 2022-07-13 21:37
Thanks for the report, Vincy. I'm not sure what to do about OP's case then. We can't fix what we can't reproduce.

**Comment by mkruselj** [comment] 2022-07-23 12:09
Closing the issue as we cannot reproduce it in house. Feel free to reopen with clear and consistently repeatable reproduction steps.

**Closed by mkruselj** 2022-07-23 12:09 UTC
Labels: Tuning, UX, Bug Report, Cannot Reproduce
