### ISSUE TITLE
Make waveshape on Sine Osc an mod destination

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1055] opened 2019-08-19 12:51 UTC
I would really like for the ability to assign an LFO to the waveshape parameter/use waveshape as a mod destination on the Sine Osc. 

I know that some of the jumps between waveshapes may be a bit jarring. Even with that constraint plenty of happy accidents for sound design can be had with the ability to move back and forth between the smooth pure sine and the more harmonically rich sine waves. 

Having stepped values is fine for my purposes.

**Comment by baconpaul** [comment] 2019-08-19 12:54
There's two approaches to this

1. Allow surge LFOs to modulate int parameters. Super useful. Tricky
2. Make the wave shape continuous and blend. Sort of not the spirit. Version tricky.

I think 1 is the way to go.... but will ponder.

**Comment by baconpaul** [comment] 2019-08-19 13:00
Linking with #235

**Comment by mkruselj** [comment] 2019-09-10 19:53
I actually think approach 2 would be super mega awesome. We would still be able to hone in on the actual quadrant-based waveforms by using the integer values (just like we do in the wavetable oscillator now, with the helpful parameter display), so I don't consider this version tricky an awful lot. Maybe I'm wrong?

But I sure think that it would be a lot more fun with a smoothly morphed wavetable!

**Comment by baconpaul** [comment] 2019-09-10 20:04
Oh it’s only version tricky because the streamed patches would change their type. (I could easily make the control snappable). I actually added a streaming-type-change mechanism in this release so we can probably do it in the next release, when there will be lots of other streaming changes too.

Also if we do your idea of having LFO mod maps then making an integer step modulation from a continuous mod could also be pretty easy.

Gotta finish #1117 ...

**Comment by mkruselj** [comment] 2019-09-10 20:17
Mod maps would be for any modulator, not just LFO ;)

But yes, thanks for considering the smooth morphing between quadrant waves in the next release! :)

**Comment by mkruselj** [comment] 2020-10-08 22:49
Gonna close this one as essentially a duplicate of #235.

**Closed by mkruselj** 2020-10-08 22:49 UTC
Labels: DSP, Feature Request, Modulation
