### ISSUE TITLE
VU Meters in Ardour in 1.9 are surprisingly expensive

### ISSUE THREAD

**Issue by nicklaf** [surge-synthesizer/surge#4347] opened 2021-04-21 13:20 UTC
**Bug Description:**
Surge UI extremely slow on certain patches.

**Surge Version**
* Plugin Host:	Ardour
* Version: 1.9.main.91069f8d
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Add a Surge MIDI track.
2. Open the Surge UI.
3. Select the third-party patch under 'Roger Linn (MPE)' called 'LS Lead Guitar 1'.
4. Leave the Surge UI open.
5. Draw enough notes in the editor so that 10 or so are playing simultaneously.
6. Play the MIDI track.
7. The Surge UI and Ardour gradually become extremely sluggish, and eventually slow Ardour to a crawl, with none of the UI panels rendered anymore.

**Expected Behavior:**
Surge doesn't slow down at all when using most other patches I tried. 'LS Lead Guitar 2' has similar problems, but all the built-in patches are fast as expected.

**Computer Information:**
 - OS: Void Linux
 - Host: Ardour
 - Version: 6.6

**Additional Information:**
Opening htop shows Xorg has very high CPU utilization as performance degrades.

The 'LS Lead Guitar 1' patch appears to be somewhat demanding. Playing without the Surge UI open in Ardour degrades performance slightly, but the problem seems to be greatly exacerbated by the Surge UI.

**Comment by baconpaul** [comment] 2021-04-21 13:26
Oooh I have a theory which would be nice if you can test.
That patch paints the vu meters by default (since the selected FX is FX1 which is the limiter)
If you click on, say, FX box B1, is it still as bad?

I'm thinking all those repaints of the VU meter could be interacting improperly with the ardour paint pipeline somehow.

**Comment by nicklaf** [comment] 2021-04-21 13:58
> Oooh I have a theory which would be nice if you can test.
> That patch paints the vu meters by default (since the selected FX is FX1 which is the limiter)
> If you click on, say, FX box B1, is it still as bad?
> 
> I'm thinking all those repaints of the VU meter could be interacting improperly with the ardour paint pipeline somehow.

In case I understand correctly, pressing Scene A and selecting oscillator 1 doesn't seem to matter much.

Actually, what seems to make the problem much worse is resizing the Surge UI window. I'll also mention that these problems seem to occur to an extent even without a complicated patch like the one I mentioned being played--they just seem to provoke the problem.

**Comment by mkruselj** [comment] 2021-04-21 14:09
Paul was talking about focusing a different FX in the FX grid, not focusing a different scene.

**Comment by baconpaul** [comment] 2021-04-21 14:35
<img width="313" alt="Screen Shot 2021-04-21 at 10 35 00 AM" src="https://user-images.githubusercontent.com/13387561/115571752-4c5a3200-a28d-11eb-8fdc-465db5fee64d.png">

Yeah click here then try it

one solution would be to slow down the idle on ardour if this is the problem.

**Comment by mkruselj** [comment] 2021-04-21 14:46
Might Ardour be polling for the UI much more often than it should have?

**Comment by nicklaf** [comment] 2021-04-21 14:50
> <img alt="Screen Shot 2021-04-21 at 10 35 00 AM" width="313" src="https://user-images.githubusercontent.com/13387561/115571752-4c5a3200-a28d-11eb-8fdc-465db5fee64d.png">
> 
> Yeah click here then try it
> 
> one solution would be to slow down the idle on ardour if this is the problem.

This solves the issue for me! Thank you for clarifying as well.

In monitoring the performance, I noticed that Ardour and Xorg both seem to have fairly constant CPU utilization, probably from drawing the UI. It was also Ardour, not Surge, which became unresponsive first. I noticed as well that making the Surge UI larger would increase the amount of CPU utilization.

Furthermore, resizing seems to be particularly expensive, so much so that resizing Surge would put the CPU utilization to 100% and grind Ardour to a halt. The workaround that baconpaul mentioned seems to prevent this.

**Comment by baconpaul** [comment] 2021-04-21 14:53
Yeah I'm not sure how often ardour is redrawing or if the redraw is particularly efficient here. But glad that solves the problem. Basically "1.9 ardour vu meter redraw is cpu intensive" is the correct name for this issue.

I think we leave this open and test it in XT to see if it is the same; there's no real fix I can think of for our current branch that's particularly easy. We could slow down the idle I guess or draw vu meters every third idle or something if it becomes a more widespread problem.

**Comment by baconpaul** [comment] 2021-04-21 15:06
Hmm OK - well the ardour devs are pretty responsive. Does sound like something is not quite right. I know they use GTK2 which is older library; wonder if that's not working with your GPU? @selenologist do you see anything like this when you run ardour?

**Comment by selenologist** [comment] 2021-04-22 02:03
Yes, I can confirm all of this behaviour. Xorg and Ardour's GUI thread consume a considerable amount of CPU, more CPU when a Conditioner displays a VU meter, and more CPU depending on zoom level.

Unfortunately I have to agree this is something to address with the JUCE port, which will probably bring its own set of challenges.

**Comment by mkruselj** [comment] 2021-04-22 14:05
But is there the same issue in another host, or is Ardour the only one exhibiting this sort of CPU munch that is GUI related? That would then point to Ardour requiring optimizations, no?

**Comment by selenologist** [comment] 2021-04-22 23:00
So some good news - for me at least, an early build of XT has dramatically lower CPU consumption - Xorg is notably a lot quieter.

**Comment by baconpaul** [comment] 2021-04-22 23:06
Oh that’s fantastic to hear.

**Comment by mkruselj** [comment] 2021-04-26 12:04
Shall we close this issue as JUCE apparently fixed this for us?

**Comment by baconpaul** [comment] 2021-04-26 12:26
Yes - I’m not going to do any optimization in the vstgui branch

**Closed by baconpaul** 2021-04-26 12:26 UTC
Labels: Bug Report, JUCE ex machina, Linux
