### ISSUE TITLE
VST2 using vst-rs

### ISSUE THREAD

**Issue by jarkk0sakkinen** [surge-synthesizer/surge#3545] opened 2020-12-29 04:35 UTC
Rust is quite easy language to bridge to C and C++. Perhaps, it would be possible to have "VST2RS" target with the glue done using rust-rs?

Some reasons why people tend to still love VST2:

- By any practical means, all software providing a VST host loads them.
- Not all plug-in vendors even support VST3. One more famous would be Xfer.
- Windows VST2 is leaps and bounds easier to bridge to Linux than VST3.
- Some VST3 plug-ins have stability issues making them a bit shaky to use.

I'm interested first and foremost is this out of reach of the Evil Steinberg's claw?

**Comment by mkruselj** [comment] 2020-12-29 08:42
> Windows VST2 is leaps and bounds easier to bridge to Linux than VST3.

But VST2 has licensing issues whereas VST3 has not because it has an open source component to it, which VST2 has not.

> Some VST3 plug-ins have stability issues making them a bit shaky to use.

I would consider this a matter of implementation from the plugin developer, rather than an inherent VST3 thing that is always there.

**Comment by baconpaul** [comment] 2020-12-29 12:31
The problem is not technical. The answer is outlined https://surge-synthesizer.github.io/formats

1. If you are a valid owner of the VST2SDK you can build a VST2 for yourself. Obviously if you distribute it you violate the GPL3 license of the surge authors.
2. There are a variety of compatibility libraries on the internet including vst-rs. Almost none of them make anything even close to a compelling claim that they avoid the very clear non-reverse-engineering clause in the VST2 license. vst-rs doesn't even mention this but other people have done a far better job at making their work clear. However the ambiguity means we won't do a binary distribution with these.

So closing this as a 'wont do/can't do'

**Closed by baconpaul** 2020-12-29 12:31 UTC

**Comment by baconpaul** [comment] 2020-12-29 12:36
oh also vst-rs doesn't support editors yet.

**Comment by jarkk0sakkinen** [comment] 2021-01-01 14:55
Right, I get **2**. Thanks for explanation.

**Comment by jarkk0sakkinen** [comment] 2021-01-02 17:07
Surge is the only single one VST3i I use. It works well, no serious issues, and zero crashes so far.  I guess that since the plugin interface is project baked, bugs can be fixed just with Surge in mind :-) Not to mention fast response time from detection to a fix.

**Comment by baconpaul** [comment] 2021-01-02 17:12
Yeah it’s been a lot of work to be honest but I think we mostly have it working now. 

That said if you have the vst2sdk you can still build for yourself no problem!! The client code is all there in the repo and it’s just an env but we can’t distribute the binary of such a build for the obvious reasons

**Comment by jarkk0sakkinen** [comment] 2021-01-13 16:38
I think I just slowly start to use VST3 now that practically everything supports it  (even Renoise since 3rd of Jan with 3.3 release).

**Comment by baconpaul** [comment] 2021-01-13 17:43
Yup - vst3 is finally real on Linux. That was 18 months of many people working and pushing (including us!) but it is finally true
