### ISSUE TITLE
Different patches play different scale degrees with retuning

### ISSUE THREAD

**Issue by narenratan** [surge-synthesizer/surge#6804] opened 2023-01-14 14:04 UTC
**Bug Description:**
Playing midi note zero with the `Keys/DX EP.fxp` and `Basses/Bass 1.fxp` patches gives different pitches when using retuning (tuning files used below).

**Surge XT Version**
I used surgepy built from commit [21bfcdb](https://github.com/surge-synthesizer/surge/commit/21bfcdbb0b907bee7db5dcce61c3a7b7ad0c9094) in the surge repo.

I also tested with Surge XT in Reaper:

* Version: Surge XT 1.1.makepkg.d3568a9ae
* Plugin Type: LV2
* Bitness: 64-bit

**Reproduction Steps:**
I've created a temporary repo with a surgepy script, the tuning files, and the output I get [here](https://github.com/narenratan/tuning_example).

To reproduce, running
```
$ git clone https://github.com/narenratan/tuning_example.git
$ cd tuning_example
$ python3 tuning_example.py
``` 
loads the tuning files and plays midi note zero using the DX EP patch, producing `dx_ep.wav`. Changing `patch_name` in the script [here](https://github.com/narenratan/tuning_example/blob/main/tuning_example.py#L19) plays midi note 0 with the Bass 1 patch, producing `bass_1.wav`. Listening to the two wav files, `bass_1.wav` has a pitch a major third below `dx_ep.wav`. This corresponds to the `5/4` in the scl file [here](https://github.com/narenratan/tuning_example/blob/main/example.scl#L9); changing the 5/4 moves the pitch Bass 1 plays (the DX EP pitch remains the same).

I also saw this behaviour in Reaper by:
- Creating a new project and track
- Adding Surge XT to the track FX
- Setting the patch to DX EP
- Loading the [scl](https://github.com/narenratan/tuning_example/blob/main/example.scl) and [kbm](https://github.com/narenratan/tuning_example/blob/main/example.kbm) files 
- Adding the Midi Sequencer Baby before Surge XT
- Setting the sequencer to loop midi note 0 and playing the track
- Switching between the DX EP and Bass 1 patches

This leads to the pitch moving by a major third when I switch between the patches

**Expected Behavior:**
I would expect that the pitches produced when using the DX EP and Bass 1 patches would be the same. In particular the DX EP pitch is the one I would expect.

**Computer Information (please complete the following!):**
 - OS: Linux (Arch Linux)
 - Host: Python and Reaper
 - Version: Python 3.10, Reaper v6.69

**Additional Information:**
This is a minimal example of something I ran into when using retuning with a just intonation sequencer I am working on. Using different patches for different parts in a song was changing the pitch of some parts. I made the scl and kbm files above with Scale Workshop to be safe.

**Comment by narenratan** [comment] 2023-01-14 14:07
I should say that last night I started looking into this by reading the Surge code and adding some print statements, which was very educational for me! Sadly I didn't get to the bottom of it though.

**Comment by mkruselj** [comment] 2023-01-14 14:55
IIRC Surge retunes over a wider key span (-255 to 255 midi keys, so it's going below MIDI note 0 virtually!). So if you have loaded SCL that have a different repetition interval, it is very likely that MIDI note 0 could end up on a different pitch.

**Comment by baconpaul** [comment] 2023-01-14 15:15
Right so this is not a bug.

The tuning has two modes. Tune at midi input or tune after modulation. These are detailed in the manual but the biggest difference here is the effect that the octave shift has. You will notice bass 1 has a 1 octave -ve shift and dx ep does not.

If you load these in the VST and change to "tune at midi input" then that means the raw key remapping happens before that octave modulation. The octave drop is really just a 12 key drop. If you do it at modulation then the octave drop drops you by scale length, which in the case of a one note scale is the 5/4 drop you see.

If you take DXEP in the 'tune at modulation' mode and make the scene octave shift -1 octaves, you will see the same thing.

Which mode is "correct" is a long and interesting question which we can't resolve and it really depends on context. But for the scale you have "tune at midi input" is almost always going to be what you want if you aren't doing modulation gestures.

You can change either of these by changing the flag on storage.

So I'm going to close this issue since it is expected behavior but expected behavior of a complicated system. Feel free to takg more stuff if you have questions or ask in #tuning channel on discord too!

**Closed by baconpaul** 2023-01-14 15:15 UTC
Labels: Bug Report

**Comment by narenratan** [comment] 2023-01-14 15:34
doh I hadn't read microtonal tuning section of the manual :facepalm: Thanks very much for explaining! Makes sense to me now. Will set to tune at midi input for the time being. Thanks for your help :)

**Comment by baconpaul** [comment] 2023-01-14 15:57
Great! And yeah this topic is one I often use when people ask me the difference between a component and an instrument - how and when to apply microtonality is tricky! Anyway have fun!
