### ISSUE TITLE
Installing surgepy as python package fails on macOS

### ISSUE THREAD

**Issue by cwalo** [surge-synthesizer/surge#7934] opened 2024-12-24 22:09 UTC
**Bug Description:**
Following the instructions [here](https://github.com/surge-synthesizer/surge/blob/main/scripts/ipy/Demonstrate%20Surge%20in%20Python.ipynb), building surgepy as a Python package on macOS 15.1 fails. Building manually succeeds. 

I've tracked it down to `juce_audio_basics.cpp` being compiled as c++ instead of objective-c++, since it contains obj-c code. i.e. `if (@available (macos 11.0, ios 14.0, *))`

I was able to get it to build by updating `common/CMakeLists.txt` to add compile options for this file. That said, I'm not sure if this is right. Maybe options should be set in `surge-python/CMakeLists.txt` since manual builds succeed? In any case, happy to submit a PR once we determine the ideal fix.

```
...
  if(APPLE)
    target_sources(juce_dsp_rack_sub PRIVATE
      ${SURGE_JUCE_PATH}/modules/juce_core/juce_core.mm
      ${SURGE_JUCE_PATH}/modules/juce_audio_formats/juce_audio_formats.mm
+     ${SURGE_JUCE_PATH}/modules/juce_audio_basics/juce_audio_basics.cpp
    )
+   set_source_files_properties(
+     ${SURGE_JUCE_PATH}/modules/juce_audio_basics/juce_audio_basics.cpp
+     PROPERTIES
+     COMPILE_OPTIONS "-x;objective-c++"
+   )
...
```

<details>
<summary>pip install output</summary>

```
(venv) ➜  surge git:(main) python3 -m pip install src/surge-python 
Processing ./src/surge-python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from surgepy==0.1.0)
  Downloading numpy-2.2.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Downloading numpy-2.2.1-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 21.4 MB/s eta 0:00:00
Building wheels for collected packages: surgepy
  Building wheel for surgepy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for surgepy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [223 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is AppleClang 16.0.0.16000026
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is AppleClang 16.0.0.16000026
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /Users/corey/Developer/surge/src/surge-python/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build
        Command:
          /private/var/folders/7x/z3zv97p540x8m3gh0w32pg0w0000gn/T/pip-build-env-kmrsbqde/overlay/lib/python3.13/site-packages/cmake/data/bin/cmake /Users/corey/Developer/surge -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-install -DPYTHON_VERSION_STRING:STRING=3.13.0 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/7x/z3zv97p540x8m3gh0w32pg0w0000gn/T/pip-build-env-kmrsbqde/overlay/lib/python3.13/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/Users/corey/Developer/surge/venv/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -DPYTHON_LIBRARY:PATH=/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/lib/libpython3.13.dylib -DPython_EXECUTABLE:PATH=/Users/corey/Developer/surge/venv/bin/python3 -DPython_ROOT_DIR:PATH=/Users/corey/Developer/surge/venv -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -DPython3_EXECUTABLE:PATH=/Users/corey/Developer/surge/venv/bin/python3 -DPython3_ROOT_DIR:PATH=/Users/corey/Developer/surge/venv -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -DCMAKE_MAKE_PROGRAM:FILEPATH=ninja -DSURGE_BUILD_PYTHON_BINDINGS=TRUE -DSURGE_SKIP_JUCE_FOR_RACK=TRUE -DSURGE_SKIP_ODDSOUND_MTS=TRUE -DSURGE_SKIP_VST3=TRUE -DSURGE_SKIP_ALSA=TRUE -DSURGE_SKIP_STANDALONE=TRUE -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=15.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64 -DCMAKE_BUILD_TYPE:STRING=Release
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 16.0.0.16000026
      -- The CXX compiler identification is AppleClang 16.0.0.16000026
      -- The ASM compiler identification is AppleClang
      -- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- It's Surge XT, folks! Version is 1.4.0
      -- CMAKE_BUILD_TYPE is Release
      -- CMake version is 3.31.2
      -- Compiler version is 16.0.0.16000026
      -- Targeting 64-bit configuration
      -- Performing Test COMPILER_HAS_AVX_OR_IS_ARM
      -- Performing Test COMPILER_HAS_AVX_OR_IS_ARM - Success
      -- Enabling tests; compile with SURGE_BUILD_TESTRUNNER=OFF to skip
      -- CMake version 3.31.2 allows CLAP build
      -- Building CLAP with CLAP_CXX_STANDARD=17
      -- CLAP version: 1.2.0
      CMake Warning (dev) at libs/clap-juce-extensions/clap-libs/clap-helpers/CMakeLists.txt:90 (install):
        Policy CMP0177 is not set: install() DESTINATION paths are normalized.  Run
        "cmake --help-policy CMP0177" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Building Surge XT using the following JUCE wrappers: AU
      -- Will build all of airwindows
      -- Version: 10.2.0
      -- Build type: Release
      -- Performing Test HAS_NULLPTR_WARNING
      -- Performing Test HAS_NULLPTR_WARNING - Success
      -- Including local pffft
      -- Including local sqlite
      -- Building LuaJIT at CMake time right now; configure with -DSURGE_SKIP_LUA=TRUE to disable
      -- Running ./build-macos-luajit.sh "/Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build/libs/luajitlib/LuaJIT" in /Users/corey/Developer/surge/libs/luajitlib
      -- Successfully built LuaJIT: /Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build/libs/luajitlib/LuaJIT/bin/arm64/libluajit.a;/Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build/libs/luajitlib/LuaJIT/bin/libluajit.a;/Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build/libs/luajitlib/LuaJIT/bin/x86_64/libluajit.a
      -- CMake Omitting Native Aliases
      -- Detecting Filesystem Support
      -- Performing Test SST_PLUGININFRA_FILESYSTEM_STD_FS_FOUND
      -- Performing Test SST_PLUGININFRA_FILESYSTEM_STD_FS_FOUND - Success
      -- filesystem: Using std::filesystem from <filesystem> with SST_PLUGINFRA_PLATFORM_FS
      -- Creating fs import via '/Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build/libs/sst/sst-plugininfra/libs/filesystem/include/filesystem/import.h'
      CMake Deprecation Warning at libs/PEGTL/CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.
      
      
      CMake Deprecation Warning at libs/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.
      
      
      -- pybind11 v2.10.3
      CMake Warning (dev) at libs/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      Call Stack (most recent call first):
        libs/pybind11/tools/pybind11Tools.cmake:50 (find_package)
        libs/pybind11/tools/pybind11Common.cmake:180 (include)
        libs/pybind11/CMakeLists.txt:208 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonInterp: /Users/corey/Developer/surge/venv/bin/python3 (found suitable version "3.13", minimum required is "3.6")
      -- Found PythonLibs: /opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/lib/libpython3.13.dylib
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Performing Test HAS_FLTO_THIN
      -- Performing Test HAS_FLTO_THIN - Success
      -- Building Python package with scikit-build
      -- Installer Surge Version is LOCAL
      -- Found Git: /usr/bin/git (found version "2.39.5 (Apple Git-154)")
      -- Adding download-extra-content target from https://github.com/surge-synthesizer/surge-extra-content.git
      -- Configuring done (16.0s)
      -- Generating done (0.1s)
      -- Build files have been written to: /Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build
      [1/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/ADClip7Proc.cpp.o
      [2/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/ApicolypseProc.cpp.o
      [3/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/AirProc.cpp.o
      [4/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/Air.cpp.o
      [5/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/ADClip7.cpp.o
      [6/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/Apicolypse.cpp.o
      [7/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BassDriveProc.cpp.o
      [8/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BitGlitterProc.cpp.o
      [9/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BassDrive.cpp.o
      [10/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BlockParty.cpp.o
      [11/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BlockPartyProc.cpp.o
      [12/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BitGlitter.cpp.o
      [13/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/AirWinBaseClass_pluginRegistry.cpp.o
      [14/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BrightAmbience2.cpp.o
      [15/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BrightAmbience2Proc.cpp.o
      [16/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BussColors4.cpp.o
      [17/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/ButterComp2Proc.cpp.o
      [18/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/ButterComp2.cpp.o
      [19/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/BussColors4Proc.cpp.o
      [20/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/Cabs.cpp.o
      [21/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/CapacitorProc.cpp.o
      [22/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/ChamberProc.cpp.o
      [23/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/Capacitor.cpp.o
      [24/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/Chamber.cpp.o
      [25/306] Building CXX object src/common/CMakeFiles/juce_dsp_rack_sub.dir/__/__/libs/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.o
      FAILED: src/common/CMakeFiles/juce_dsp_rack_sub.dir/__/__/libs/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.o
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DJUCE_GLOBAL_MODULE_SETTINGS_INCLUDED=1 -DJUCE_MODULE_AVAILABLE_juce_audio_basics=1 -DJUCE_MODULE_AVAILABLE_juce_core=1 -DJUCE_MODULE_AVAILABLE_juce_dsp=1 -DJUCE_MODULE_VAILABLE_juce_audio_formats=1 -DJUCE_STANDALONE_APPLICATION=0 -DJUCE_USE_CURL=0 -DJUCE_USE_FLAC=0 -DJUCE_USE_OGGVORBIS=0 -DJUCE_USE_WINDOWS_MEDIA_FORMAT=0 -DJUCE_WEB_BROWSER=0 -DNDEBUG=1 -I/Users/corey/Developer/surge/src/../libs/JUCE/modules -O3 -DNDEBUG -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -mmacosx-version-min=15.0 -fPIC -Wno-multichar -Werror -fvisibility=hidden -fvisibility-inlines-hidden -Wno-unused-command-line-argument -Wno-deprecated-declarations -Werror=inconsistent-missing-override -Werror=logical-op-parentheses -Werror=dynamic-class-memaccess -Werror=undefined-bool-conversion -Werror=bitwise-op-parentheses -Werror=pointer-bool-conversion -faligned-allocation -fasm-blocks -MD -MT src/common/CMakeFiles/juce_dsp_rack_sub.dir/__/__/libs/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.o -MF src/common/CMakeFiles/juce_dsp_rack_sub.dir/__/__/libs/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.o.d -o src/common/CMakeFiles/juce_dsp_rack_sub.dir/__/__/libs/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.o -c /Users/corey/Developer/surge/libs/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp
      In file included from /Users/corey/Developer/surge/libs/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp:111:
      /Users/corey/Developer/surge/libs/JUCE/modules/juce_audio_basics/utilities/juce_AudioWorkgroup.cpp:71:13: error: expected expression
         71 |         if (@available (macos 11.0, ios 14.0, *))
            |             ^
      /Users/corey/Developer/surge/libs/JUCE/modules/juce_audio_basics/utilities/juce_AudioWorkgroup.cpp:77:13: error: expected expression
         77 |         if (@available (macos 11.0, ios 14.0, *))
            |             ^
      /Users/corey/Developer/surge/libs/JUCE/modules/juce_audio_basics/utilities/juce_AudioWorkgroup.cpp:223:9: error: expected expression
        223 |     if (@available (macos 11.0, ios 14.0, *))
            |         ^
      3 errors generated.
      [26/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/ChromeOxide.cpp.o
      [27/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/CojonesProc.cpp.o
      [28/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/ChromeOxideProc.cpp.o
      [29/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/Cojones.cpp.o
      [30/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/Compresaturator.cpp.o
      [31/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/CompresaturatorProc.cpp.o
      [32/306] Building CXX object libs/airwindows/CMakeFiles/airwindows.dir/src/CabsProc.cpp.o
      [33/306] Building CXX object src/common/CMakeFiles/juce_dsp_rack_sub.dir/__/__/libs/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o
      [34/306] Building CXX object src/common/CMakeFiles/juce_dsp_rack_sub.dir/__/__/libs/JUCE/modules/juce_dsp/juce_dsp.cpp.o
      [35/306] cd /Users/corey/Developer/surge && /private/var/folders/7x/z3zv97p540x8m3gh0w32pg0w0000gn/T/pip-build-env-kmrsbqde/overlay/lib/python3.13/site-packages/cmake/data/bin/cmake -D CMAKE_PROJECT_VERSION_MAJOR=1 -D CMAKE_PROJECT_VERSION_MINOR=4 -D SURGESRC=/Users/corey/Developer/surge -D SURGEBLD=/Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build -D AZURE_PIPELINE= -D WIN32= -D CMAKE_INSTALL_PREFIX=/Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-install -D CMAKE_CXX_COMPILER_ID=AppleClang -D CMAKE_CXX_COMPILER_VERSION=16.0.0.16000026 -P /Users/corey/Developer/surge/cmake/versiontools.cmake
      -- Found Git: /usr/bin/git (found version "2.39.5 (Apple Git-154)")
      -- Setting up surge version
      --   git hash is 4cb028d1 and branch is main
      --   buildhost is Coreys-Laptop.local
      --   buildarch is arm64
      -- Developer Local Build
      -- Using SURGE_VERSION=1.4.main.4cb028d1
      -- Configuring /Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build/geninclude/version.cpp
      [36/306] Building CXX object src/common/CMakeFiles/juce_dsp_rack_sub.dir/__/__/libs/JUCE/modules/juce_core/juce_core.mm.o
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/private/var/folders/7x/z3zv97p540x8m3gh0w32pg0w0000gn/T/pip-build-env-kmrsbqde/overlay/lib/python3.13/site-packages/skbuild/setuptools_wrap.py", line 668, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/7x/z3zv97p540x8m3gh0w32pg0w0000gn/T/pip-build-env-kmrsbqde/overlay/lib/python3.13/site-packages/skbuild/cmaker.py", line 696, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/7x/z3zv97p540x8m3gh0w32pg0w0000gn/T/pip-build-env-kmrsbqde/overlay/lib/python3.13/site-packages/skbuild/cmaker.py", line 741, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /private/var/folders/7x/z3zv97p540x8m3gh0w32pg0w0000gn/T/pip-build-env-kmrsbqde/overlay/lib/python3.13/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /Users/corey/Developer/surge/src/surge-python
        Working directory:
          /Users/corey/Developer/surge/src/surge-python/_skbuild/macosx-15.0-arm64-3.13/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for surgepy
Failed to build surgepy

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (surgepy)
```
</details>

**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.

* Version: 1.3.4
* Plugin Type: [VST3, AU]
* Bitness: 64-bit
* Checkout commit: main @ 4cb028d1dd4e000e29fd40708a6a7e71099b8322

**Reproduction Steps:**

```
git clone git@github.com:surge-synthesizer/surge.git
python3 -m venv venv
source venv/bin/activate
python3 -m pip install surge/src/surge-python
```
Result -> Build fails, see output above

**Expected Behavior:**
Python package builds successfully

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: macOS 15.1.1
 - Arch: M1 - arm64
 - Host: Ableton
 - Version: 12

**Additional Information:**

**Comment by baconpaul** [comment] 2024-12-26 00:48
I wonder if we need a lang objc for surgery because of the way we compile juce?

@narenratan you set up the pip build yeah? Any thoughts?

**Comment by narenratan** [comment] 2024-12-26 11:33
Hi folks, yep I set up the pip build. Thanks for the great bug report!

I also see the failing build on Mac. Looking at it, I think the build fails because we set `SURGE_SKIP_JUCE_FOR_RACK` for the pip build [here](https://github.com/surge-synthesizer/surge/blob/main/src/surge-python/setup.py#L34). I get the same build failure running
```
$ cmake -Bbuild -DSURGE_SKIP_JUCE_FOR_RACK=TRUE
$ cmake --build build
```
in the top level repo directory.

I also tested building surgepy on Linux, and while the build succeeds with the current main branch, actually importing surgepy I get an undefined symbol error:
```
Python 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import surgepy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/naren/repos/venv/lib/python3.12/site-packages/surgepy/__init__.py", line 1, in <module>
    from ._surgepy import *
ImportError: /home/naren/repos/venv/lib/python3.12/site-packages/surgepy/_surgepy.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZN4juce20juce_compilationTimeE
>>>
```
Removing `SURGE_SKIP_JUCE_FOR_RACK` in setup.py fixes the undefined symbol error on Linux.

Removing `SURGE_SKIP_JUCE_FOR_RACK`, on Mac I then get a CMake error `Cannot add target-level dependencies to non-existent target "surge-xt_Standalone"`. Removing `SURGE_SKIP_STANDALONE` from setup.py, I then get an error:
```
  /Users/naren/repos/surge/src/surge-xt/gui/SurgeGUIEditor.cpp:458:20: error: no member named 'uiThreadChecksTunings' in 'SurgeStorage'
    458 |     synth->storage.uiThreadChecksTunings = true;
        |     ~~~~~~~~~~~~~~ ^
  /Users/naren/repos/surge/src/surge-xt/gui/SurgeGUIEditor.cpp:471:20: error: no member named 'uiThreadChecksTunings' in 'SurgeStorage'
    471 |     synth->storage.uiThreadChecksTunings = false;
        |
```
which comes from the surgepy build setting `SURGE_SKIP_ODDSOUND_MTS`. It looks like some MTS-ESP bits in the code don't currently have `#ifndef SURGE_SKIP_ODDSOUND_MTS` checks, e.g. in `src/surge-xt/gui/overlays/TuningOverlays.cpp` - I can make a separate PR adding these.

So I think the simplest change to get a surgepy build which passes the `src/surge-python/tests/test_surgepy.py` tests on Mac and Linux is:
```
diff --git a/src/surge-python/setup.py b/src/surge-python/setup.py
index 6684e9ab..6e7c6da3 100644
--- a/src/surge-python/setup.py
+++ b/src/surge-python/setup.py
@@ -31,11 +31,11 @@ setup(
     cmake_source_dir="../..",
     cmake_args=[
         "-DSURGE_BUILD_PYTHON_BINDINGS=TRUE",
-        "-DSURGE_SKIP_JUCE_FOR_RACK=TRUE",
-        "-DSURGE_SKIP_ODDSOUND_MTS=TRUE",
+        # "-DSURGE_SKIP_JUCE_FOR_RACK=TRUE",
+        # "-DSURGE_SKIP_ODDSOUND_MTS=TRUE",
         "-DSURGE_SKIP_VST3=TRUE",
         "-DSURGE_SKIP_ALSA=TRUE",
-        "-DSURGE_SKIP_STANDALONE=TRUE",
+        # "-DSURGE_SKIP_STANDALONE=TRUE",
     ],
     cmake_process_manifest_hook=just_surgepy,
     package_data={"surgepy": [*find_stubs(path=Path("surgepy"))]},
```
If I understand correctly these SKIP flags are there to speed up the surgepy build, so I could make a PR removing them for now and then look into adding them back if that sounds OK? Adding back `SURGE_SKIP_ODDSOUND_MTS` doesn't look too tricky; the undefined symbol error on Linux with `SURGE_SKIP_JUCE_FOR_RACK` and the CMake error on Mac with `SURGE_SKIP_STANDALONE` might be trickier but I can certainly have a go!

**Comment by baconpaul** [comment] 2024-12-26 13:47
Wow great stuff

I bet the skip juce has blown up now we are on juce 8

skip juce can’t actually skip juce because of a few effects so it just skips almost all of juce. Fixing that is #7879 which means the whole surge common juce thing can be reworked 

but the very first thing tou identify will blow up vcv rack when I pull to surge 14 so I think investigating and fixing that will help - I’ll look at it soon

**Comment by cwalo** [comment] 2024-12-26 22:07
Thanks for digging in so quickly! Let me know if there's anything I can help with or test.

**Comment by baconpaul** [comment] 2024-12-27 15:00
OK #7939 makes it so the builds work on macOS, but I didn't actually get around to testing if it loads. It should also fix the missing symbol on linux but I don't have a linux box booted right now.

All indeed related to juce 8 changes.

once I merge that, if you could give the pip builds a test go and if they work we can close this and if not lets see what the problem is.

**Comment by baconpaul** [comment] 2024-12-27 15:14
That change is now merged, if you want to test the pip builds with it. Let me know!

**Comment by narenratan** [comment] 2024-12-27 17:21
Thanks very much Paul! For me the pip build now succeeds on Mac and Linux (using latest main code aaf3c073). Also on Mac and Linux the `test_surgepy.py` tests pass, and I tested manually calling `surgepy.createSurge` in the interpreter. So all looks good to me!

**Comment by baconpaul** [comment] 2024-12-27 17:44
Great! Will close this issue then.

Thanks for the super clear report @cwalo and the great but hanging @narenratan

**Closed by baconpaul** 2024-12-27 17:44 UTC
Labels: Bug Report

**Comment by cwalo** [comment] 2024-12-27 19:12
Nice! Just pulled the latest and the pip build also succeeds for me on macOS. Thanks a bunch gang!
