### ISSUE TITLE
Switching to and from Audio Passthru Mono or Stereo will cause very loud clicks on the left channel

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#531] opened 2019-02-07 16:14 UTC
I am using the cursor up&down keys to switch between `Audio PassThru Mono` and `Audio Passthru Stereo` - both of which will result in a loud click on the left channel. I came across this while testing cursor up/down/left/right and switched from a non-audio preset to an audio-preset.

![audio passthru mono stereo switching causes clicks](https://user-images.githubusercontent.com/4966687/52425120-05485200-2b04-11e9-88e1-ddffbf4b3f21.gif)

**Comment by esaruoho** [comment] 2019-02-07 16:19
Note: The clicking behaviour can be replicated by just switching from `Latch` to `Mono ST+FP` - each click (to and fro) will result in a click on VST2.

No clicks with LogicAU when switching between Latch / Mono ST+FP, or switching from patch to patch.

**Comment by baconpaul** [comment] 2019-03-11 13:13
@esaruoho as with all the other click n pop problems I can't reproduce this reliably. Can you?

(They are real; just they don't occur reliably)

**Comment by baconpaul** [comment] 2019-03-11 13:19
OK now I know what's causing click n pop I am going to close this issue and consolidate it with the others

**Closed by baconpaul** 2019-03-11 13:19 UTC
Labels: audio issue, clicks n pops
