### ISSUE TITLE
Host automation of Active scene and Scene mode doesn't update GUI

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2226] opened 2020-06-28 17:55 UTC
**Describe the bug**
Host automation of "active scene" and "scene mode" variables are not visually automated. You can only see that the automation is happening if you click on something related to the oscillator

![106](https://user-images.githubusercontent.com/56724286/85954503-3daa3380-b978-11ea-8b43-2be73cbb47f8.gif)

**To Reproduce**
send host automation active scene and scene mode

Edit: VST3 is actually showing host automation on scene mode but VST2 does not, why is that?
Edit 2: both VST3 and VST2 is not showing automation on active scene

**Comment by baconpaul** [comment] 2020-06-28 18:05
Both those controls force a UI frefrehs when manually clicked; so it probably just doesn't do that on the DAW path around the nonmod things. Should be an easy fix.

**Comment by baconpaul** [comment] 2020-06-29 11:56
So backing out that change. The problem is the rebuild, while correct, breaks edits in flight

So what we want is to have separate indicators for which scene is acrtive and which scene is being edited.

Then automate active
 but not for 1.7.0

**Comment by baconpaul** [comment] 2020-11-29 02:42
I’m almost 100% sure my fix for live also fixed this. Can you confirm it is still a problem at head @K0rrid0r - like I said I think it is fixed now.

**Comment by VincyZed** [comment] 2021-01-16 00:57
Just tested this, and it worked fine with Scene Mode. I wasn't able to automate Selected Scene in the first place. Closing this for now as it seems to be fixed.

**Closed by VincyZed** 2021-01-16 00:57 UTC
Labels: Bug Report, Host Automation, UI
