### ISSUE TITLE
Waveshaping control "seems like it's bust" - sound reduced to nothing

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#538] opened 2019-02-07 21:03 UTC
Window 8.1, tried it in Renoise. Will try Bitwig next time.
* Seems like the waveshaping control is bust. When it's set to "soft" the sound reduced to nothing when the amount slider is increased. I tried with the last versino from Vember and it worked OK

from 
https://www.kvraudio.com/forum/viewtopic.php?p=7307924#p7307924

**Comment by baconpaul** [comment] 2019-02-14 02:04
So I played around with this a bit. Took the EP2 patch and ran sequences through it and turned the wave shaper to soft

Soft, Hard, Asym and Sine all have the behavior that the control acts like an attenuator as well as a shaper it seems. So at -24db there's no sound and at +24db there's plenty.

Can we get some more info from the user on the exact situation?

**Comment by baconpaul** [comment] 2019-03-07 22:53
Just a ping on this one @esaruoho - any idea what the problem is?

**Comment by baconpaul** [comment] 2019-04-01 23:11
So I am pretty sure the wave shaper is fine playing with it. I'm gonna close this issue.

**Closed** 2019-04-30 17:40 UTC
