### ISSUE TITLE
Preset menu is very slow and causes crashes frequently VST/LV2 on Linux

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1101] opened 2019-09-04 05:33 UTC
**Describe the bug**
This bug report is from my experience VST and LV2 on REAPER, Ardour, Carla and RENOISE.

The preset menu opens on VST and LV2 in linux for me, but it sometimes crashes the host immediately, sometimes stays open and crashes if you try and click somewhere, sometimes works fine, but is always just very very slow.
It ALWAYS crashes if I open the preset menu and then try and move the plugin Window.

The list is also truncated well below the maximum size it could be taking up
![truncatedPresets](https://user-images.githubusercontent.com/4732794/64228004-1d6e2d00-ceab-11e9-98b9-77f89ca1db05.png)
:

SYSTEM INFO
The latest nightly, first version with LV2
I'm on the latest lubuntu 19.04 a lightweight Ubuntu distro.
UNAME printout:
5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 GNU/Linux
Latest stable Ardour, REAPER, RENOISE and Carla

**Comment by baconpaul** [comment] 2019-09-04 10:50
A lot of related content over on #617 for this one

**Comment by jpcima** [comment] 2019-09-04 13:53
It is indeed very slow; and also CPU usage high in the editor, which is another thing to have a look at.
I can't get it to crash though. Are you able to extract a gdb backtrace from a debug build?
Perhaps, this will give an idea of the location of the problem.

**Comment by jpcima** [comment] 2019-09-04 13:56
Oh, I just noted a code defect at this location. The function must return a value but doesn't.

https://github.com/surge-synthesizer/surge/blob/6c7f30fe9ff8f3da4f6c9de2b448bcf7cce8d71f/src/linux/LinuxVST3Helpers.cpp#L164-L172

**Comment by mortfell** [comment] 2019-09-04 13:59
I’m not set up to build from source but I can maybe do that tonight.

**Comment by baconpaul** [comment] 2019-09-04 14:05
Oh yeah that does need to return a value; but it only exits at the end fo the loop thread basically. It can safely return NULL.

If you take a look at the other linux menu issues you can see some of my attempts to debug the weird animator code in vstgui which is causing a lot of the slowness.

**Comment by baconpaul** [comment] 2019-09-05 11:51
OK I tried reaper vst3 ubuntu 18 in parallels on my 2014 MacBook pro.

No problem with the preset menus

They have the same cruddy animation the other menus do but work and are OK both for the full list (right) and category only (left) button menu.

I think the problem here is that the VSTGUI menu code is kinda junk. We have a fork of vstgui to apply other changes we needed. So either

1) we can try and bring that form up to master and remerge those changes and see if that fixes. Or
2) we can try and fix on our fork

Neither of those are things I have an appetite to do before 1.6.2 though since they have far ranging impact on all the hosts.

I wonder what is making it so slow for you? Something in your drawing pipeline isn't interacting with cairo well it seems.

**Comment by mortfell** [comment] 2019-09-05 14:48
yeah, I'm really not sure, seems like it's slow for both me and @jpcima 
I'll keep testing the linux version when I have time, try some different debugging things.

**Comment by jpcima** [comment] 2019-09-05 14:50
It was extremely slow, especially if I hover the expanding menus up and down, seems like to slow down the host itself to a full halt with the more I do it.

**Comment by mortfell** [comment] 2019-09-05 14:51
yeah, that sounds like exactly the issue Im having as well

**Comment by baconpaul** [comment] 2019-09-05 15:12
Right

So there's some animation happening in vstgui which runs some timers and stuff to fade the menus in and out. I bet the problem is there somewhere.

I never figured out how to disable that animation but to be honest I didn't look that closely.

Is the left button (category browse presets) fast? It's just the nesting that gets you?

Again the first time we looked at this we discussed it over on #617 

but I think what needs to happen is someone who is brave and understands cairo dives into vstgui.surge/vstgui/lib/platform/common/genericoptionmenu* to see what's going on. That code is only used on linux (on mac and windows vstgui uses the OS provided menus)

Also super helpful would be to profile the system when running the menus. On macOS I have a good sampling profiler - presume linux has exactly the same available. That could let us know where the time is going.

**Comment by baconpaul** [comment] 2019-09-05 15:17
and now looking at that code I remember where I got lost last time; that whole "database" thing is really confusing. 

But I do see that closeSubMenu has an allowAnimation argument which defaults to true; and the animation only occurs 3 places. So I think it would be feasible to set it to 'immediate'.

Or alternately set the CubicBezierTimingFunction in there to some other TimingFunction subclass (which is all in vstgui/lib/animation/timingfunction.h) to a new TimingFunction which just does an immediate blat. Again this is just from me scanning the code now.

But profile first for sure.

**Comment by baconpaul** [comment] 2019-09-05 15:19
Oh and the list truncation is because the menu has to draw within the bounds of the parent container; since it isn't a system menu with its own window but is rather just a drawn artifact on top of the frame.

**Comment by jpcima** [comment] 2019-09-05 15:29
Thanks for info, myself I'm trying right now to dig and disable this or that, see what happens.
I do have some familiarity with cairo, as it my primary drawing library for plugins; of Vstgui, not so much.

I'm going to examine this animation business as suggested.
The slowness problems didn't seem to emanate from scalable graphics, that part I've verified.
Profiling is a definite good idea.

**Comment by baconpaul** [comment] 2019-09-05 15:45
Yeah profile first for sure

But I bet if you

1 make an immediate jumoyimer with length of 1ms that jumps to end and
2: replace the 4 instances of beziertimer with that

Things will be better

In the doc directory of the main repo is information about our vstgui fork. Basically if you end up wanting to patch vstgui it could be a tad tricky first time - just multi repo multi branch shenanigans but we are set up to make it possible

**Comment by jpcima** [comment] 2019-09-05 15:53
I have applied this patch, to disable the closing animation.
https://gist.github.com/jpcima/cda8d83462ca27b0782a0d7e42d368da

Now, the menu works remarkably better !!!
I mean, it still shows some very ephemeral ghosting artifacts, but it's no longer slow or hanging user interface.

In the patch though, I had to add the null assignment, or it will produce a direct crash. (which I hope is correct as a fix, the animated branch does it also)

**Comment by baconpaul** [comment] 2019-09-05 16:04
Great; I added a comment on the gist.

**Comment by baconpaul** [comment] 2019-09-05 18:12
Your latest version of the fix is spot on. I am in the middle of applying it now. It makes the menus so much better.

@tank-trax has also done a lot of linux testing for us. Let me tag him here too. Once I get it all pushed I'll update this issue and a new build should have the fix (but remember it will require a git submodule update --init --recursive). Probably 30 more minutes of git shenanigans.

**Comment by jpcima** [comment] 2019-09-05 18:20
Well it's your fix honestly more than it is mine. :)
Your intuition about the animation has shown to be the right track.

**Comment by baconpaul** [comment] 2019-09-05 18:24
Ha well thanks. But you know how pair programming always works out. I banged my head against that for a few hours in the spring, couldn't get it, then forgot about it.  Then you and @mortfell find out it is even more borked than we thought. So then looked and said "maybe its here". You look at it fresh and say "oh yeah here's how you disable it". And now it's fixed. (Almost). So teamwork!!

**Comment by baconpaul** [comment] 2019-09-05 18:25
Also I confirmed a substantial improvement in both the VST3 and LV2 with the patch in place. 

CI running now.

**Comment by baconpaul** [comment] 2019-09-05 18:32
OK I have merged the change. 

If you are building yourself, not only do you need to pull master, but you need to `git submodule update --init --recursive` to get the changes to vstgui.surge submodule

If someone can confirm the improvement that we saw from the master branch, I think we can close this issue.

Great addition. Really a super improvement.

**Comment by baconpaul** [comment] 2019-09-05 18:33
Oh and the nightly build is still running; so will take about 30 minutes for this to hit the .deb nightly.

**Comment by jpcima** [comment] 2019-09-05 19:01
I took opportunity of this updating moment to take a break.
Just made the update, all seems good.

**Comment by baconpaul** [comment] 2019-09-05 19:02
Fantastic. I'll close this issue then. Great stuff!

**Closed by baconpaul** 2019-09-05 19:02 UTC
Labels: linux

**Comment by mortfell** [comment] 2019-09-05 20:33
Sill a little slow on my system, but much much better
