### ISSUE TITLE
Window appears broken but becomes normal after moving it

### ISSUE THREAD

**Issue by pouyah85** [surge-synthesizer/surge#2909] opened 2020-10-19 11:20 UTC
When surge is opened the window is shown as in the picture i attached. When moving it it becomes normal again. 

Surge version 1.7.1 onwards. even the recent nightly builds
This information is found on the About screen, which you get to from the bottom right menu

* Version: 1.7.1 - 1.8.0
* Plugin Type: VST3 Windows
* Bitness: 64-bit
**Reproduction Steps:**
1. Open surge
2. Move screen
3. 
4.

**Expected Behavior:**
That the screen starts up normal

**Screenshots:**
![surge 1 71 onwards](https://user-images.githubusercontent.com/73111006/96443970-baa23700-120d-11eb-8839-1466c17f5b23.jpg)

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Ableton
 - Version: 10.1.25 

**Additional Information:**

**Comment by mkruselj** [comment] 2020-10-19 12:02
This to me looks like Live's HiDPI compatibility option meddling with things.

https://help.ableton.com/hc/en-us/articles/209775985-High-DPI-monitor-support-Windows-10-

Try disabling Auto-scale Plugin Window option.

**Comment by pouyah85** [comment] 2020-10-19 12:34
Hi again. This problem is prevalent without the auto-scale. With auto-scale everything gets blurry. And yes, it's a HiDpi screen

**Comment by baconpaul** [comment] 2020-10-19 12:41
Yeah looks like live is giving us half the screen geometry we need.

**Comment by baconpaul** [comment] 2020-10-19 13:07
Wonder that vst3 comment if they are calling IPlugViewContentScaleSupport which we don’t support yet. I’ll peek this week

**Comment by mkruselj** [comment] 2020-11-23 10:56
This actually also happens on non-HiDPI display. Over here at 1920x1200 Surge opens initially like this:

![image](https://user-images.githubusercontent.com/2393720/99954344-e1123f80-2d82-11eb-8711-e0dd6abfa6fd.png)

If I close it then reopen it unscrews itself.

**Comment by baconpaul** [comment] 2020-11-23 12:33
What’s wrong in that screenshot?

**Comment by mkruselj** [comment] 2020-11-24 23:41
@baconpaul See the extra black borders around? That's what was wrong.

But looks like @Kingston1's zoom PR fixed it! So would be great to hear from @pouyah85 if the latest nightly fixes this issue for him, so that we can close this issue!

**Comment by Kingston1** [comment] 2020-11-29 19:15
I had a friend test this in Ableton 10 and Windows 7.

The original bug is fixed, but slightly glitched window edge still: https://i.imgur.com/kaAd3ZF.png

**Comment by baconpaul** [comment] 2020-11-29 19:40
I wonder if that glitch is the aspect ratio stuff being ignored?

**Comment by mkruselj** [comment] 2020-11-29 21:38
But isn't aspect ratio ignore there only for FL?

**Comment by baconpaul** [comment] 2020-11-29 21:49
The purposeful one is on for fl 
The buggy one in #3268 is for all hosts 
So I was saying that I bet the extra is the same bug as #3268

**Comment by Kingston1** [comment] 2020-11-29 23:04
Ok now I see a more generic issue with the window size still. This thing from Live actually reproduces in Cubase 11, too. I just did not see it because the dark skin right side does not have those small global/fs/fsunit texts in it. 
![image](https://user-images.githubusercontent.com/5409091/100556045-0da8e880-32a8-11eb-91cc-ff80a4661794.png)

**Comment by pouyah85** [comment] 2020-11-30 17:01
Hey guys, The problem is still there with the recent nightly build unfortunately

**Comment by baconpaul** [comment] 2020-11-30 18:35
So I just installed Live 10 trial on windows, and my VM has HDPI.
Both with HDPI on and off at top of codebase I have no problem with sizing in the DAW
Any more information about your display? What's your scale set to perhaps?

**Comment by baconpaul** [comment] 2020-12-01 16:11
Also if you can let us know exactly which nightly you are using (once you have the UI restored, do menu / about and you will see info; press 'copy version info' and paste into this issue from your clipboard) that would help. thank you

**Comment by mkruselj** [comment] 2020-12-19 15:37
OK so I tested the very latest nightly in Live 10.1.30 on my Surface Pro 4, which has a HiDPI display, it's set to 200% UI scaling at OS level. Surge opens just fine without any extraneous black borders.

Closing this issue as fixed.

**Closed by mkruselj** 2020-12-19 15:37 UTC
Labels: Awaiting User Information, Bug Report, Host Specific, UI
