### ISSUE TITLE
More control over the input/output of the filters and the ability adjust filter mix

### ISSUE THREAD

**Issue by TheGuyWhoo** [surge-synthesizer/surge#6697] opened 2022-11-09 12:25 UTC
The only thing that makes me reach for vital over surge, despite vital being very resource hungry and preferring the character and tone shaping options in surge, is the fact that we have so little control over the routing and mixing of the filters. This is a limitation that greatly affects some physical modeling(esque) processes that would otherwise be possible, for example:

Kalimba: https://www.youtube.com/watch?v=MGfL5dQee9M

Harp and bowed string: https://www.youtube.com/watch?v=LgNEvGVFz9Y

Flute: https://www.youtube.com/watch?v=wVul3xKs7xA

These kinds of processes would be very cool to explore with the audio input of feature of surge! Another cool feature idea would be the ability to route the effects before the filter and distortion.

**Comment by baconpaul** [comment] 2022-11-09 12:44
So overall we agree completely. In the vst it is rather hard but we have a plan in a future version to add pretty arbitrary filter routing - there’s several issues here but #4355 is the main one but search the issues for filter and you can find others 

but today if you are a rack user you can use the new surge xt rack modules to try arbitrary configurations! 

I propose we consolidate your comments into 4355 and then close this issue if that’s ok with you. It’s spot on but it is quite a big change

**Comment by mkruselj** [comment] 2022-11-09 13:00
#4355 will fully resolve what you want to do, but we need time to get there indeed. 🙂

**Comment by TheGuyWhoo** [comment] 2022-11-12 14:27
Sorry for the delay! I'm totally cool with consolidating this into 4355.

**Comment by mkruselj** [comment] 2022-11-12 15:11
Great, thanks! In that case, closing this issue as a duplicate of #4355. 🙂

**Closed by mkruselj** 2022-11-12 15:11 UTC
Labels: Feature Request

**Comment by TheGuyWhoo** [comment] 2022-11-13 13:02
Is there any way I can load oneshots into surge and use it like a sampler? I'm not sure I quite understand the wavetable osc. For some samples it allows me to just load the sample and play them back like a regular sampler(like the organics noise samples from serum for example), but then I load an 808 or something like and it functions like a normal wavetable synth again.

Sorry for littering, I don't know where else to ask and don't want to open an issue unnecessarily.

**Comment by baconpaul** [comment] 2022-11-13 13:14
short answer is: not really
longer answer is: wavetable kinda does this when you load a one shot.
I think the manual describes this pretty well but I haven't read that section in a while I'll be honest :)

but please do feel free to open new issues or ask on our discord. its easier than having issues become about "2" things. (Although no worries that you asked here).

**Comment by mkruselj** [comment] 2022-11-13 16:06
BTW you can search all existing issues to find one that might potentially be related to the thing you want to ask...
