### ISSUE TITLE
Stereo to mono noise

### ISSUE THREAD

**Issue by Lo-lo78** [surge-synthesizer/surge#6604] opened 2022-09-10 06:21 UTC
**Is your feature request related to a problem? Please describe!**
A clear and concise description of what the problem is. e.g. I'm always frustrated when [...]
Surge's noise is stereo only. In some situations it would be useful to switch from stereo noise to mono.
**Describe the solution you'd like:**
The oscillator is mono and when I use the noise it is always stereo. One button to switch from stereo to mono to mono to stereo solves many situations.
**Describe alternatives you've considered:**
It would be useful to create a noise button. Or even two buttons. One stereo and another mono.
**Additional context:**

Thanks to the team!

**Comment by Andreya-Autumn** [comment] 2022-09-10 07:08
Duplicate of #6494, which there is a plan for, so I'm closing. ;)

**Closed by Andreya-Autumn** 2022-09-10 07:08 UTC
Labels: Feature Request
