### ISSUE TITLE
quick preset search

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#4775] opened 2021-07-27 03:07 UTC
**Is your feature request related to a problem? Please describe.**
i have tons of presets and sometimes it's hard to find the ones i want or very slow to browse them with the mouse

**Describe the solution you'd like:**
Double clicking the preset name could turn the preset name bar into a search bar. Similar to quicksilver / OSX spotlight

![image](https://user-images.githubusercontent.com/27327/127088825-9d5232c6-0b83-472a-bbd5-5ff064aa8556.png)

![image](https://user-images.githubusercontent.com/27327/127088864-8f6900bd-5c3c-4a17-ab52-b68892405ecb.png)

![image](https://user-images.githubusercontent.com/27327/127088903-accec0a4-dc80-4fae-9722-89bf9aeff948.png)

**Describe alternatives you've considered:**
using Windows or OSX to search the preset files directly from the OS file finder

**Additional context:**
I reckon this is related to https://github.com/surge-synthesizer/surge/issues/2359 but somehow simpler / aiming to be a quick find as opposed to a database search with tag support, etcs

**Comment by mkruselj** [comment] 2021-07-27 06:48
Surge XT already has this pretty much when you open Patch Database (right click patch browser) . We're working on a full fledged patch browser with tags AND text search for XT.

This is basically a duplicate of #2359 so closing this one.

**Closed by mkruselj** 2021-07-27 06:48 UTC

**Comment by baconpaul** [comment] 2021-07-27 11:22
I like the idea of a quick typeahead search in the ui though and it’s easy to code since we’ve coded it so agree we should include that in the browser work

**Comment by hems** [comment] 2021-08-04 12:36
> Surge XT already has this pretty much when you open Patch Database (right click patch browser) . We're working on a full fledged patch browser with tags AND text search for XT.
> 
> This is basically a duplicate of #2359 so closing this one.

i see, i didn't know that feature, and it needs loads of clicks to arrive there! but it's definitely a start!

**Comment by baconpaul** [comment] 2021-08-04 13:57
yeah it is super duper alpha! Like the rest of the new features in XT
If you download an XT from the last few days, though, shift click on the patch name will open that screen.

**Comment by mkruselj** [comment] 2021-08-04 14:13
Two clicks is not "loads of clicks" IMO. :)

**Comment by baconpaul** [comment] 2021-08-04 14:57
well it is a bit hard to find in the menu now I agree. and then navigating doesn't get focus properly and so on.

like i said - it is super duper alpha.

**Comment by hems** [comment] 2021-08-04 15:47
> If you download an XT from the last few days, though, shift click on the patch name will open that screen.

good to know, i didn't know that!

**Comment by hems** [comment] 2021-08-04 15:47
> Two clicks is not "loads of clicks" IMO. :)

IMO two clicks aren't much as well, but that definitely is something i wouldn't have discovered by myself.

good work tough, it's a great progress, we just need to make it smoother now : D

thank you!

**Comment by baconpaul** [comment] 2021-08-05 01:48
yeah our idea is that the final patch browser becomes the default screen to pop up when you click and the old menu is a user option as default launch and moves to shift click. Or something like that. but we aren't even close to there yet. Lots to do on XT.
