### ISSUE TITLE
Reaper: Setting the zoom to 175% on Royal skin causes black borders

### ISSUE THREAD

**Issue by Altarberg** [surge-synthesizer/surge#3844] opened 2021-02-07 14:24 UTC
Bug Description:

Using Deaper and seting the zoom level in Royal skin at 175% causes black borders to appear (zoom level stays at 150%)

Surge Version

Surge Synthesizer
Plugin Host:	REAPER
System:	Windows 64-bit VST3 on AMD Ryzen 5 5600X 6-Core Processor             
Build Info:	Built on 2021-02-06 at 19:20:15, using pipeline host 'fv-az165-25'
Version:	1.9.nightly.6b723a1

Just set royal skin zoom level to 175%.

Windows 10, Reaper 6.23
 - Version: [e.g. 2.4]

![image](https://user-images.githubusercontent.com/75176229/107149349-e2d9b100-6936-11eb-9ecc-266e70426a87.png)

**Comment by baconpaul** [comment] 2021-02-07 14:42
As I mentioned on discord

I bet this is reaper being conservative, us finding a zoom factor of 174.94 fits the window, then the SurgeGUIEditor checks against fixedZoom (like https://github.com/surge-synthesizer/surge/blob/e8c05c277004b899126abe30aa637f0b34ad7eb5/src/common/gui/SurgeGUIEditor.cpp#L6489 But there’s a few) pushing us down.

If we take those ones and make it <= zoom - 3 or <= zoom * 0.99 or some such I bet this goes away

**Comment by mkruselj** [comment] 2021-02-07 19:07
Likely a duplicate of #3834

**Closed by mkruselj** 2021-02-07 19:07 UTC
Labels: Bug Report, Zoom
