### ISSUE TITLE
How can I alter Timbre cc74 to BC cc2 in the source code?

### ISSUE THREAD

**Issue by DavidsonAudioMulti** [surge-synthesizer/surge#2638] opened 2020-09-19 17:14 UTC
This isn't really a problem more of a change of default CC74 to CC2 for Timbre

I would like to have timbre cc74 be by default cc2
What part of the code can I alter to get swap these values. I would also like to rename the GUI Timbre to Breath any suggestions would be appreciated thank you.

Update: I found that changing the Case 74 to 2 in SurgeSynthesizer.cpp changes the source CC for timbre that's great. I still need to figure out how to rename the button Timbre to Breath?

**Comment by baconpaul** [comment] 2020-09-19 18:26
timbre is treated specially in mpe mode so be careful. and we wouldn't be able to merge your change. but you can go ahead and modify the name Timbre in the places it appears in src/common/ModulationSource.h

If you want to map CC2 you can also assign it to a control and then use that control as modulation source.

Hope that helps

**Comment by DavidsonAudioMulti** [comment] 2020-09-19 19:26
I see that I tried and it turned out kinda glitchy.. Is there a way of editing the modulation button name like turn Modwheel into Breath. I can't find the GUI edit for this. I looked through the skins and couldn't find this. It must be programmed into surge some place. I will keep looking to see if I can change it. I noticed that I can change the default CC's for the Macros in surge configuration file. This I can change CC 41 to CC 2 by default which also does what I want. Still I would like to be able to edit the GUI for the Modwheel button in the routing section cheers!

**Comment by baconpaul** [comment] 2020-09-19 20:01
The Modwheel button is named in the same place as the Timbre button, that point in modulation sources header as mentioned above

You can RMB on a control and set it to CC2 or you can also put it in learn mode. Theres a menu that lets you save a variety of configurations.

The hard coded modulators are indeed that. The macros (or direct midi learn) serve as the non-code driven way to map other controls to surge. Or of course mapping through your DAW to whatever you want using automation.

**Comment by baconpaul** [comment] 2020-09-19 20:02
https://github.com/surge-synthesizer/surge/blob/4d8baf1b4e618487bc217ee210d174694731bfe9/src/common/ModulationSource.h#L107 that's the region you are looking for. change the 3 versions of the name and rebuild your surge and it will work.

**Comment by mkruselj** [comment] 2020-09-19 20:46
I would rather suggest you to use a Macro for this. You can bind almost any CC to the macro directly, and it works like any other modulation source.

**Comment by DavidsonAudioMulti** [comment] 2020-09-19 21:08
mkruselj are these macros or bindings saved individually with the preset? For instance if I make a patch and assign the macro 1 to CC2 then the person that loads a preset would also have to have the same macro set or same configuration file for default macro cc's? My hope is to just have cc2 as a default modulator so the macros don't have to be altered to support the presets.

I found that piggy backing CC2 on to aftertouch works to where is can accept aftertouch or cc2 input. I just made a separate cc2 case 2 for modulation to aftertouch source.  

I am going to try baconpauls suggestion to change the button name. Thank you everyone for your suggestions this helps me a lot cheers!

**Comment by baconpaul** [comment] 2020-09-19 21:17
@DavidsonAudioMulti the problem is the approach you are taking will also not let someone open your patch since we can't merge it! 

The midi mappings are set up by users. What I would do in your case is to rename the macro "Breath" and then let the user map their appropriate midi control. 

If we added another row of modulators, or added a 'compound midi modulator' which has RMB toggles (kinda like velocity is release velocity) it would solve your problem. That's more code than what you have indicated you have changed. But if you are interested in making it so one of the monophonic control points (probably mod wheel is the most sensible) as a bound control, that's writable code.

**Comment by DavidsonAudioMulti** [comment] 2020-09-19 21:36
Baconpaul I see what you are saying make a toggle for modulation wheel but then we would lose mod wheel. I am trying to get better compatibility with wind controller and I would like to have the CC's 1,2,5 as built in modulation sources. Maybe I could do a BC toggle for aftertouch where aftertouch can be swapped for cc2. It would be great to be able to have just cc 1 and 2 as built in modulation sources this would make wind controller patches that rely on cc2 easier to make. I am gonna try to change the name of the button see if I can. Thanks again!!

**Comment by mkruselj** [comment] 2020-09-19 22:18
Macros are indeed saved within the patch, individually for each one you save. However, the MIDI assignment to the macro is saved globally. So you would have to instruct people using your patches to MIDI learn the Breath macro that you do to CC #2.

**Comment by mkruselj** [comment] 2020-09-19 22:19
And yeah @baconpaul at some point we will need another row of modulators, haha. 😁

**Comment by baconpaul** [comment] 2020-09-19 22:23
@DavidsonAudioMulti inwas suggesting we do the same thing as we did with release velocity where two modulators can sit in one slot

https://youtu.be/GnEX-ypuem0

Like they

**Comment by mkruselj** [comment] 2020-09-19 22:24
Yeah that'd be a stopgap solution, but man would it be great if we didn't have to hide modulators like that 😄

**Comment by baconpaul** [comment] 2020-09-19 22:31
I agree 
Just trying to offer solutions which we could merge in 172

**Comment by baconpaul** [comment] 2020-09-19 22:32
If we did add a row what would it contain?
Obviously release vel but do we have enough midi controls to justify a full row?

**Comment by DavidsonAudioMulti** [comment] 2020-09-20 02:37
I was able to change the name for after touch and make it respond to both CC2 and Aftertouch works pretty good. It would be better to have a toggle switch to select between the 2 controllers. This really only makes it easier to make patches that respond to cc2 that is not a huge improvement. 
![image](https://user-images.githubusercontent.com/47409222/93691373-8d912600-faa1-11ea-9db4-85cd576c769a.png)

**Comment by mkruselj** [comment] 2020-09-20 10:23
> If we did add a row what would it contain?
> Obviously release vel but do we have enough midi controls to justify a full row?

Release velocity
Breath controller (CC 2)
Expression (CC 11)
Separate monophonic keytracks (lowest highest latest oldest)
Random unipolar
Random bipolar
...

**Comment by DavidsonAudioMulti** [comment] 2020-09-20 16:19
mkruselj That is a great suggestion this would be a big improvement!! How difficult would this be to implement I am not real familiar with Surge project most likely not something I could pull off. I found that adding cc2 to the aftertouch input is getting good results. One thing I notice is that surge is slightly slow to respond to CC inputs and Note on offs. This is a very small delay but I can notice it when compared to other synths. Is there a way to increase responsiveness to CC and note on off's?

**Comment by baconpaul** [comment] 2020-09-20 17:13
Which DAW are you using and which plugin flavor?

What @mkruselj suggested would be easy from an internals perspective; and a huge pain from a UI perspective (we would have to re-render all our graphics and respace the UI).

**Comment by mkruselj** [comment] 2020-09-20 17:53
We'd really only need to update bmp00102 across two (well three, if we count Nick's) skins to account for one extra row, the rest is dealing with spacing of modbuttons in code. Not terrible from my perspective.

**Comment by mkruselj** [comment] 2020-09-20 17:56
Also I don't notice any additional delays to note on/offs compared to other synths, however CCs that are received are being smoothed out to an extent, AFAIK.

**Comment by DavidsonAudioMulti** [comment] 2020-09-20 21:39
I am using Reaper and VST3 I think the delay that I am experiencing is very slight and may have nothing to do with the note on off's. Since I am using a wind controller the CC and note on off are kinda linked so if the CC has a certain smoothing or lag applied it triggering seems slightly sluggish. Mkruselj the smoothing that occurs on the CC can that be configured to be disabled or have an adjustment for it? Do you know where this code is located? Thanks!!!

**Comment by mkruselj** [comment] 2020-09-20 21:49
There's no parameter to adjust that smoothing in the synth itself, and @baconpaul knows where that is in code. Might not be a bad idea to have some options in the Menu regarding that smoothing?

**Comment by DavidsonAudioMulti** [comment] 2020-09-20 21:58
That would be great for instruments like the wind controller that rely heavily on CC response. These controllers are typically very smooth and need little to no smoothing for a tight feel. +1 mkruselj for this suggestion on putting it in the options menu.

**Comment by baconpaul** [comment] 2020-09-20 22:18
The problem is less the smoothing (although that is a problem) but that the smoothing algo is both too slow and never reaches the target! 

I should just go and fix that. 

https://github.com/surge-synthesizer/surge/issues/1412

is the issue. Let me bump it into the 172 milestone.

**Comment by DavidsonAudioMulti** [comment] 2020-09-21 00:14
That would be great baconpaul!! I don't think I would notice with the mod wheel or foot pedal CC but the breath controller you can feel a slight sluggishness. Making the CC mod's more responsive would help when using a breath controller or wind controller. Thank you for looking into this let me know how it goes cheers.

**Comment by DavidsonAudioMulti** [comment] 2020-09-21 02:50
I looked at the section for the release velocity option from right click. I was thinking I might be able to make AfterTouch respond the same way when right clicked with an option for CC2 Breath as an alternate in the right click menu. I will try to add this feature in I am not 100% if I have found all the code to replicate this feature over. Any tips on how I could add this menu option for AF to BC thanks.

**Comment by mkruselj** [comment] 2020-09-21 07:27
You don't have to add that, we have a better solution - redesigning the modulation section, adding one more row for more modulators.

**Comment by DavidsonAudioMulti** [comment] 2020-09-21 13:43
Great that would be awesome mkruselj!! I hope you guys can make the CC's a little more responsive also this would be an excellent addition. I will keep an eye out for an update can't wait to try this thanks you!

**Comment by mkruselj** [comment] 2020-09-23 23:02
@DavidsonAudioMulti So just to let you know, spent a day or so redoing the layout of modulation area and adding new modulators, now there's dedicated slots for breath, expression and (continuous!) sustain pedal even, to act as modulation sources.

Feel free to check out the latest [nightly](https://surge-synthesizer.github.io/nightly), but be aware this is a pre-beta sort of software, not intended for full production purpose until things are officially released. Do let us know your thoughts!

The CC smoothing options will be there at a later point.

**Comment by DavidsonAudioMulti** [comment] 2020-09-24 06:14
Great I am checking it out thanks that was super fast way to go!!

**Comment by DavidsonAudioMulti** [comment] 2020-09-24 06:22
This build is working nicely with the wind controller exactly what I was looking for CC2 Breath as a built in modulation source. This will make patch creation more universal without have to change any macros. I am interested to try the CC smoothing when it is ready.

**Comment by baconpaul** [comment] 2020-09-29 00:20
I just pushed the midi smoothing options - should be in a nightly soon enough (although azure is having some issues this evening) so I'll close this issue since the two material things - breath as a modulator and better smoothing - were both great ideas (thanks for opening the issue!!) and are now done in the nightly ready for 1.8.0.

Thanks!

**Closed by baconpaul** 2020-09-29 00:20 UTC
Labels: Feature Request

**Comment by DavidsonAudioMulti** [comment] 2020-10-07 17:11
Great I will try thank you!!
