### ISSUE TITLE
"Impulse" wavetable crashes host

### ISSUE THREAD

**Issue by unlessgames** [surge-synthesizer/surge#6854] opened 2023-02-22 00:54 UTC
**Bug Description:**
Selecting the `Generate/Impulse` wavetable crashes the host. 

**Surge XT Version**
Surge XT 1.1.2

* Plugin Type: VST3
* Bitness: 64-bit
* Sample Rate: 44.1 kHz / 32 Sample Surge Block

**Reproduction Steps:**
1. Select wavetable oscillator
2. Pick the table "Generated/Impulse" from the drop-down or step to it with the arrows.
3. Host crashes.

**Computer Information:**
 - OS: archlinux
 - Host: Renoise.3.4.2, carla-rack.2.5.3

**Comment by baconpaul** [comment] 2023-02-22 01:02
Did you get a stack? Did you build yourself or use the binary - Arch turns on asserts which 112 can fail. And if you built yourself did you try the nightly?

wondering if this is same as #6702

**Comment by baconpaul** [comment] 2023-03-03 13:51
I have confirmed this is the same problem as #6702 caused by us having a limit range and arch turning on non-production asserts in production.

@unlessgames if you update to a nightly build it will work and the fix will be included in our upcoming 1.2 release.

**Closed by baconpaul** 2023-03-03 13:51 UTC
Labels: Linux, Bug Report
