### ISSUE TITLE
Linux Standalone the `Options -> Audio/MIDI settings` dialog issue - JUCE related

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#4792] opened 2021-07-31 02:18 UTC
with the dev branch of JUCE (HEAD detached at 802f33b0e)

for the Standalone the `Options -> Audio/MIDI settings` dialog hangs to the left of the monitor and cannot be expanded. Can be moved and minimized.

![image](https://user-images.githubusercontent.com/41337033/127725727-1af3ee93-6039-416f-87a0-2b0162614082.png)

reverting back to JUCE 6.0.7 does not occur

![image](https://user-images.githubusercontent.com/41337033/127725767-82e26afe-9268-4e8c-a8ba-174235e93044.png)

**Comment by mynameismuhl** [comment] 2021-07-31 11:53
Hi @tank-trax. It all looks good here (mint20.1).
Maybe there is some mixup because of "HEAD detached at ..."?
The submodule in the repository switched to dev branch a few days ago, 
if you do "submodule update..." and a clean build 
you should be using JUCE 60008 as default.

**Comment by tank-trax** [comment] 2021-07-31 14:22
@mynameismuhl I had the issue using JUCE 6.0.8 though

reverted back to 6.0.7 no issue, did submodule update and it came back

**Comment by mynameismuhl** [comment] 2021-07-31 15:05
Ah ok sorry then.
I just double checked in ubuntu (20.04) and there I see the same you do
(there the window sizes correctly aprox every 4th time its opened). 
But it works correctly in Mint (Mate). So its not linux per sé but desktop environment(?)

**Comment by baconpaul** [comment] 2021-07-31 15:07
Yeah I moved the head pointer of xt to develop to get ready for 6.1

**Comment by baconpaul** [comment] 2021-07-31 18:20
Looks like juce has already fixed this so #4793 will pull to tip of juce for us. Once that's merged a submodule update and clean build should resolve

Note JUCE will report 6.0.8 for develop. This is a point of consternation amongst the juce community but there's no solution yet. Even though you see 6.0.8 on the command line and about, it is develop. (I won't ship a production XT against anything other than a production JUCE tag, but develop fixes several bugs we need and we're still in alpha; this is only a problem in the interim period while we track tip of juce and wait for 6.1 to ship).

**Comment by tank-trax** [comment] 2021-07-31 18:38
FYI am using KDE

**Comment by baconpaul** [comment] 2021-07-31 18:48
I was able to repro on ubuntu and above merge fixes it
if you pull to head, submodule, clean build you should be good I hope

You should see

```
paul@ubuntu:~/dev/music/surge-xt$ (cd libs/JUCE; git log | head -1)
commit 087cda7e1f359855889e28dbf69b3767f21e9f08
```

before you clean and build

**Comment by tank-trax** [comment] 2021-08-01 02:51
I've narrowed it down to it being something to do with the KDE Plasma Breeze Dark Plasma Style

the Global Theme is Breeze Dark

however if Plasma Style is set to Breeze Dark it will hang left and be slim unable to resize, however if the Plasma Style is Breeze it will work (it intermittently repeats the unintended behaviour)

there is a workaround to Force the size by setting Windows Properties in KDE

![image](https://user-images.githubusercontent.com/41337033/127757490-1bda3ddb-40fb-46ac-b093-56466757c1bb.png)

**Comment by tank-trax** [comment] 2021-08-01 02:58
turn out it's the Plastik Window Decoration that is not jiving with the new JUCE

![image](https://user-images.githubusercontent.com/41337033/127757635-afb38cf8-550b-4f50-bd7a-2dfa5a8b0bba.png)

**Comment by tank-trax** [comment] 2021-08-01 03:19
here using Breeze Window Decoration the dialog opens as it should (it very rarely hangs left but still happens albeit very infrequently, with Plastik always)

![image](https://user-images.githubusercontent.com/41337033/127758059-2b6b992f-c200-4071-ad3e-9ce1bcb359f4.png)

**Comment by mynameismuhl** [comment] 2021-08-01 10:27
@baconpaul did it fix it on your Ubuntu?
i have an LTS Ubuntu installed just for testing (unchanged, just updates and dependencies)
and the bug is still existent here.
Plus now i can also see it with Mint (almost never but it happens).

**Comment by baconpaul** [comment] 2021-08-01 11:09
It did

**Comment by baconpaul** [comment] 2021-08-01 14:44
https://forum.juce.com/t/sporadic-regression-6-0-7-develop-in-standalone-settings-window-in-linux-develop/47153

OK I wrote this up on the juce forum. Lets see if they have any thoughts?

**Comment by baconpaul** [comment] 2021-08-04 15:24
Juce team has a fix that should hit develop in the next eeek it seems. Will close this issue when I merge that but confirmed it’s on their side

**Comment by baconpaul** [comment] 2021-08-11 14:13
Oh cool 
I’ll find a time today to repull develop merge and close

**Comment by baconpaul** [comment] 2021-08-11 14:47
Once I merge #4829 if you do a submoulde update and clean build this should be resolved.

**Closed** 2021-08-11 14:58 UTC
Labels: Linux, Bug Report
