### ISSUE TITLE
Generating LV2 presets during compilation

### ISSUE THREAD

**Issue by ToFFmashines** [surge-synthesizer/surge#7609] opened 2024-04-17 08:40 UTC
When installing Surge XT in the environment of the Zynthian project, running on Raspberry pi and Oram-Bookworm-64 bit branch, I came across the need to have LV2 presets generated as well. The standard presets work, but they must be accessed through the Surge XT's native GUI. However, the Zynthian environment requires LV2 presets for its functionality in the form of preset selection in its interface. Due to the considerable amount of presets (1274 factory presets and 4742 3rdparty presets) and essentially manual processing, it is unrealistic to convert all of them into the required format.

Would it be possible to add an option that would turn on the generation of LV2 presets? 
For example in the form:
`cmake -DSURGE_BUILD_LV2=TRUE -DSURGE_BUILD_LV2_PRESETS=TRUE`

On behalf of the developers and users of Zynthian, I hope for your kindness and that you will join the Pianoteq developers who have added a CLI option for this specific problem.

Greeting
Tomas ToFF Kubina

**Comment by baconpaul** [comment] 2024-04-17 11:18
The juce preset mechanism, at build time, will export lv2 presets. For this reason and a few others we have it turned off.

but the change you are after (a flag to build to export) would be eas to code. If you look here

https://github.com/surge-synthesizer/surge/blob/a42226ddf9c5e1045da762eb4e62cbe500f34e56/src/surge-xt/SurgeSynthProcessor.cpp#L190

you can see the code needed is ifdefed out in a surge use juce presets set of blocks.

so your request is basically

1. add a cmake option as you suggest
2. Have that cmake option set a-d internally in the surge xt sub project
3. Chave the undef to ifdef that
4. Test it in the zynthian lv2 environment 
5. Send us a pr

it is step 4 which is hard for us but the changes are small. Any dev with some basic cmake chops should be able to do 1-3 and 5. We would welcome the change if off by default

Hope that helps

**Comment by baconpaul** [comment] 2024-04-17 11:43
Oh or the easiest is turn that undef into a define in a local copy and do a build and test

**Comment by ToFFmashines** [comment] 2024-04-17 14:50
Hi Paul,

thanks for the quick solution suggestions.

I will focus on editing the file SurgeSynthProcessor.cpp, so that I have quick results and can provide a conclusion on whether the generated LV2 presets are suitable.

As I am the man with the white flag on the front line whose loss is insignificant, I ask myself to do it right.
The row will be change to 
`#define SURGE_JUCE_PRESETS `
It's correct?

I got a working Surge XT in Zynthian using this procedure:
```
cmake -Bignore/s13clang -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DSURGE_BUILD_LV2=TRUE -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
cmake --build ignore/s13clang --config Release --parallel 3
sudo cmake --install ignore/s13clang
```
Should I change something? And where should I expect processed LV2 presets?

When I look at how the file generated via jalv host in Zynthian looks like, I see this:

```
@prefix atom: <http://lv2plug.in/ns/ext/atom#> .
@prefix lv2: <http://lv2plug.in/ns/lv2core#> .
@prefix pset: <http://lv2plug.in/ns/ext/presets#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix state: <http://lv2plug.in/ns/ext/state#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<>
	a pset:Preset ;
	lv2:appliesTo <https://surge-synthesizer.github.io/lv2/surge-xt> ;
	rdfs:label "AcidBuzz" ;
	lv2:port [
		lv2:symbol "enabled" ;
		pset:value 1.0
	] , [
		lv2:symbol "freeWheeling" ;
		pset:value 0.0
	] ;
	state:state [
		<https://surge-synthesizer.github.io/lv2/surge-xt:StateString> "56956.yUmXy.Ez........L3.........................O+fWarAhckI2bo8la8HRLt.iHfTlai8FYo41Y8HRUTYTK3HBHyQWXtQVXr8lak0iH4U1bh.xO9vCbgQ2XnAhbkYWZyk1at0iHxLiH9vSakQWXf3VXsUVOhDzXoQFHBUmd5IBHiEFckc1axkWOhXUZtMVYtQGHZEVcnElbuLUYwUWYtMVYyIBHi8VasUlaz0iHTU1bzklamABcnUFHtU1cfXVZrQWYxMWHh.RX0QGZuIWOhXUZtMVYtQGHZEVcnElbh.BaoMVYtMWY8HhH9vCcgc1bf7hO77RakQWX9vCbgIWXsUFckI2b9vicuwVcsU1WFgULfPWdvUVOhHiHfXWXrUWY8HRLt.CLv.CLv.CLv.CLv.CLh.xK9vicuwVcsU1WFgkLfPWdvUVOhHiHfXWXrUWY8HRLt.CLv.CLv.CLv.CLv.CLh.xK9vicuwVcsU1WFg0LfPWdvUVOhHiHfXWXrUWY8HRLt.CLv.CLv.CLv.CLv.CLh
```

The last line is very substantially cut.

We'll see where we get to step by step.

ToFF

**Comment by ToFFmashines** [comment] 2024-04-18 08:32
Hi Paul,

Unfortunately, the assumption was correct. What JUCE 7 produces is unusable for us.

Please close this ticket, with the fact that its solution is not possible until there is proper support in JUCE 7.

How can I contact you? I have two more questions. We would need to have a compiled LV2 plugin with OSC IN support enabled and only with the main stereo output. And I don't want to discuss it here.

Thanks again for your support

ToFF

**Comment by jofemodo** [comment] 2024-04-18 08:45
Hi @baconpaul !

Here jofemodo, from zynthian project too ;-)

I'm testing the procedure and it works OK. The generated presets are not self-contained, but i think it's OK to use this kind of presets for factory presets, that is a stable list. If they change, we could regenerate again. 

Using these presets has the advantage of speed. They are faster to load than native LV2 presets, what is super-cool when testing presets while playing/sequencing.

Anyway, only the "factory presets" are generated OK. The generated LV2 presets for the 3rd party collection is not OK and all of them have the same “RANGE ERROR” name. This should be fixed. Do you know what could be the cause?

Regards,

**Comment by jofemodo** [comment] 2024-04-18 08:55
OK! I read the code and found this fragment in  src/surge-xt/SurgeSynthProcessor.cpp:

```
    if (index < 0 || index >= presetOrderToPatchList.size())
    {
        return "RANGE ERROR";
    }

```

It seems that the "presetOrderToPatchList" array is not being fully generated.

Regards

**Comment by jofemodo** [comment] 2024-04-18 09:25
OK! Fixed with this "patch":

sed -i "s/firstThirdPartyCategory/firstUserCategory/g" src/surge-xt/SurgeSynthProcessor.cpp

Now all factory and 3rd party presets are generated OK.

Regards,

**Comment by baconpaul** [comment] 2024-04-18 11:47
Ahh great. Lemme look at what that actually changes and see if I can make it mergable

I see from your forum discussion you also have some sort of problem with the 6 out version? With the pre juce 7 lv2 version we had to disable those but I thought the juce 7 version worked

I also see you use a pi4. The newer patches in third party use some of the newer features which use more cpu. I would suggest if doing load tests to test with some of the jacky Ligon or Kinsey dulcet ones

**Comment by baconpaul** [comment] 2024-04-18 11:50
You can see that old code here https://github.com/surge-synthesizer/surge/blob/012f6ce775962ea2186a85c8ae45d8c2d16ffe11/src/surge-xt/plugin_type_extensions/SurgeSynthLV2Extensions.cpp#L24

for testing purposes you can probably put that at the end of the processor constructor in an if wrapper is lv2 block and re test 

but the synth is also resilient under the extra outputs just not being connected whcih is the best approach.

**Comment by baconpaul** [comment] 2024-04-18 12:58
OK over in #7610 you can see I did two things which I'll merge as soon as CI is done

1. add a `SURGE_EXPOSE_PRESETS` cmake option which turns preset exposing on in the XT juce plugin. So `cmake .... -DSURGE_BUILD_LV2=TRUE -DSURGE_EXPOSE_PRESETS=TRUE` and the LV2 will get the presets in the manifest
2. Do a (slightly more surgical and appropriate) version of the fix from @jofemodo 's sed to make sure the presets are fully exposed, but that if you save user presets they don't confuse the system.

CI usually takes about 15 minutes and when its merged you can pull and try again.

**Comment by baconpaul** [comment] 2024-04-18 12:59
Oh also connecting the thread the other way: https://discourse.zynthian.org/t/surge-xt/8764

**Comment by ToFFmashines** [comment] 2024-04-19 06:31
Hi Paul,
I tried the whole procedure from the ground up and came across u cmake -B.
The procedure was:
```
git clone https://github.com/surge-synthesizer/surge.git
cd surge
git submodule update --init --recursive
cmake -Bbuild -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DSURGE_BUILD_LV2=TRUE DSURGE_EXPOSE_PRESETS=TRUE -DCMAKE_INSTALL_PREFIX=/usr
```
and i got this warning:
```
CMake Warning:
  Ignoring extra path from command line:

   "DSURGE_EXPOSE_PRESETS=TRUE"
```
I'm not proficient in c/c++ and compiling like boss jofemodo, which on the other hand makes me an ideal dumb tester.

**Comment by Andreya-Autumn** [comment] 2024-04-19 09:25
Easy: you're missing a hyphen in front. See how all the other options begin with `-D...` but the expose presets one begins with just `D`? That's your problem.

**Comment by ToFFmashines** [comment] 2024-04-19 10:47
Sorry, I really missed that.

**Comment by baconpaul** [comment] 2024-04-19 17:13
I'm going to close this issue as resolved. Let me know if you need anything else but it looks like we are good.

**Closed by baconpaul** 2024-04-19 17:13 UTC
Labels: Feature Request
