### ISSUE TITLE
Enable LFO/SLFO Modulation of Oscillator Octave / Scene Octave

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#367] opened 2019-01-21 10:04 UTC
I think it would be great to be able to modulate the parameters of the Oscillator Octaves and Scene Octave with LFO/SLFO

**Comment by baconpaul** [comment] 2019-01-21 16:03
The reason you can't do this is 2-fold

1. There's no natural UI gesture for it, but more importantly
2. The modulation architecture only modulates continuous variables. This is the same reason you can modulate the M in FM3 but not FM2.

You could imagine the LFO modulating by doing a round; or introducing a new LFO class which is an integer-LFO. But that's all quite a lot of work. So I'm going to tag this as a "post 1.6" type thing since it has some far reaching impact on the code if we do something like it.

**Comment by sense-amr** [comment] 2019-01-21 21:10
yeh i was definitely looking at "future release" for that

**Comment by paulhuman** [comment] 2019-01-22 11:07
> 2\. The modulation architecture only modulates continuous variables.

I guess, due to the same limitation, Serum uses the additional non-stepped "crs" parameter for the pitch modulation.

**Comment by sense-amr** [comment] 2019-01-22 12:00
I figure a modulator with only 7 steps .. since that is -3 -2 -1 0 1 2 3 is all thats needed.. and yeah "crs" or course would be the way to go since the parameters are defined for each step .. and there only needs to be 7 in this way even a LFO step with 7 steps should work .. if it was able to be linked to Oscillator octave and Scene Octave

**Comment by baconpaul** [comment] 2019-01-22 13:04
From looking at the surge code, an easier approach I think would be to use a continuous LFO and allow it to bind to a non-continuous variable with an implicit round for some controls. Not all but some. The choice to modulate continuous is an explicit-sh one as I laid out and @kurasu confirmed in #235 (which also has some of the code paths).

So the problem isn't the modulator; it's the wiring thereof. To adjust that code is quite a few shifts if we want to do it consistently and correctly. And of course the UI. How do you indicate that you want a 1 octave wobble rather than a 3 octave wobble. Like what's the equivalent of the blue slide part of a slider. All require a bit of design.

**Comment by baconpaul** [comment] 2019-01-22 13:33
Yes. It can be. You would need to make the changes to the modulation architecture I outline above.

The external modulation path - which goes through the exposed parameters - is far more liberal than the internal modulation path - which assumes float modulators basically right now. That's changeable but would need changing.

**Comment by baconpaul** [comment] 2019-01-22 13:34
assumes float parameters and assumes parameters bound to a slider both, actually. Both assumptions are inside the internal modulation path (the second one a bit more implicit than the first).

**Comment by sense-amr** [comment] 2019-01-22 13:36
I would have to ask if there is  7 discreet parameter options ..  why would it be coded as a float ?

**Comment by sense-amr** [comment] 2019-01-22 13:39
ok ill bite.. like a code retard.. why can't those 2 modules just be coded as int?

**Comment by itsmedavep** [comment] 2019-01-22 13:57
> From looking at the surge code, an easier approach I think would be to use a continuous LFO and allow it to bind to a non-continuous variable with an implicit round for some controls. Not all but some. The choice to modulate continuous is an explicit-sh one as I laid out and @kurasu confirmed in #235 (which also has some of the code paths).
> 
> So the problem isn't the modulator; it's the wiring thereof. To adjust that code is quite a few shifts if we want to do it consistently and correctly. And of course the UI. How do you indicate that you want a 1 octave wobble rather than a 3 octave wobble. Like what's the equivalent of the blue slide part of a slider. All require a bit of design.

The UI bit is fairly known but would need to be designed. Meaning, there are well traveled patterns for exposing a "recommended range" that's inside a much larger range in sliders. Serum does this in several places as an example (with knobs and sliders). I did this the video editing apps I worked on. 

Also further considerations would be, are you snapping to a musical scale to arrive at 1 octave vs 3? Are you just allowing free form placement without quantizing to musical scale? What is the expectation (freeform placement, quantized placement snapping to musical scale, something else?)

FabFilter Pro Q solves that part of the question fairly elegantly. They provide freeform placement of frequency point on the EQ but provide a dot on a keyboard to drag around if you would like to snap to musical scales. 



> ok ill bite.. like a code retard.. why can't those 2 modules just be coded as int?

I think Paul is saying they can be but that it will require a fairly disruptive bit of code change.  As to why it was done that way  in the first place, anyone's guess really. I have a guess but its just that.

**Comment by baconpaul** [comment] 2019-01-22 14:16
@sense-amr for me this thread has three references which immediately come to mind. I don't know where in the world you live and what you studied and stuff but I'm thinking of abott and costello "whose on first" and I'm also thinking of the turing decidability proof and church-turing thesis. You can google both of em. But the first is fun way to see two people talking past each other, which I feel we are. And the second basically says computers can do anything you want (except the things they can't) if you describe a program (except for the things you can't program).

But @itsmedavep has it right. You could code LFOs to modulate ints. It's work. There are edge cases. You have to do the UI. But it's expressible as lambda calculus or as a pen writing on a long bit of tape so you are fine. The spread between "you can" and "you have" is the activity we call "coding" :) This one is "quite a bit of coding".

I think the reason it wasn't done in this way in the first place was probably, quite simply, that @kurasu set up LFOs to modulate continuous parameters and so that's what it does. Modulating non-continuous parameters is a harder UX problem.

Note that when @kurasu went off and write bitwig with his buddies he lifted this constraint. So a continuous externally exposed parameter can get modulated by bitwig. But that's a different path.

Does that all help?

**Comment by baconpaul** [comment] 2019-06-16 01:34
Link to  #235

**Comment by mkruselj** [comment] 2020-10-08 19:39
Closing as a duplicate of #235, basically.

**Closed by mkruselj** 2020-10-08 19:39 UTC
Labels: Feature Request, Modulation
