### ISSUE TITLE
Selecting OSC Types in a certain order transposes the OSC

### ISSUE THREAD

**Issue by cyanit** [surge-synthesizer/surge#702] opened 2019-03-02 19:52 UTC
**Problem**
If you select the Wavetable generator in the UI and then select the "Classic" generator, it'll transpose the OSC down.

**Expectation**
The pitch of the OSC stays constant, no matter what kind of generator is selected in any order

**Reproduction**
In order to reproduce the bug, take a look at them here:
[![Take a look at this bug](https://img.youtube.com/vi/52h1REqogk8/0.jpg)](https://youtu.be/52h1REqogk8 "Take a look at this bug")

**System Infos**
OS: Windows 10
DAW: Bitwig Studio 2.4
Type: VST2, 64bit
Build: NIGHTLY 2019-03-02-96dac41

**Comment by baconpaul** [comment] 2019-03-02 20:02
Thank you very much for this series of excellent bug reports.

**Comment by baconpaul** [comment] 2019-08-22 14:32
Ha OK I just spent some more time looking at this. (Sorry for the very long delay).

The problem isn't quite that the oscillator is transposed (although that is what appears to happen). Here's what happens

When you select classic/ sawtooth it applies a default patch to the classic oscillator. This patch sets width and sub-width to the midpoint.

Now when you change the oscillator type using an external parameter it doesn't go to that preset it goes to the default. The default has width and sub width set to 0

This (effectively) means the oscillator is playing at half frequency (just change those parameters and you will see).

It is compounded by the fact that when you change the OSC type with a control you don't get the visual update.

I'm not quite sure what the right fix is here. The options are

1: Have the default super oscillator configuration match the classic/saw configuration. I think that is the best
2: Leave it as is 
3: Have the osc type pick the same things as the menu

This is all related to your issue #701 also - which is that the osc type parameter is controlling the oscillator type; but the menu is not doing the same thing. For instance, there is no way through that parameter to pick the 'saw' and 'square' classic presets because they both map to oscillator type 1 or whatever.

Now that I've diagnosed this let me think about what I want to do for the 1.6.2 release. Setting that default is probably the reasonable choice. I don't *think* it will break anything but it will definitely change the rack module which is a bit of a bummer. So need to be a teensy bit careful with how I do it.

**Comment by baconpaul** [comment] 2019-08-22 15:05
OK now that we can see what's going on (thanks to the push I just did which actually updates the UI when you automate this) we can see the problem

If you load a surge and automate classic -> sine -> classic everything is fine
If you load a surge and choose menu/sine then automate to classic you get the shift

What is happening is when you do an automated change of the oscillator type, the oscillator isn't getting a chance to set its default values. Probably need something like loadOscAlgos to get called in this control path.

My earlier diagnosis about default values was not correct. The default values of the super oscillator basically match the sawtooth setting. So it is state because we aren't calling init_defaultvalues when osc type changes under automation

There is a special code path for FX which we can crib here to get this issue closed.

Close. I can close this for 1.6.2 for sure.

**Comment by baconpaul** [comment] 2019-08-22 16:17
OK @cyanit I've actually got this fixed! Pushing to nightlies now.

**Closed** 2019-08-22 16:23 UTC
