### ISSUE TITLE
Linux LFO ruler lines in the wrong spot

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#2993] opened 2020-10-28 19:59 UTC
Latest build of Surge, Debian Buster, tested on a few hosts, same thing with the VST2

this happens when Tempo Sync on the LFO is enabled
![image](https://user-images.githubusercontent.com/41337033/97489727-4a469480-1936-11eb-93b7-f12a8dc535cc.png)

**Comment by baconpaul** [comment] 2020-10-28 21:38
Yet another cliprect problem
I think the cliprect has to go.

**Comment by baconpaul** [comment] 2020-10-29 00:19
@tank-trax pretty sure evil just fixed this. Can you look at latest master? Thanks!

**Comment by tank-trax** [comment] 2020-10-29 02:00
unfortunately the commit 893983 on the main branch still has the same displacement

**Comment by baconpaul** [comment] 2020-10-29 02:22
Indeed it does

**Comment by mkruselj** [comment] 2020-10-29 08:07
So it's something else then I guess. :)

**Comment by tank-trax** [comment] 2020-10-29 15:15
@bgins are getting this too?

**Comment by baconpaul** [comment] 2020-10-29 15:54
I get it reliably on linux. No problem reproducing.

**Comment by tank-trax** [comment] 2020-10-29 19:20
Just checking as my system did an update and well... things changed. Wanted to make sure it wasn't isolated to my system. Some hacks are temporal it seems.

**Comment by baconpaul** [comment] 2020-10-30 19:53
OK so the above fix fixes the gross temposync glitches on linux

but it is still the case that the rule lines and the envelope lines are misaligned. It is worse on linux than mac/lin (my guess is because valscale is 100 times bigger).

Here's mac where it is super subtle
<img width="261" alt="Screen Shot 2020-10-30 at 3 52 54 PM" src="https://user-images.githubusercontent.com/13387561/97750890-fc619600-1ac7-11eb-92c4-313ec39c4835.png">

here's linux where it is really obvious
<img width="243" alt="Screen Shot 2020-10-30 at 3 50 35 PM" src="https://user-images.githubusercontent.com/13387561/97750804-e0f68b00-1ac7-11eb-9197-71d678aa1ff4.png">

I bet it is something about the scaling compared with the axis points. So rename this issue rather than close it, but still merge the fix to the super-gross temposync thing

**Comment by baconpaul** [comment] 2020-11-06 15:02
OK this mis-alignment is the same problem we have had with somewhere inside VSTGUI path code casting to an int too early. Same thing that makes us run with the scale 1000. It's linux only. Mac and win is right (just the line draw makes it look over) but as you scale up linux the miss gets bigger.

**Closed** 2020-11-30 04:50 UTC
Labels: Bug Report, Linux, UI
