### ISSUE TITLE
Surge XT CLAP instances from prior projects not loading in Bitwig 5.0

### ISSUE THREAD

**Issue by bboxdave** [surge-synthesizer/surge#6928] opened 2023-04-12 04:46 UTC
Congrats on the recent release!

In Bitwig 5 Beta 2, on Windows 10, on an Intel i7-3770 CPU, I've loaded two different projects previously saved in Bitwig 4.3.10, including tracks created with Surge XT v1.1 (one project) and v1.2.0 (the other project), CLAP version, 64-bit. When I open the projects with Bitwig 5 Beta 2, the instance(s) of Surge won't load properly. Each instance of Surge yields the message, "Could not load plug-in. Could not load initial plug-in state: Couldn't load the plugin state".

Attempting to reload the plug-in doesn't help. The only option is to load a new instance of Surge XT, but this results in losing any Bitwig modulators that were assigned to the existing instance of the synth.

I've also tried reinstalling Surge XT 1.2.0, and that didn't help (although Surge still opens fine in Bitwig 4.3.10).

I've reported this issue to Bitwig tech support as well.

**Comment by baconpaul** [comment] 2023-04-12 10:57
I’ll grab 5 on my Mac today and look to see if I can repro. If yu can attach the engine.log that would also be super. I also flagged this issue to my friends at the bw clap team.

**Comment by baconpaul** [comment] 2023-04-12 12:15
I can confirm that with Surge XT 1.2.0 on macOS 12 a project saved in BWS 4.4.5 loads fine in 5.0 beta 2. So this might be a windows thing or may be a sporadic other-thing.

**Comment by abique** [comment] 2023-04-12 13:16
Hi,
I could not reproduce that issue with Surge-XT 1.2 on Linux.
I've created a project with bitwig 4.4.10 and then opened it with bitwig 5 and it worked well.
Please could you attach a reduced version of your project saved with Bitwig 4.x?
Thanks,
Alex

**Comment by abique** [comment] 2023-04-12 13:16
Also if you have access to Bitwig's engine logs, could you attach them to the issue please?

**Comment by abique** [comment] 2023-04-12 14:46
This issue is fixed in Bitwig 5.0 Beta 3 (will be released later).

**Comment by abique** [comment] 2023-04-12 14:46
BTW, it only affects Windows.

**Closed by abique** 2023-04-12 14:46 UTC
Labels: Host Specific, Bug Report, CLAP

**Comment by baconpaul** [comment] 2023-04-12 14:55
Thanks @abique !!

**Comment by bboxdave** [comment] 2023-04-12 19:19
Wow, that was fast. Saved me some tinkering this evening. Many thanks!
