### ISSUE TITLE
Access to midi modulators via Lua(formula)

### ISSUE THREAD

**Issue by blancoberg** [surge-synthesizer/surge#7667] opened 2024-06-20 15:02 UTC
**Is your feature request related to a problem? Please describe!**
Not really a problem, but It would be very convinient to have access to all midi modulators directly in lua, instead of importing via modulation of the envelope. 

**Describe the solution you'd like:**
Access to midi modulators via lua in the same way you have access to the macro knobs. 
Pitch bend, Mod wheel, breath, mpe timbre, keytrack etc. 

It could also be useful to have a variable for "mpe pitch" ( Only the mpe pitch data for the current note). Although that doesnt exist as a modulator.

**Comment by baconpaul** [comment] 2024-07-11 21:02
OK the next nightly in about an hour will have all of these, some obviously voice gated.

I gotta say, formula modulator + MPE gestures + linnstrument is, I think, an experiment waiting to happen.

I'll leave this issue open until you confirm in case I forgot any but I think I got them all. Please let me know when you've given it a whirl.

**Comment by mkruselj** [comment] 2024-07-11 21:44
And there's a new PR that slightly tweaks names of the new state variables.

#7707

**Comment by baconpaul** [comment] 2024-07-11 22:17
merged

**Comment by blancoberg** [comment] 2024-07-11 23:01
This is great! All of them is there from what I can see. I'v tested most of them and they all seem to work. 

One thing though, When you deactivate keytracking, the pitchbend still works. Is it suppose to work like that? 
In any case, I think the "Bend Range" parameters could be very useful to have access to in Lua as well. 
That way you can read those values and counteract the regular pitch bend and also use it for creating a custom bend that is adjustable via those values.

**Comment by baconpaul** [comment] 2024-07-11 23:27
1. state.mpebendrange is there. I didn't check it but it should be correct. did you not see it there or was it incorrect?
2. that key tracking off still bending with mpe sounds like a bug. Let me either confirm it tomorrow or get back to you. But that may be hard to fix indeed, thinking of how the code works.

**Comment by blancoberg** [comment] 2024-07-12 08:17
the mpe pitch bend works fine and is disabled when keytracking is off. Its the regular pitch bend that is still active.
I was referring to the "Bend Range" under scene parameters.  Those values would be useful to have access to

**Comment by mkruselj** [comment] 2024-07-12 09:24
Pitch bend is always active, it doesn't concern itself to keytracking (by design).

**Comment by baconpaul** [comment] 2024-07-12 10:49
Ahh yes global pitch bend is always on. 

And understand. I think that’s doable sure

**Comment by baconpaul** [comment] 2024-07-12 13:18
OK pbrange_up and _dn will be there in a nightly later this morning, and this issue will close when I merge the change that starts that build.

Thanks for the idea! We will probably turn the nightly into 1.3.3 towards the end of summer

**Closed** 2024-07-12 13:43 UTC
Labels: Feature Request, Modulation, MIDI, Awaiting User Information, Resolved
