### ISSUE TITLE
Filter EG and Amp EG have broken UI in Andromeda themes

### ISSUE THREAD

**Issue by Odebe** [surge-synthesizer/surge#6894] opened 2023-03-25 17:01 UTC
**Bug Description:**
Filter EG and Amp EG have broken UI in Andromeda themes.

**Surge XT Version**
* Version: 1.9.0
* Plugin Type: LV2
* Bitness: 64-bit

**Reproduction Steps:**
1. Download and install Andromeda theme https://github.com/surge-synthesizer/surge-extra-content/releases/download/skin-library/Andromeda.zip
2. Go to 'Menu -> Skins -> Andromeda'
3. Select any theme in Andromeda section
4. See broken EG

**Expected Behavior:**
EG looks like in default theme

**Screenshots:**
Andromeda Wave:
![image](https://user-images.githubusercontent.com/25752432/227730527-3e855c89-304f-4517-9e12-481778c989f9.png)
Default:
![image](https://user-images.githubusercontent.com/25752432/227731198-04cb71a4-0177-4215-bc0b-8282e4682608.png)
**Computer Information:**
 - OS: Manjaro Linux (kernel 5.15.91)
 - Host: Reaper
 - Version: 6.73

**Additional information:**
Changing zoom does not fix this.

**Comment by mkruselj** [comment] 2023-03-25 19:22
All themes in the Skin Library require Surge XT, they won't look good in Surge 1.9. Closing as not a bug.

**Closed by mkruselj** 2023-03-25 19:22 UTC
Labels: Bug Report
