### ISSUE TITLE
gui not working for all version of surge including nightly version

### ISSUE THREAD

**Issue by mexanik619** [surge-synthesizer/surge#4042] opened 2021-03-07 14:58 UTC
![image](https://user-images.githubusercontent.com/80208363/110244176-82648080-7f83-11eb-93f2-fda4a88d7ed0.png)
this is the issue 
kindly fix this or tell me the cause 
i am using cakewalk by bandlab 64bit and surge is not working

**Comment by mkruselj** [comment] 2021-03-07 16:27
I think more info is needed. From the screenshot I can only deduce you're on Windows 7. But which exact version of Cakewalk, also what's your graphics card?

**Comment by mkruselj** [comment] 2021-03-08 10:03
Well, I installed the latest Cakewalk by Bandlab on my main PC (Windows 10), and Surge opens just fine in it. So @mexanik619 we definitely need more info.

**Comment by mexanik619** [comment] 2021-03-08 15:16
> Well, I installed the latest Cakewalk by Bandlab on my main PC (Windows 10), and Surge opens just fine in it. So @mexanik619 we definitely need more info.

Well, I have installed cakewalk 64 bit on my dell laptop 
dell vostro 1440
the specs are given as follows: 
i3 370m 
graphics card is not there 
integrated gma 64 mb vram
4 gb ram with 60 hz screen 
the other plugins are working fine even surge effects bank is also working but surge is not working it everytime shows like this
blank screen and i am so annoyed with this.

**Comment by mexanik619** [comment] 2021-03-08 15:17
> > Well, I installed the latest Cakewalk by Bandlab on my main PC (Windows 10), and Surge opens just fine in it. So @mexanik619 we definitely need more info.
> 
> Well, I have installed cakewalk 64 bit on my dell laptop
> dell vostro 1440
> the specs are given as follows:
> i3 370m
> graphics card is not there
> integrated gma 64 mb vram
> 4 gb ram with 60 hz screen
> the other plugins are working fine even surge effects bank is also working but surge is not working it everytime shows like this
> blank screen and i am so annoyed with this.

i literally installed cakewalk like 4 days before with all plug ins

**Comment by mkruselj** [comment] 2021-03-08 20:10
Ha, not sure what would be the cause there.

Perhaps, try disabling X-Ray feature in Cakewalk and see if that helps.

Also, do you have some other DAW to test (perhaps try Reaper)?

**Comment by baconpaul** [comment] 2021-03-09 00:20
Yeah that was my thought too. Lets see if it is a system-wide issue with surge or a cakewalk issue.

Also does cakewalk have any error logs?

A white screen with no graphics would happen primarily if the Ui threw an exception on load. Some things that could make it do that include not being able to find resources perhaps?

But (you know this @mkruselj but OP doesn’t) I use mac not windows primarily so not sure I’m that helpful. A test in savi or reaper and a view of any logs may give us a hint tho?

**Comment by mexanik619** [comment] 2021-03-09 08:23
Ummmm actually a error keeps loading when vat scan us there 
It say something related to but ridge.exe and vstscan.exe but it doesn't effect other plugins...
And also I don't know about what is it and I m trying get rid of that error also 
Does it affected my surge or what
And also I use surge nightly

**Comment by mkruselj** [comment] 2021-03-09 08:27
Reaper is a 10 MB download and has a free 60 day trial period.

**Comment by mexanik619** [comment] 2021-03-09 08:39
And also can u tell me about X ray I don't know what it is or how to disable it

**Comment by mkruselj** [comment] 2021-03-09 09:01
In Cakewalk: Edit>Preferences>Customization>Display, at the bottom you have Enable X-Ray checkbox.

**Comment by mexanik619** [comment] 2021-03-09 14:41
I have x-ray option also it doesn't work at all...

**Comment by mexanik619** [comment] 2021-03-09 15:43
Bro actually I tried reinstalling cakewalk and also it doesn't help it again shows like this

**Comment by mkruselj** [comment] 2021-03-09 16:03
So can you please try Reaper just to rule some things out? If the same thing happens in Reaper, there's something wrong with your computer then.

**Comment by mexanik619** [comment] 2021-03-10 15:16
It doesn't work on reaper also.....
Reaper just stops working on starting it

**Comment by mexanik619** [comment] 2021-03-10 15:17
But all plugins are working well....pretty normal but surge 
I m switching it over 
Can u tell me some vst that are same as surge with a vocoder
...
And pretty similar to surge

**Comment by mkruselj** [comment] 2021-03-10 21:07
OK so you definitely have an issue on your computer, possibly hardware-related. Not really possible to say what exactly, unfortunately.

Surge is kinda unique, though. :) If you need the vocoder from Surge, you can use the SurgeEffectBank plugin...

**Comment by mkruselj** [comment] 2021-03-10 21:32
Here's some other thoughts.

1. Press Win+R, type **%PROGRAMDATA%\Surge** - Explorer will open. Screenshot that
2. Press Win+R, type **%USERPROFILE%\Documents\Surge** - Explorer will open. Screenshot that.

Just to verify if everything went well with the install or not. Also, if you see a SurgeUserDefaults.xml file in Documents\Surge, delete it. Let's see what happens.

**Comment by baconpaul** [comment] 2021-03-10 21:44
Oh yeah good point a corrupted skin could do this.

In that case the synth might still play notes before you open the ui. Does it?

**Comment by mkruselj** [comment] 2021-03-10 21:48
From my experience a corrupted skin usually crashes Surge outright... but the guy apparently did a fresh install 4-5 days ago, so it's twilight zone, really...

**Comment by mexanik619** [comment] 2021-03-11 04:58
Thanks a lot 
Lemme try this...

**Comment by mexanik619** [comment] 2021-03-11 04:59
I know it's an old laptop but all other plugins like TDR NOVA 
TAL FILTER
helm 
It all works just fine....

**Comment by mexanik619** [comment] 2021-03-11 05:00
Valhallafreqecho also

**Comment by mkruselj** [comment] 2021-03-11 07:00
Please provide screenshots I requested. We're troubleshooting here, so let's stay focused. 

All those plugins that you listed use JUCE, which we don't use currently. We use VSTGUI, but that should really not be a problem I think.

**Comment by mexanik619** [comment] 2021-03-11 08:27
![image](https://user-images.githubusercontent.com/80208363/110757234-2ba3c300-8271-11eb-9c58-b128018b76a9.png)
and the docs file you said it is not there

**Comment by mexanik619** [comment] 2021-03-11 08:29
and there is no Documents\Surge file

**Comment by mexanik619** [comment] 2021-03-11 08:35
As per my knowledge surge didn't created a docs file....

**Comment by mexanik619** [comment] 2021-03-11 10:15
https://user-images.githubusercontent.com/80208363/110757234-2ba3c300-8271-11eb-9c58-b128018b76a9.png
This only shows nothing more

**Comment by mexanik619** [comment] 2021-03-11 10:15
And there is no document file

**Comment by mkruselj** [comment] 2021-03-11 12:40
OK it looks like it did install properly in fact. It's fine if there's no Documents\Surge, that just reinforces that it's a fresh install and no user settings were made.

**Comment by mexanik619** [comment] 2021-03-11 14:06
Umm sorry but I can try at least another OS
But computer 
NAA I cant

**Comment by mkruselj** [comment] 2021-03-12 15:26
That is unfortunate. Well, we have no idea what's up there. If you can try it in Windows 10 at some point, let us know, but until then, we just don't know what is wrong with your computer that makes Surge not show its GUI. Closing this issue, but if something changes for you in Windows 10 (for the better), let us know!

**Closed by mkruselj** 2021-03-12 15:26 UTC
Labels: Bug Report, UI

**Comment by mynameismuhl** [comment] 2021-03-13 21:51
I am reopening this to add a wild guess, that this might be related to 
the skin royale which seems to be somewhat more demanding.

I recently installed 1.8.1 on a comparably old laptop 
(i5-M 520/linux/reaper) and just tested this again. 
If i hide/unhide the royal GUI it takes more than a second to pop up, 
starts all white, then works fine. 
Translate that to WIN/i3 and you might have that neverending whitescreen in first post.

Now the good news: Dark and Classic Skin dont have that problem, 
I can hide/unhide those in almost doubleclick-speed.
Now if you are stuck with a white GUI you cannot change the skin.
But what you can try is: 

Open 'skins' folder and delete the folder 'royal-surge.surge-skin'

then restart your daw. surge should show up in classic view (hopefully).

**Comment by baconpaul** [comment] 2021-03-13 22:02
An excellent point - the Royal skin does require substantial memory for the pngs 

the classic and dark skin also make offscreen buffers. I wonder if op is just running out of video ram? Would windows raise an event if that happened? I’m careful to check that condition - which is why there would be no crash - but I don’t know if I provide user feedback in that case.

anither thought that came to mind though: surge through vstgui used direct2d. I wonder if op has a graphics subsystem which is not direct2d compatible somehow? Juce uses gdi which is consistent with sfx working. Serum also uses vstgui so if serum shows blank that would also be a possible explanation (and one which would be solved later this year when we move surge proper to juce)

But as mentioned I’m a Mac user. These are just guesses.

**Comment by mkruselj** [comment] 2021-03-13 22:13
The main thing is, though, that OP said there is no user config.xml file, so that means the skin wasn't changed from the default Classic skin, so... back  to square one?

**Comment by baconpaul** [comment] 2021-03-13 23:17
Right
I would be curious if they could run the serum demo tho which is also vstgui based 
Or if they could run the surge xt nightly but that’s buggy in so many ways so probably not a good test right now

**Comment by baconpaul** [comment] 2021-03-13 23:19
Also direct 2d has lots of versions - wonder if updating a graphics card driver may work? Isn’t that something you have to do on windows?

it’s odd that it doesn’t render and doesn’t crash. 

I’m still unclear if it makes sound or not too

**Comment by mynameismuhl** [comment] 2021-03-15 01:42
To put this issue back into the grave out of which i dragged it:

I found an older drive with win7 on it and put it in the above mentioned laptop,
which i looked up uses the same grafix chip as the op machine.
And i can say this works fine, gui sound and all.
including system + driver updates from i dont even know how many years ago.
(Going online with win7 in 2021 might be another way to invite performance issues).

i played around with this gui popup delay some more 
and found some other weirdness in ram usage along the way 
for which i will open a new issue.
