### ISSUE TITLE
VST3 Init error in Qtractor

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#2003] opened 2020-06-01 21:14 UTC
**Describe the bug**
When loading Surge VST3 in Qtractor the Init does not play as it should.
VST2 functions as it should.

**Please let us know your surge version**
* Surge Version: commit ac781431
* Plugin type VST3
* Bits 64

**To Reproduce**
Open Surge VST3
Play a note. Distorted and does not play the Init as it should

**Screenshots**
This is the Init when opening

![Screenshot_20200601_170347](https://user-images.githubusercontent.com/41337033/83454857-d9ed2300-a42a-11ea-9147-587709aa5f86.png)

This is what it should look like

![Screenshot_20200601_170448](https://user-images.githubusercontent.com/41337033/83454869-dce81380-a42a-11ea-96c5-41f70e0953d7.png)

**Desktop**
 - OS: Debian Buster
 - Host: Qtractor 14

**Comment by trebmuh** [comment] 2020-06-01 23:42
Pinging @rncbc since we've been talking/working about Qtractor + surge VST3 on those last days.

**Comment by baconpaul** [comment] 2020-06-01 23:57
Oh yeah this came up because he gave us #2000 which fixed surge in qtractor so @tank-trax and I built his branch and started testing away.

**Comment by trebmuh** [comment] 2020-06-02 00:26
...and it's come full circle! :)

**Comment by baconpaul** [comment] 2020-06-02 00:56
Anwyway just confirmed also that the init patch if you click over to latch gives you noise.
will peek perhaps this evening.

**Comment by baconpaul** [comment] 2020-06-02 00:58
and yeah it's just because all the osc are unmuted when qtractor loads the inits.
I wonder if qtractor is dealing with bool vst3 types improperly.

**Comment by tank-trax** [comment] 2020-06-02 01:27
I've saved the original Init patch and it loads fine. All other presets load as they should. Seems like something that happens only on start up or first load of the VST3i.

**Comment by baconpaul** [comment] 2020-06-02 01:34
yeah that's exactly it. I am in there now

It seems at startup it is calling setParamNormalized with the default value for the bools, which is 0, or unmuted, before asking me for my values.

**Comment by baconpaul** [comment] 2020-06-02 01:46
I can't quite get it but something in the qtractor startup path is setting my bools to their default value before it is getting them, and the default value is wrong.

in reaper I see

getParameterInfo
getParameterNormalized

(then it goes)

in qtractor I see

getParameterInfo
setParameterNormalized (with the default)
getParameterNormalized (this obviously gets the default)

since the init state of the synth is *not* everything in default state but is *almost* everything in default state this causes the problem.

So definitely something in the startup path is mis-handling parameter get/set order

I thought I was close but I don't know the qtractor code so didn't find it. The set emerges from qtractorVst3Plugin::updateParam if that helps.

Don't think this is a surge bug. Think this is a qtractor order of application bug.

**Comment by baconpaul** [comment] 2020-06-02 01:47
you can see same on LFO kfreerun vs trigger too btw.

if it helps, id 168 is the osc2 mute which is one of the ones being mishandled.

**Comment by rncbc** [comment] 2020-06-02 08:04
maybe fixed  in https://github.com/rncbc/qtractor/commit/137c118

cheers

**Comment by baconpaul** [comment] 2020-06-02 11:36
Yup that's it! Works now - awesome. Lemme close this.

I think the resize change is still wonky. In surge there's two ways to resize - now the 'zoom/set zoom to' works but if you drag a corner to use the vst3 resize (which initiates the resize on a different path) I get a hang. Is there a way to prefer to track these in qtractor git issues or some such? I saw you flipped the m_resizing but I'm still not sure it is spot on.

**Closed by baconpaul** 2020-06-02 11:36 UTC
Labels: Host related

**Comment by rncbc** [comment] 2020-06-02 13:41
> if you drag a corner to use the vst3 resize (which initiates the resize on a different path) I get a hang. Is there a way to prefer to track these in qtractor git issues or some such? I saw you flipped the m_resizing but I'm still not sure it is spot on.

resizing by dragging the window frame borders seems to work here just fine, by scaling the whole client area.

**Comment by baconpaul** [comment] 2020-06-02 14:19
Ok I’ll look again. Hung for me but maybe I had a bad build!

And hey thanks for using surge to test vst3 and adding vst3 to Linux!

**Comment by rncbc** [comment] 2020-06-02 14:22
thanks2u2

**Comment by tank-trax** [comment] 2020-06-02 19:26
tested in Debian Buster and can confirm issue is resolved. Thanks!!
