### ISSUE TITLE
Rename user preset appears database lock error

### ISSUE THREAD

**Issue by Wandelwolf** [surge-synthesizer/surge#6959] opened 2023-04-19 08:06 UTC
1. Rename a user preset and save
2. The error appears: PatchDB - Loading Favorites SQL Error[5]. Database is locked (This Error appears two times immediataly)
3. After confirm, the preset is finally renamed
4. If i want to perform now the following i got the same error: PatchDB - SQL Error[5]. Database is locked (without the "Loading Favorites"), and this time up to 20+ times immediataly, that i have to confirm now
- save a new preset, delete a preset, favorite a preset
- again after confirming all the errors, the action was performed, and i see the favorite, the preset is deleted or a new is created!
- Refresh patch browser doesn't help
- Restart the surge standalone session or the DAW host helps and all actions can performed without an error as long as no preset rename is performed! Then the error appears again for all the actions above!

* Version: Linux x64 Verison 1.1.2, 1.2.0, and the nightly downloaded on 2023.04.18
* Plugin Type: VST3, Clap, LV2 in Reaper and Standalone

 - OS: openSUSE Tumbleweed 20230413, amd64
 - Host: Reaper 6.73
- Another User has the same issue in Arch Linux too.

**Comment by baconpaul** [comment] 2023-04-21 23:40
I was able to reproduce this on ubuntu with the standalone.

**Comment by baconpaul** [comment] 2023-04-21 23:57
Ahh the problem is that rename == save then delete
the save happens and rebuilds the database
so then the delete happens and also rebuilds the database
so we have dueling rebuilds

annoying. need to ponder.

**Comment by mkruselj** [comment] 2023-04-22 06:10
Can we not save then delete and only then update database?

**Comment by baconpaul** [comment] 2023-04-22 11:20
Yes but I think that’s not it anyway 

also that’s an annoying code change for an annoying reason

**Comment by baconpaul** [comment] 2023-04-22 11:48
OK I've found it. It was slightly different than I thought

basically a threading error. A couple of defensive fixes coming in next 30 minutes.

**Comment by baconpaul** [comment] 2023-04-22 12:41
OK all merged.

**Closed** 2023-04-22 12:40 UTC
Labels: Bug Report, Patch Browser
