### ISSUE TITLE
Scrolling inconsistencies with int sliders and number fields

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1931] opened 2020-05-22 18:52 UTC
**Description**
Scrolling is inconsistent on integer sliders and number fields. For instance, when scrolling on Uni Voices, it skips values, and when scrolling on number fields, it repeats values quite often (every 2-3 scroll steps).

**Surge version**
Latest nightly, VST3 x64

**Expected behavior**
Scrolling on integer value sliders and number fields should act like 1 scroll step = 1 increase or decrease of the integer value.

**Screenshots**
![Slider wheel bugs](https://user-images.githubusercontent.com/50145178/82699597-f45d1a80-9c3a-11ea-9c57-ad5f64ab212a.gif)

On the above GIF, I scroll through the Poly field consistently, but the result is not consistent (skips very often).
Also, this is easier to see, but Uni Voices skips values.

**Config:**
 - OS: Windows 10 x64
 - Host: FL Studio 20.7 x64

Although this should be an easy fix, I tried and looked in CSurgeSlider.cpp and messing around with range calculations in it also changed the behavior for float sliders (which work correctly). 
I also tried to tweak the range calculations in CNumberField.cpp but I messed things up even more.

**Comment by baconpaul** [comment] 2020-05-22 19:17
Just a note: The problem is "scroll step" is a physical property of the mouse, but not a logical property that comes through the vstgui api to us in the onMouseWheel, which only gives a concept of distance.

If Win32 supports the 'scroll jog' gesture we could plumb it through but I can't since I'm trackpad only so have only continuous scroll devices here.

**Comment by VincyZed** [comment] 2020-05-22 19:22
No worries. I will do more testing on my side later and let you know if I find something.

**Comment by baconpaul** [comment] 2020-05-22 19:26
https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousewheel

```
paul:~/dev/music/surge$ grep -r WHEEL_DELTA vstgui.surge/
vstgui.surge//vstgui/lib/platform/win32/win32frame.cpp:			short zDelta = (short) GET_WHEEL_DELTA_WPARAM(wParam);
vstgui.surge//vstgui/lib/platform/win32/win32frame.cpp:			pFrame->platformOnMouseWheel (where, kMouseWheelAxisY, ((float)zDelta / WHEEL_DELTA), buttons);
vstgui.surge//vstgui/lib/platform/win32/win32frame.cpp:			short zDelta = (short) GET_WHEEL_DELTA_WPARAM(wParam);
vstgui.surge//vstgui/lib/platform/win32/win32frame.cpp:			pFrame->platformOnMouseWheel (where, kMouseWheelAxisX, ((float)-zDelta / WHEEL_DELTA), buttons);
```

that means in theory that the onMouseWheel value of "1" means a single mouse click on windows

**Comment by VincyZed** [comment] 2020-05-26 05:05
OK so I have a fix working for the NumberField issue at least. Before PR though, I just wanted to know what this line does to make sure I don't forget anything:

`if( controlmode == cm_midichannel )` (CNumberField.cpp , line 693)

![image](https://user-images.githubusercontent.com/50145178/82861956-5abc9400-9eec-11ea-91bf-bf1f55fa965d.png)

What's the midichannel thing and how does it affect mouseFactor (scrolling speed multiplier)?

**Comment by baconpaul** [comment] 2020-05-26 10:30
The number field shows midi channel in scene split mode by scaling midi note by 16. That slows down the scroll to be reasonable on my Mac is all

**Comment by baconpaul** [comment] 2020-05-28 22:25
Hey @VincyZed I think your #1954 means we can close this? Thanks!

**Comment by VincyZed** [comment] 2020-05-29 02:28
Well it still does weird things with Unison Voices amount, haven't look into that still..

**Comment by baconpaul** [comment] 2020-05-29 12:38
OK I'll leave it open then!

**Closed** 2020-06-11 15:30 UTC
Labels: UX related
