### ISSUE TITLE
Audio input display should draw incoming audio

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2216] opened 2020-06-27 14:44 UTC
![102](https://user-images.githubusercontent.com/56724286/85924878-64dc0480-b895-11ea-9bee-ac07ff5797a9.gif)

A change in SurgeGUIeditor.cpp and Oscillator.h allowed for osc_audioinput to start draw the incoming audio in the oscillator display in realtime. But it needs some work so let's toss it into 1.7.1

if( oscdisplay && synth->storage.getPatch().scene[current_scene].osc[current_osc].type.val.i == ot_audioinput ) {
   oscdisplay->invalid();
}

Korridor  4:21 PM
Paul that worked really well! It's not perfect but worked!

baconpaul  4:21 PM
yeah
figured it would
hows your CPU when it is running though?

Korridor  4:22 PM
nothing changed in the cpu

baconpaul  4:22 PM
I would want to do some profiling and optimization if we merged that
this is exactly the kind of thing we dont want to put into 170 last minute
but that we do want to properly profile and test for 171

baconpaul  4:23 PM
this is the sort of thing that would splat some linux daw or break on macos 10.12 or something
so lets be conservative
but I am hopeful that a scope is entirely possible

**Comment by mkruselj** [comment] 2021-09-13 18:27
Closing as duplicate of #1970.

**Closed by mkruselj** 2021-09-13 18:27 UTC
Labels: Feature Request, Oscillator, UX
