### ISSUE TITLE
Surge stops responding to qwerty keyboard midi signals when clicked on

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1811] opened 2020-05-06 23:48 UTC
**Describe the bug**
When I usually listen to surge at first and build a sound or play a melody I usually do this with my qwerty keyboard. This is no problem with the latest nightly and no other version.

The problem occurs when i start to click with my mouse in surge just one click anywear. Then the qwerty keyboard will not midi trig surge anymore unless i click anywear back in the DAW.

This is not a problem with the stable 1.6.6 release where i can click on the plugin and do stuff and still midi trig with with the qwerty keyboard.

**Please let us know your surge version**
1.5.2 works like normal
1.6.6 (official) works like normal
Nightly (latest version in VST3 64 bit) has this bug from now.

**To Reproduce**
This was tested in FL Studio 10 and 20.6

**Expected behavior**
To be able to use the qwerty keyboard and click on surge without loosing the ability to still trig it with the qwerty keyboard, function comes back if i click anywear in the DAW.

**Desktop (please complete the following information):**
 - OS: [e.g. windows 8.1]

**Additional comment**
it needs to be fixed, its immensly slowing down creativity when working with surge in this way.

**Comment by baconpaul** [comment] 2020-05-06 23:53
OK this one will be tricky to debug. Let me tag it and I'll add it to the list. 

Looking at diffs from 1.6.6 nothing is immediately obvious so I'll need to ponder.

**Comment by baconpaul** [comment] 2020-05-06 23:58
oh i bet i know exactly what it is. i bet it is the cursor change stuff.

I may DM you a VST3 tomorrow to test with that all turned off. will you be on slack?

**Comment by K0rrid0r** [comment] 2020-05-07 00:01
Yes i will be on slack! please send it tomorrow! :)

**Comment by baconpaul** [comment] 2020-05-07 00:05
OK might have it in an hour or so but I know you are on german time or something. I'll attach a dropbox link here.

**Comment by baconpaul** [comment] 2020-05-07 00:13
https://www.dropbox.com/sh/u02yzscrq19whfp/AADgaXCZAROCAC3GNelKFWyFa?dl=0

there's a dll I built with cursor changes off. May not fix it but if it does then that's good since we planned to turn those off anyway.

lemme know.

i'll delete it once you've confirmed too so we can go back to nightly and so on.

Thanks!

**Comment by baconpaul** [comment] 2020-05-07 00:33
the cursor changes didn't fix it :(

**Comment by K0rrid0r** [comment] 2020-05-07 02:09
Problem now also confrimed on FL Studio 20.6 (x64)

**Comment by baconpaul** [comment] 2020-05-07 02:27
OK! Well at least I can install FL20 to test it in my VM myself which is good. I’ll look in the next few days. @mkruselj if you can look too that’d be great

**Comment by K0rrid0r** [comment] 2020-05-07 07:19
https://www.youtube.com/watch?v=FTruoe5Hqqg

This guy is working in the exact same way as I do with the QWERTY and he has a solution to the problem shown with Xfer Serum in FL Studio 20.6. but, this solution does still not work for surge.

Also Surge 1.5.2 has stopped working like normal and dont respent to QWERTY when clicked on and cant use this solution either (that was sad)

I have also opened FL 20.6 in 64 bit mode and launched the VST3 and it does not work either, even if it says it would solve it in the manual.

@mkruselj
Has reproduced this issue with FL Studio 20 and Ableton also.

I start to suspect that the problem still lies in the surge code actually.

**Comment by mkruselj** [comment] 2020-05-07 07:28
Actually I haven't reproduced it, I just said that FL20 and Live are wrapping/bridging plugins, instead of hosting them under the DAW process, which might be the cause of the issue...

**Comment by K0rrid0r** [comment] 2020-05-07 11:32
Here the final list of testing with FL Studio 10 (32) and FL Studio 20.6 (32) and (64):


FL Studio 10 (32 bit)

Surge x86 1.5.2 VST2 OK! <----------------------------------------

Surge x86 1.6.6 VST2 OK! <----------------------------------------
Surge x86 1.6.6 VST3 qwerty dont work at all, only latch will put it on
Surge x64 1.6.6 VST2 dont load at all, expected
Surge x64 1.6.6 VST3 issue with qwerty

Surge x86 Nightly.bd17bdb VST2 OK! <----------------------------------------
Surge x86 Nightly.bd17bdb VST3 qwerty dont work at all, only latch will put it on
Surge x64 Nightly.bd17bdb VST2 dont load at all, expected
Surge x64 Nightly.bd17bdb VST3 issue with qwerty

Surge x86 Nightly.8c375c9 VST2 OK! <----------------------------------------
Surge x86 Nightly.8c375c9 VST3 qwerty dont work at all, only latch will put it on
Surge x64 Nightly.8c375c9 VST2 dont load at all, expected
Surge x64 Nightly.8c375c9 VST3 issue with qwerty

FL Studio 20.6 (32 bit)

Surge x86 1.5.2 VST2 OK! <---------------------------------------- 

Surge x86 1.6.6 VST2 OK! <---------------------------------------- 
Surge x86 1.6.6 VST3 OK! <---------------------------------------- 
Surge x64 1.6.6 VST2 dont load at all, expected
Surge x64 1.6.6 VST3 issue with qwerty

Surge x86 Nightly.bd17bdb VST2 OK! <---------------------------------------- 
Surge x86 Nightly.bd17bdb VST3 OK! <---------------------------------------- 
Surge x64 Nightly.bd17bdb VST2 dont load at all, expected
Surge x64 Nightly.bd17bdb VST3 issue with qwerty

Surge x86 Nightly.8c375c9 VST2 OK! <---------------------------------------- 
Surge x86 Nightly.8c375c9 VST3 OK! <---------------------------------------- 
Surge x64 Nightly.8c375c9 VST2 dont load at all, expected
Surge x64 Nightly.8c375c9 VST3 issue with qwerty

FL Studio 20.6 (64 bit)

Surge x86 1.5.2 VST2 OK! <----------------------------------------

Surge x86 1.6.6 VST2 dont load at all, unexpected! 
Surge x86 1.6.6 VST3 issue with qwerty 
Surge x64 1.6.6 VST2 OK! <---------------------------------------- 
Surge x64 1.6.6 VST3 OK! <----------------------------------------

Surge x86 Nightly.bd17bdb VST2 dont load at all, unexpected!  
Surge x86 Nightly.bd17bdb VST3 issue with qwerty 
Surge x64 Nightly.bd17bdb VST2 OK! <---------------------------------------- 
Surge x64 Nightly.bd17bdb VST3 OK! <---------------------------------------- 

Surge x86 Nightly.8c375c9 VST2 dont load at all, unexpected!  
Surge x86 Nightly.8c375c9 VST3 issue with qwerty 
Surge x64 Nightly.8c375c9 VST2 OK! <---------------------------------------- 
Surge x64 Nightly.8c375c9 VST3 OK! <----------------------------------------

**Comment by mkruselj** [comment] 2020-05-08 11:51
This is likely a wontfix due to VST3 bridged in FL10 has issues on FL side of things.

**Comment by baconpaul** [comment] 2020-05-08 11:56
Right.
It seems the upshot is

FL20: Same Bittiness, VST2/3 works; Different Bittiness bridge gets in the way, per the FL doc
FL10: Same Bittiness VST2 works VST3 doesn't

So it does sound like an FL10 VST3 bug. I'm going to close this issue and ponder #1777 in light of this.

**Closed by baconpaul** 2020-05-08 11:56 UTC
Labels: UX related, VST3, Windows
