### ISSUE TITLE
Non-UTF-8 character in file name (patches_factory/Monosynth/µcomputer.fxp)

### ISSUE THREAD

**Issue by dvzrv** [surge-synthesizer/surge#1699] opened 2020-04-10 15:24 UTC
**Describe the bug**
When building the package for 1.6.6 on Arch Linux I encountered an issue with one of the factory patches in `resources/data`.

**Please let us know your surge version**

* Surge Version: 1.6.6
* Plugin type n/a
* Bits n/a

**To Reproduce**
1. Build package from source
2. Copy all files below `resources/data/` to data location in fakeroot
3. During `package()` step see warning

`Can't translate pathname 'usr/share/surge/patches_factory/Monosynth/µcomputer.fxp' to UTF-8`

**Expected behavior**
All file names are translatable to UTF-8.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Host n/a
 - Version n/a

**Additional context**
While I see, that the file is contained in the resulting package, I'm certain that it will cause trouble on various file systems down the line.

**Comment by baconpaul** [comment] 2020-04-10 15:26
Curious: why do we need UTF-8 file names? The synth and all the menus work fine with extended char sets.

**Comment by baconpaul** [comment] 2020-04-10 15:27
(you are free in your packager to just rename this file of course if you want! But support for full char set in filenames and menus is a feature, not a bug, of the synth)

**Comment by dvzrv** [comment] 2020-04-10 15:28
This seems to be an issue during the compression step of the package.
Maybe zstd can't work with the file name.

All in all the file ends up on the file system, so I'm not entirely sure whether this will end up being a problem or not.

Maybe I'll just rename it then!

**Comment by baconpaul** [comment] 2020-04-10 15:32
<img width="663" alt="Screen Shot 2020-04-10 at 11 30 28 AM" src="https://user-images.githubusercontent.com/13387561/79002562-ba1e3a80-7b1e-11ea-9925-248f8b2fd9d6.png">

Yeah it hasn't been a problem for us on ubuntu macOS or win10; and we have gone out of our way to support proper unicode support in the tool. For instance, here's a patch I just saved with an emoji in the name. Actually we ended up fixing a lot of bugs that this one particular item tickled around beta 6 or beta 7. 

<img width="663" alt="Screen Shot 2020-04-10 at 11 30 28 AM" src="https://user-images.githubusercontent.com/13387561/79002606-ceface00-7b1e-11ea-959c-f5bfa120e535.png">

So I'm going to close this one; but indeed if you are using a toolchain which isn't wide char aware you will need to adapt in the packaging. "muComputer" is a fine replacement of course, and we scan the filesystem at startup so a simple rename will work just fine.

**Closed** 2020-04-10 15:33 UTC

**Comment by dvzrv** [comment] 2020-04-10 15:57
Ha, figured out why: We're running bsdtar with the C locale (to not enforce a specific UTF-8 locale system-wide).
This leads to that warning message.

Allegedly this isn't a problem, but also glibc still doesn't support C.UTF-8, so there's that.

**Comment by baconpaul** [comment] 2020-04-10 16:06
Well OK! If you want to be super conservative just rename the file! But glad we sorted it all out
