### ISSUE TITLE
Patch change during play

### ISSUE THREAD

**Issue by Gypsy2GS** [surge-synthesizer/surge#5905] opened 2022-02-23 21:29 UTC
Using win11, Cakewalk, Surge 1.9.0.91069f8 64bit
I want to change a patch on the fly, during playback)  I can do this via Cakewalk Event List. The problem is that I cannot see any way to  identify patch numbers in Surge.  Is there any way of identifying Surge patch numbers?

**Comment by baconpaul** [comment] 2022-02-23 21:40
unfortunately we don't currently support daw-initiated patch changes.

**Comment by mkruselj** [comment] 2022-02-23 22:10
Duplicate of #576.

**Closed by mkruselj** 2022-02-23 22:10 UTC
