### ISSUE TITLE
CPU spikes when using Vintage Ladder Type 1 filter and modulating Osc mixer level to -inf

### ISSUE THREAD

**Issue by Trace98J** [surge-synthesizer/surge#7633] opened 2024-04-30 20:58 UTC
**Bug Description:**
CPU spikes when using Vintage Ladder Type 1 and modulating the osc mixer volume.
The spike happens when the volume is modulated to -inf and holding down the note.
Modulation can even be manually moving the slider with the mouse.

**Surge XT Version**
* Version: 1.3.NIGHTLY.2bfa3c0
* Plugin Type: VST3, CLAP
* Bitness: 64-bit

**Reproduction Steps:**
1) Init surge instance;
2) Enable either Filter 1 or 2 with Vintage Ladder Type 1;
3) Put Osc 1 level to -inf;
4) Change the first LFO to Envelope, and modulate the Osc 1 Level by any amount;
5) Set the LFO EG sustain to 0%;
6) Hold down a Midi note;
7) Bug!

**Computer Information**
 - OS: Windows 10
 - Host: Reaper
 - Version: v7.15
 
**About Surge XT**
Version: Surge XT 1.3.nightly.2bfa3c0
Build Info: 2024-04-30 @ 01:17:41 on 'fv-az520-346/pipeline' with 'MSVC-19.38.33135.0' using JUCE 7.0.5
System Info: Windows 64-bit VST3 on Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz, 16 GB RAM
Host: Reaper @ 48000 Hz
Processing Block: 32 samples

**Additional Information:**
Happens with every filter configuration.
Moving the filter cutoff changes the behaviour depending on the sound source, in some instances using the filter doesn't cause the spikes.

**Comment by baconpaul** [comment] 2024-04-30 21:03
I wonder if something is going either nan or into software floats.

**Comment by Trace98J** [comment] 2024-04-30 21:39
> Hmmm not sure I'm not seeing anything out of the ordinary here. The voice is still gated so it will consume CPU until note is released and AEG is done.

Yes but by spike I mean going to 100% CPU usage (reported by surge in top right corner).
Also holding down the note at whatever level, even at -inf doesn't cause it (CPU at 5/6%); it only happens when modulating from whatever value TO -inf (CPU ato 100%).

**Comment by mkruselj** [comment] 2024-04-30 21:51
Yeah, I can't confirm this on my machine. Keeps CPU meter at 5% constantly while doing this.

**Comment by baconpaul** [comment] 2024-04-30 21:57
Can you save and share the exact patch that does it? A zip of the fxp attached here perhaps?

**Comment by Trace98J** [comment] 2024-04-30 22:24
Sure, here it is.
[CPU Spike.zip](https://github.com/surge-synthesizer/surge/files/15171883/CPU.Spike.zip)

This is "similar" to issue #6905 . Even there it wouldn't repro on @mkruselj machine.

**Comment by baconpaul** [comment] 2024-04-30 22:44
You have a modern cpu also? Not like running on a 14 year old intel or anything? Just to eliminate possibilities

**Comment by Trace98J** [comment] 2024-04-30 22:46
No, I'm on a I5-8600, I can try on a Windows Sandobx to see if it repros there on a clean install.

**Comment by mkruselj** [comment] 2024-04-30 22:54
i7-6700K. It's a bit long in tooth but still runs things well :)

**Comment by baconpaul** [comment] 2024-05-01 13:27
On a quick check I also don't get a CPU spike here on my mac.

My best guess is somehow you are getting software denormals (which is when float values < 1e-30 or so stop using hardware for acceleration and go to a way more inefficient approach). We do the assembly trick in our process loop to turn those off, but maybe it is escaping for you somehow? A very good way to test this is to add an epsilon of noise to the patch. So take your patch, unmute the noise channel, and set the level instead of -inf to like -85db or some such. Does it still spike for you?

If it does, it means my theory is correct, but the reason for it is mysterious. At that point I'd need to think about how to help diagnose it. And also if it does, are you running any other plugins in your system? I wonder if one of them is untoggling the state for the system somehow.

If it doesn't, it means my theory is incorrect. Which means the reason is even more mysterious. At that point I'd also need to think about how to help diagnose it, but would have even fewer ideas :)

**Comment by Trace98J** [comment] 2024-05-01 13:59
> So take your patch, unmute the noise channel, and set the level instead of -inf to like -85db or some such. Does it still spike for you?

Having the noise channel on at levels above -inf prevents the 100% PCU spike BUT:
-at -180dB the cpu rises to 9/10% (instead of normal 5%)
-at -185dB the cpu rises to 11/12%
-at -190db the cpu rises to 16/17%
-at -192db the cpu rises to 20/21% 

noting that these values are inputted via right click and "edit value" dialog; if i manage with small mouse movement to set the level to -192 the cpu goes up to 56% .

then at -inf it just goes bananas to 100%...

Thank you for looking into it. 

About the other plugins running in my system; I tried to replicate this bug on a Windows Sandbox and fresh Surge + Reaper install, and it still shows up.

**Comment by baconpaul** [comment] 2024-05-01 14:16
Right

So what this means is, for some reason, your system is not obeying the software denormals flag we set. Which is good. We now know the problem and know the cause

But it is also bad. because i have no idea why that happens

The about screen will have a detailed description of your system and processor. Do you mind pasting that into this issue? I may ask some other audio devs if they have ever seen this.

(Another fix would to be to add some denormal noise to the input of the vintage ladder filter, which we can do, but i would want to understand why your system doesn't obey the flags properly. I may also give you a small executable to run, but that means I need to boot windows to make it for you).

Thanks for your patience. What an odd one.

**Comment by Trace98J** [comment] 2024-05-01 14:24
> The about screen will have a detailed description of your system and processor. Do you mind pasting that into this issue?

I've added it into the issue (if I understood correctly what you mean by about screen).

Thank you again for your time!

**Comment by baconpaul** [comment] 2024-05-01 14:24
Oh I see the about info is above. Sorry!

**Comment by baconpaul** [comment] 2024-05-01 14:25
Quick question: Does the problem show up in the standalone also?

**Comment by Trace98J** [comment] 2024-05-01 14:26
> Quick question: Does the problem show up in the standalone also?

In the Windows Sandbox it did, I don't have standalone on my main machine but I will install it right away and update this comment with the info.

**Comment by baconpaul** [comment] 2024-05-01 14:30
Thanks.

**Comment by baconpaul** [comment] 2024-05-01 15:05
Alright I asked some colleagues and this is indeed mysterious. I’ll boot into windows and see if anything obvious occurs in my system and report back.

One last thing. Your base system doesn’t have any wierd daemons or background audio processes running does it? The reason I ask is your system is acting as if it is ignoring the floating point control registers which we set and I’m just wondering if there’s something interfering with those. No hypervisors or wierd audio drivers or anything like that right?

**Comment by baconpaul** [comment] 2024-05-01 15:40
So in good news (for most surge users) but bad news (for you)  i just did a release build at head on windows of surge and didn't see the spike with your patch.

My system is

```
Version: Surge XT 1.3.main.74d4dde6
Build Info: 2024-05-01 @ 15:40:06 on 'DESKTOP-SEV21K1/local' with 'MSVC-19.29.30136.0' using JUCE 7.0.5
System Info: Windows 64-bit Standalone on AMD Ryzen 5 4500U with Radeon Graphics         , 15 GB RAM
Sample Rate: 48000 Hz
Processing Block: 32 samples
```

**Comment by baconpaul** [comment] 2024-05-01 15:43
at this point my next step would be to make you a small executable to probe why your system isn't setting FTZ. Let me think a little.

**Comment by Trace98J** [comment] 2024-05-01 17:26
> No hypervisors or wierd audio drivers or anything like that right?

I'm thinking about it but I only have these:
![immagine](https://github.com/surge-synthesizer/surge/assets/131201422/c9217aec-ab0c-4039-a337-b0932056cac9)
The usb audio device is a webcam; X3mini a midi keyboard.

> at this point my next step would be to make you a small executable to probe why your system isn't setting FTZ. Let me think a little.

Thank you... If it might be of help I haven't formatted in a while and was thinking about doing it in the not-so-far future.

**Comment by baconpaul** [comment] 2024-05-01 21:52
OK I spoke with a few more experienced windows devs. It seems some other folks have seem this problem, and it comes in two forms

1. Some system or other call resets FPU flags after I do, so "reset closer to the process call" or
2. The FPU flags don't work on your system

both of these require test builds. I've made a test build for the first case 

https://github.com/baconpaul/surge/releases/tag/CUSTOM

That's a zip containing a custom build of Surge XT.exe (the standalone). If that version, when loading your test patch, still exhibits the behavior then I will need to make a test build to figure out case 2.

If that version works, then I have some pondering to do about how to do it efficiently, but it tells us a lot

Please do give it a whirl and let us kno

Most likely, since it is a zip of an exe downloaded from the internet, your smartscreen and so on will complain. I built it on my windows box which I beleive to be virus free (since I barely ever boot it and only isntall dev tools). 

If you would prefer to beleive them and build the software yourself I can provide you with the diffs from main in that binary.

**Comment by Trace98J** [comment] 2024-05-01 22:32
> Please do give it a whirl and let us kno

Hello, I tried the build both on a Windwos Sandbox and on my main system; the issue persists unfortunately.

**Comment by baconpaul** [comment] 2024-05-01 22:48
OK that's good.  Sort of. I'll make one more exe for you to run later tonight. You are comfortable running an exe from a terminal yes? I just need to figure out the right test.

**Comment by baconpaul** [comment] 2024-05-01 22:50
(There's a very easy for for this, by the way, which is to pre-fill our buffers with 1e-15 noise, which surge used to do and which we could make an option but before we resort to that I want to make sure it would work for you, and also it would have to be an option since it has negative repercussions in some cases too)

**Comment by baconpaul** [comment] 2024-05-01 22:56
Oh actually I see one more thing potentially

Can you test this https://github.com/baconpaul/surge/releases/download/CUSTOM/Test.Two.Surge.XT.zip for me?

**Comment by Trace98J** [comment] 2024-05-01 23:04
> Oh actually I see one more thing potentially

This one works!!! No spike in this one apparently...

> You are comfortable running an exe from a terminal yes?

I should be!

**Comment by baconpaul** [comment] 2024-05-01 23:06
Well no need. Thats awesome and the mistake is profoundly embarrassing.

I'll ahve a new nightly soon.

**Comment by Trace98J** [comment] 2024-05-01 23:10
Yippiee!

Thank you for the patience with this somewhat obscure issue!

**Comment by baconpaul** [comment] 2024-05-01 23:11
it turns out to be a really fundamental bug you discovered which is masked on most users machines. So thank you for being persistent in reporting it.

**Comment by Trace98J** [comment] 2024-05-01 23:15
Glad to hear! My pleasure

**Comment by baconpaul** [comment] 2024-05-01 23:38
OK I merged a fix now. It usually takes about an hour for a new nightly to appear. When it does please let me know if it fixes it (and also if it fixes the other issue you reported we couldn't reproduce)

Thanks!

**Closed** 2024-05-02 06:05 UTC
Labels: Bug Report
