### ISSUE TITLE
Sometimes notes keep playing after key release

### ISSUE THREAD

**Issue by cdelacruzpinto** [surge-synthesizer/surge#6483] opened 2022-08-06 14:09 UTC
**Bug Description:**
Sometimes, notes keep playing after key release

**Surge XT Version**
1.1.0

* Version:
* Plugin Type: AU
* Bitness: 64
* 
**Reproduction Steps:**
1. Randomly keep notes playing for long time. It does not happen always, but sometimes. Seems not to be patch related.
2. Release the keys
3. The note keeps playing.

**Expected Behavior:**
The note stops playing after the release time passes.

**Computer Information (please complete the following!):**
 - OS:  13.0
 - Host: Verified on Live and Logic
 - Version: 10.7.4 (Logic) 11 (Live)

**Comment by baconpaul** [comment] 2022-08-06 18:21
Are you in MPE mode? Also are you using midi channels in some particular way?

**Comment by baconpaul** [comment] 2022-08-06 18:22
Oh also your step one. Randomly keep notes playing for a long time.

do you mean play lots of notes over a period or do you mean hold one note for a long time while playing other notes?

thanks

**Comment by cdelacruzpinto** [comment] 2022-08-06 19:23
Hello again :-).

- No 'special' / particular MIDI setup. No MPE. Just a Komplete Kontrol M32 usb controller connected to my Mac with freshly open Live 11 and some tracks with instances of Surge. Also no other devices connected to the Mac.

- My step 1... well, I just played some notes while playing with the UI and sometimes some notes got stuck. I'm sorry for not being very specific... is just difficult to reproduce (but I tried now again and happened a few times in Ableton. Seems to have to do with interacting with the UI while playing. I.e: I managed to reproduce a few times more with a patch with a sequence playing and then clicking at the same time in Ableton in a way that hides the plugin UI / closing the UI while playing notes. It's difficult to reproduce, but at least in my specific environment happens.

**Comment by baconpaul** [comment] 2022-08-06 19:56
Ok that’s very useful 

One last question - do you have the virtual keyboard display on or off in the plugin? 

Thank you for the kind words and for the helpful reports

**Comment by cdelacruzpinto** [comment] 2022-08-07 05:35
Was off.

**Comment by mkruselj** [comment] 2022-08-09 09:21
Can you try and reproduce this while recording MIDI, as well?

**Comment by achlubek** [comment] 2022-09-15 17:03
Worth to try this workaround: in SurgeXT go into menu -> MPE settings -> Enable MPE, somehow this fixes the issue, I don't know what side effects it can cause.

**Comment by baconpaul** [comment] 2022-09-15 17:25
That should only fix the issue if the issue is 'you are sending MPE midi and not in MPE mode'. If your device somehow rotates the note off channel then you might see a stuck note from channel 2/3 though, and an MPE device would.

**Comment by achlubek** [comment] 2022-09-15 17:31
> That should only fix the issue if the issue is 'you are sending MPE midi and not in MPE mode'. If your device somehow rotates the note off channel then you might see a stuck note from channel 2/3 though, and an MPE device would.

I have no MPE capable devices, it works anyway. Changing MPE in live settings for devices I tested with (Keystation 61 and Microfreak) doesn't make any difference. But somehow enabling MPE in Surge just fixes the problem? I have no idea what that could mean but I hope this can help finding the problem.

**Comment by baconpaul** [comment] 2022-09-15 17:39
Ahh you are a live user
So live has this habit of making a synth “mpe” and remapping midi streams so if the live device says mpe even a normal keyboard will get translated to mpe

the earky versions of live11 also had the extra bug that they would activate mpe but not send a midi message activating mpe. This caused stuck notes for users in live with surge unless they either turned off mpe translation in live or turned on mpe receipt in surge 

i don’t suppose you are running one of the older love 11 versions are you? We worked with live devs to fix this but the first few live 11s definitely made stuck notes this way

**Comment by achlubek** [comment] 2022-09-15 17:48
I'm on the lastest 11.1.6 Live Suite

**Comment by mkruselj** [comment] 2023-04-05 19:40
@achlubek It would be useful to get some more information from you. Please try the very latest version of Live, this issue shouldn't happer there because Live will send a proper message to Surge to enable MPE mode, hence there should be no hanging notes.

I am going to tentatively close this issue, but if this is still happening for you in the very latest version of Live with the very latest version of Surge XT, let us know!

**Closed by mkruselj** 2023-04-05 19:40 UTC
Labels: MIDI, Awaiting User Information, Bug Report
