### ISSUE TITLE
Wavetable Load causing RefCount Runaway

### ISSUE THREAD

**Issue by Flayzen** [surge-synthesizer/surge#787] opened 2019-03-23 20:37 UTC
Version 1.6.0 beta 7. VST3. FL Studio 20 on Windows 10.

1) GUI Zoom setting not remembered when closing/reopening the interface.
2) Opening any 3rd party wavetable causes immediate crash of DAW:

![surgecrash](https://user-images.githubusercontent.com/47046397/54871414-72116600-4dab-11e9-8ed3-b9ccd054b6fe.png)

**Comment by baconpaul** [comment] 2019-03-23 21:44
The first yeah we know about. A new session uses the default zoom. You can set your default above 100. Fixing that is tricky. 

On the second that’s new. Which wavetable crashed it? When you say 3rd party you mean the layzer ones or some others in documents/surge? And if it is one not shipped with synth that crashes it could you zip it and attach to this isssue?

**Comment by esaruoho** [comment] 2019-03-24 05:44
apparently the .wav -tables (note extension) are here:

https://drive.google.com/open?id=1t2ywS2bi_sMYtWao7gxX9nB7-ylifDeQ

**Comment by baconpaul** [comment] 2019-06-19 13:16
Just renaming this issue; with 1.6.1.1 I have fixed the in-session vst remembering and the cross session is on the plan for 1.6.2

This refcount > 5 reproducibility is really interesting. I upped the limit to 10 but good to know there's a wav file here which can reproduce it on windows. Thank you. I'll slate this one for 1.6.2

**Comment by baconpaul** [comment] 2019-08-06 17:41
@Flayzen I just added a completely reworked support for .wav files. I was able to load a couple fo the files in the dropbox here into surge no problem - and they certainly would not have loaded in the past (they are 2048 sample wav files with no smpl block). So I'm going to close this issue, especially since the DAW-is-not-remebered one is in a separate 1.6.2 issue.

If with the latest nightly (you need a build date of Aug 6 or later) you still get a crash loading these wavetables please reopen this with a link to the crashing wt. 

Thanks

**Closed by baconpaul** 2019-08-06 17:41 UTC
