### ISSUE TITLE
Really loud noise when loading a project with Surge XT

### ISSUE THREAD

**Issue by jxquae** [surge-synthesizer/surge#6555] opened 2022-08-21 03:43 UTC
**Bug Description:**
Whenever I open a project involving Surge XT it plays a REALLY loud noise that makes the entire project inaudible except for that one noise coming from surge. 

**Surge XT Version**
* Version: 1.1.0.012f6ce
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open a project on FL Studio 20 with Surge XT
3. It plays a really loud sound that drowns out everything else

**Expected Behavior:**
I expected it to just load the beat that I made

**Screenshots:**
https://drive.google.com/drive/folders/1Hcs3dH4yfkp3OeHFMAmb_tzDpT6VU9eh?usp=sharing 
This is a link to the video

**Computer Information (please complete the following!):**
 - OS: Windows 11
 - Host: FL Studio
 - Version: 20.9 (probably) 

**Additional Information:**
It can happen on any of the Surge XT instruments that I had open, it doesn't matter what instrument

**Comment by jxquae** [comment] 2022-08-21 03:48
Some additional information I forgot: 
1. the sound NEVER goes away as long as the project is open (I left it open for 30 minutes and it never went away) 
2. I've tried deleting the Surge XT that the loud noise is coming from and it DOES eventually go away after a couple minutes, but then when I try reopening Surge, the loud noise IMMEDIATELY comes back and destroys my ears lol
3. I don't think it has to do with the plugins/effects I've added to them because I deleted them and the sound still played

**Comment by mkruselj** [comment] 2022-08-21 07:05
Please try adjusting FL's plugin wrapper for Surge XT do that it uses fixed size buffers, and always use max size buffer. Does it happen then still?

Also, which patches are being loaded? Any of them have audio input active?

**Comment by baconpaul** [comment] 2022-08-21 09:41
Note in the video the surge bu meter is at zero. This means surge thinks it is creating no sound. The video doesn’t show the surge screen to see quite what is going on and I don’t quite understand fl but a clearer view of the surge settings and go track would help I’m sure.

**Comment by mkruselj** [comment] 2022-08-23 19:15
@jxquae Can you try removing all plugins from that FL Studio project except for Surge XT (including any effect plugins you might have loaded across various tracks), save the project as a copy, see if it still happens? If it does, please remove all audio clips from the project, zip up the project and attach it here? Thanks!

**Comment by mkruselj** [comment] 2023-04-11 22:51
We haven't received a reply in quite some time now. We are going to close this issue for the time being. Please let us know if the issue is still happening for you or not, with the latest Surge XT 1.2 release, if possible!

**Closed by mkruselj** 2023-04-11 22:51 UTC
Labels: Host Specific, Awaiting User Information, Bug Report
