### ISSUE TITLE
Menus borked after closing second Surge with a menu open 

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7156] opened 2023-08-09 18:51 UTC
See this nice Surge menu, and the other Surge chilling in the bakground?
![1](https://github.com/surge-synthesizer/surge/assets/105538426/527d1d09-f66f-4893-887f-25b16ad7165e)

If you keep that menu open while closing the second Surge, the next time you open it (or any menu), it'll look like this: 
![2](https://github.com/surge-synthesizer/surge/assets/105538426/4da03d32-72b5-4f28-bdb9-a0035f342f94)

And I know it's been that way for a *long* time, I just didn't figure out the repro until now. :)

**Comment by baconpaul** [comment] 2023-08-09 18:52
ahh the perils of global looks and feels
this one might be ... tricky

**Comment by baconpaul** [comment] 2023-08-09 18:57
im surprised it doesn't crash tbh now i think of it
sugh
the problem is the look and feel needs a storage
but is global
and storage is not
so we ahve a 'last one in the door uses their storage' problem
isntead we should make the look and feel a global shared pointer wiht a stack of storages and
you unregister your storage when your editor goes away

**Comment by baconpaul** [comment] 2023-08-10 12:42
OK here's that blurb turned into something more concrete

SGE has this code

```
    surgeLF = std::make_unique<SurgeJUCELookAndFeel>(&(processor.surge->storage));

    juce::LookAndFeel::setDefaultLookAndFeel(surgeLF.get());
```

rather than having surgeLF be a member of SGE have it be a static global and only assign it if it is null.

Make the constructor a no-op constructor

to SurgeJUCELookAndFeel add a method called `pushStorage` and the SGE constructor, rather than the above, does

```
    if (!surgeLFGlobal)
        surgeLFGlobal = std::make_unique<>()
    surgeLFGlobal.pushStorage(synth-.storage)
    setGlobalLookAndFeel(surgeLFGlobal.get())
```

the SGE destructor, before the `sge.reset` does

`surgeLFGlobal.popStorage(sunth->storage)`


now what do push and pop storage do? A simple implementation would be

```
std::set<SurgeStorage *> storageStack;

voi pushStorage(SS*s ) { storageStack.insert(s); }
void popStorage(SS *s) { storageStack.erase(s); }
SurgeStorage getStorage() { assert(!storage.emtpy()); return *(storage.begin()); }
```

type thing. Then *remove* the member `storage` and use getStorage() everywhere

that's basically the plan of attack.

**Closed** 2023-08-21 00:31 UTC
Labels: UI, Bug Report
