### ISSUE TITLE
Include VST3 presets

### ISSUE THREAD

**Issue by apresta** [surge-synthesizer/surge#5913] opened 2022-02-25 16:54 UTC
VST3 presets make an instrument plugin much more accessible in different DAWs.
What would it take to (programmatically) generate .vstpreset files to include with Surge going forward?

**Comment by mkruselj** [comment] 2022-02-25 17:37
I think having both FXP and vstpresets is a bad idea. If we just move from FXP to vstpreset then we would still need to support our current FXP loader...

I vote for keeping it as is. We could just as well be saving our patches as raw human readable XML...

**Comment by baconpaul** [comment] 2022-02-25 17:53
basically you would need to force load the fxp in the vst3 then ask it to stream using the vst3 api.

the problem is force load an fxp isn't an exposed api through vst3 so you need a vst3 program that can load the vst3 but can also "reach through" to the surge inside

not super duper easy

exposing all the presets as plugin presets may also be feasible but (1) that breaks the AU and we don't know why; (2) we have 2000 presets and that's a lot and (3) it makes the LV2 generation untenable.

So I think your idea of a batch converter is the right one but that's not super easy code to write. I would probably just write a custom bit of code which loaded the surge vst3 as a dll so i could dig i through the api.

**Comment by mkruselj** [comment] 2022-02-25 17:56
> (1) that breaks the AU and we don't know why

Was that the before situation with hand-rolled wrappers, or currently with JUCE?

**Comment by baconpaul** [comment] 2022-02-25 17:56
the hand rolled wrappers never exposed any presets.

**Comment by baconpaul** [comment] 2022-02-25 17:58
> We could just as well be saving our patches as raw human readable XML...

our FXP contain binary data of the wavetable. Making them raw XML would make them 64/256ths bigger for every wavetable including patch.

**Comment by mkruselj** [comment] 2022-02-25 22:35
Eek!

**Comment by apresta** [comment] 2022-02-27 18:54
> basically you would need to force load the fxp in the vst3 then ask it to stream using the vst3 api.
> 
> the problem is force load an fxp isn't an exposed api through vst3 so you need a vst3 program that can load the vst3 but can also "reach through" to the surge inside
> 
> not super duper easy

Perhaps this could be simplified by temporarily changing the default preset. For each preset, set it as default, load Surge, export to .vstpreset with the same name. Then the converter wouldn't need to reach into the Surge UI.
I have zero knowledge of the codebase at this point, but does this make sense?

**Comment by baconpaul** [comment] 2022-02-27 19:32
Vstpreser is a format in its own right. We don’t have a writer for it. The vst3 api provides that so you need to either duplicate that code (like surge does for fxp) or call the vst3 as a vst3. 

Right now we don’t have a programaric way to write a vst3preset basically

if there was such a way you could do a variety of things but you gotta start with that step

**Comment by mkruselj** [comment] 2022-03-03 01:01
Closing as won't do.

**Closed by mkruselj** 2022-03-03 01:01 UTC
Labels: Feature Request, Won't Be Done
