### ISSUE TITLE
Possible input buffer bug causing audio input distortion?

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6524] opened 2022-08-18 12:12 UTC
User Inguz on Discord reports distorted audio input into Surge XT, supposedly it's due to <32 host block sizes causing the audio input buffers to fill incorrectly. @baconpaul to the rescue? :)

**Comment by baconpaul** [comment] 2022-08-20 14:54
Sigh. So it is definitely the case that if I get a block size < 32 the input will be incomplete when we process. I assume I have a 32 block lookahead in the input processor.

Some options

1: Add latency 32 to the synth. I strongly suggest we don't do that but add it here for completeness.
2: Add permanent latency 32 to the input and keep a buffer. Easy to do.
3: Make option (2) a user option
4: Perhaps toggle to option (2) automatically if a block is ever less than a factor of 32
5: Document this as needing fixed blocks of at least 32 to work with audio input


Thoughts welcome. For 1.1.1 I'm not sure we will do any of these though. They are all pretty big surgery on the inner loop and this isn't a regression - 1.0 and classic 1.9 work the same. So I'm going to bump out of 1.1.1 which I want to get out for all the other fixes.

**Comment by Andreya-Autumn** [comment] 2022-08-20 15:13
Here's a thought: Buffer sizes <32 are not exactly a common use case, let's make as little trouble as possible over this. 
To that end, I'm for options 4+5. Silently toggle in the background when audio input osc is up, and blocks are <32, document that this happens. 

Question, is the scene A-into-B audio  affected by this situation in any way?

**Comment by baconpaul** [comment] 2022-08-20 15:22
A into B is not impacted by this in any way. That's all done at a block level.

**Comment by baconpaul** [comment] 2022-08-20 15:22
and i agree; silently fail to latently processing the input is best we can do if we don't want to add overall latency. which we obviously dont

**Comment by mkruselj** [comment] 2022-08-20 15:23
> Here's a thought: Buffer sizes <32 are not exactly a common use case

This is not at all about audio driver buffer sizes, this is about DAW processing buffer sizes, which can and most often _are_ smaller than audio driver buffer sizes.

**Comment by baconpaul** [comment] 2022-08-20 15:26
yeah but it's really just fruity and very rarely logic which split it into blocks < n * 32

**Comment by mkruselj** [comment] 2023-01-08 22:39
So, FL Studio has an option to work with fixed buffer sizes (but not sure how many people know about it). We could pop up a dialog if we get an incomplete block at input (along with Do not show again checkbox etc), notifying the user that Surge requires fixed block sizes to operate properly.

Or, we could do it the u-he way and have a "base latency" option, which would be "off" and "<block size> samples". Then if we detect an irregular buffer size, we pop up a dialog:

![image](https://user-images.githubusercontent.com/2393720/211222630-2760e0aa-ecdf-4caf-b2d8-81b1a2341f9a.png)

**Comment by baconpaul** [comment] 2023-01-08 22:40
Right. I can also delay the audio input by 16 samples in that case if you want. I'll probably do some combination of these strategies when I turn to it indeed!

**Comment by baconpaul** [comment] 2023-01-08 22:40
32 also alas.

wonder if we should switch to 16 for 1.2

**Comment by mkruselj** [comment] 2023-01-08 22:43
I'd really want to save that change for XT2 if you want my 2c...

**Comment by baconpaul** [comment] 2023-01-08 23:01
yeah that's right
just then we need to replace "16" with "32" in all our comments here :)

**Comment by baconpaul** [comment] 2023-03-03 16:00
yes

i can also "just warn" 

"Just warn" is super duper easy

**Comment by mkruselj** [comment] 2023-03-03 17:16
Do a Foo impl and I'll make it pretty 🙂

**Comment by baconpaul** [comment] 2023-03-03 20:05
oh its easy to pop a box but it is slightly annoying to do it from the audio thread in a way which lets you not ask again. let me ponder this one for a bit more.

**Comment by mkruselj** [comment] 2023-03-03 23:48
Most likely fixed by #6866

**Comment by baconpaul** [comment] 2023-03-04 00:30
Nah it’s a totally different code path for the synth than the fx

**Comment by baconpaul** [comment] 2023-03-04 00:31
We will use a similar fix for sure but I have to write the code to have a double buffer which the synth doesn’t have now

**Closed** 2023-03-07 00:36 UTC
Labels: DSP, Bug Report
