### ISSUE TITLE
EnergyXT not showing GUI

### ISSUE THREAD

**Issue by UnoffialOfficial** [surge-synthesizer/surge#190] opened 2019-01-02 04:00 UTC
When opening Surge the GUI does not display. Only the default host gui. All other functions appear to work correctly.
 - OS: win 7
 - Host Energyxt
 - Version 2.7, AND 3.0

**Comment by esaruoho** [comment] 2019-01-02 06:04
@UnoffialOfficial screenshot? And did you use both vst2 and vst3?

**Comment by Jorgeelalto** [comment] 2019-01-02 10:23
@UnoffialOfficial do you have a log or error message from EnergyXT?

**Comment by esaruoho** [comment] 2019-02-08 10:41
Here's a page you can get an EnergyXT demo for windows+macOS from. I tried installing the macOS demo, but it crashes on macOS Mojave.
http://energy-xt.com/energyxt.html

@UnoffialOfficial could you try a February 2019 build of Surge from http://surge-synthesizer.github.io and confirm that EnergyXT does not show GUI with the newest build?

also, are you using 32-bit or 64-bit EnergyXT?

**Comment by tank-trax** [comment] 2019-02-21 19:52
I had the same issue using energyXT in WINE. Mind you the display was always an issue using WINE even with the 64 bit version. That being said LMMS partially displays the 32 bit GUI when loaded using Vestige.

**Comment by baconpaul** [comment] 2019-02-21 19:53
I installed an energyxt demo and couldn't make heads or tails of it. How do you even load a VST into a track? If someone could let me know that then I can debug this one day.

I'm mostly interested because I wonder if the same error that makes it not loadable here is also what's getting bitwig linux...

**Comment by tank-trax** [comment] 2019-02-21 20:00
@baconpaul 

go to File -> Setup - Browser

toggle to Plugins and add your VST folders there. They will appear in the left hand panel under Plugins

**Comment by baconpaul** [comment] 2019-02-21 20:09
Thank you. That's very useful. On Windows with 32 bit surge in energyXT 3.0 I see exactly this yeah, no UI. Cool. Something to debug one day!

Wonder what's happening. Very interesting.

**Comment by baconpaul** [comment] 2019-03-13 21:41
So this came up on KVR again so let me add some comments before I break. As I said I can reproduce this using the 32 bit build and EnergyXT 3.0. So how to debug. There's a lot of ways but the way I have debugged rando host vst2 problems which has worked is

1. Get a good fast build/test loop. So make it so you can build surge and run it in energyxt and then build it again and run the new one easily without error. (I use my powershell script in src/win/ for this but you use what works)

2. EnergyXT doesn't give you stdout and starting it in a debugger will suck. Too slow. So I would debug this with printf but you can't get printf without stdout so I would use my trick of adding say to the top of Vst2PluginInstance.cpp something like this

```
FILE *logfp = NULL
FILE *lfp() {
  if( logfp == NULL )
    logfp = fopen( "c:\\users\\paul\\surge-vst2.log", "w" )
  return logfp;
}
#define V2LF(...) { fprintf( lfp(), __VA_ARGS__ ); flush(lfp()); }
```

then in your code you can do

```
V2LF("I am here and state is %d\n", state_int);
```
and see it go by in the log, which presumably you `tail -f` or some such

3. The bug must be in the vst2 plugin interacting with the host. The host works with other plugins; our plugin works with other hosts. So
   1.What calls are being made to `::vendorSpecific`
   2. Does `::open()` even get called?
   3. Is there a weird request coming into `::canDo`
   4. is `tryInit()` ever called and if it is, does the editor get assigned

That's where I'd start. And if no-one else fixes this where eventually I will start!

**Comment by baconpaul** [comment] 2019-03-13 21:48
One other thought: does energyxt do something in a wierd different order than other hosts? Like does it call open before you can make a cframe or after a window has been drawn or some such? Just putting a func log in every function except the rt audio and midi process ones and comparing the startup order with another host would be illustrative

**Comment by tank-trax** [comment] 2019-03-13 23:20
@baconpaul just an FYI, energyXT was created/developed by @falkTX

**Comment by baconpaul** [comment] 2019-03-13 23:48
Oh well that’s super useful to know! @falktx since you know how the host works I am sure you have a way better plan than mine! Any insight welcome

**Comment by falkTX** [comment] 2019-03-14 05:55
> @baconpaul just an FYI, energyXT was created/developed by @falkTX

I know I have a lot of projects, but this information is just not true.
I have nothing to do with energyXT, besides one time trying to get its libaam library to support JACK in a better way.

**Comment by falkTX** [comment] 2019-03-14 05:57
One thing I know is that energyxt does not close plugin instances.
They were afraid of getting crashes or something...

**Comment by baconpaul** [comment] 2019-03-14 10:53
Ok! Well consider it a complement that I totally believed it :)

Useful info. I bet the create order is wonky if they are doing things like never close. The path I outlined above is the one to do then.

**Comment by tank-trax** [comment] 2019-03-14 14:32
my mistake... I assumed it was yours because of that libaam jack thing.... my apologies for the misunderstanding

**Comment by lunafreya** [comment] 2019-06-10 08:09
Is this issue resolved? I see no activity since the release of 1.6 Beta 7.

Did you got the GUI to show up on EnergyXT? You might need to install the latest version (1.6.1.1) to see if the GUI does show up on that particular host DAW.

**Comment by baconpaul** [comment] 2019-07-10 14:19
Linking to #938 even though this is more than just a zoom issue

**Comment by baconpaul** [comment] 2020-01-05 17:08
OK so my first task of the year was actually on windows so while I was fighting windows, cmake, and azure, I instrumented the vst2 and build and tested it in energyXT. My instrumented version is in this branch:

https://github.com/baconpaul/surge/tree/energy-xt-190

The problem is pretty straight forward though. energyXT creates an editor but never calls the dispatcher with effEditOpen, so we never open the editor.

I have no idea why energyXT never sends us effEditOpen but since it doesn't there's not much I can do.

We really need someone from the energyXT team to take a look here.

**Comment by baconpaul** [comment] 2020-01-06 00:57
From KVR:

> Jørgen Aase (the dev) has abandoned energyxt a long time ago unfortunately. So seems this issue wont be resolved. But i will try surge v 1.5 which should work according to layzer. The latest version do work in Reaper so its not that big of a deal

So with the fact that I’m not getting open called, 1.5 still works for the few users, and there’s no apparent way to figure out what’s happening in the host, I’m going to close this. If someone objects to that please reopen it (and share an idea for a plan of what to do also!)

Thanks

**Closed by baconpaul** 2020-01-06 00:57 UTC
Labels: host issue
