### ISSUE TITLE
Tear-outs hide in Reaper on MacOS

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6633] opened 2022-09-28 19:58 UTC
When tearing our the filter analyzer, MSEG etc etc, those windows take on what I'd call a "never-on-top" behavior. They are always behind the Surge UI window, whether the latter is pinned or not. 

EDIT: So there turns out to be a few related issues here. One was that the pin button was missing. This is adressed by #6634.

The other issue is that when neither window is un-pinned, the tearout windows are always-behind the main Surge UI window. Obviously window focus usually determines which window goes on top. 
This is especially annoying because it means pressing the tear-out button apparently just makes the window in question dissappear. At which point one has to move the main UI out of the way to be able to access the pin button so the tearout can go on top. Not very useful. 

In less problematic but probably related news, both windows pinned also doesn't correctly follow the last-focused-window-on-top paradigm.

**Comment by mkruselj** [comment] 2022-09-28 20:32
The cause is because "always on top" pin button is not being repositioned for Mac, it seems to be drawn way out of overlay window's title bar area, so you cannot keep those torn out overlays on top of other windows if you want to. Simple fix, I think.

**Comment by mkruselj** [comment] 2022-11-29 12:52
@Andreya-Autumn Huh did we forget to close this issue?

**Comment by Andreya-Autumn** [comment] 2022-11-30 13:03
Well, the question of how windows behave when neither or both the main UI and the tearout are pinned remains open I guess. 
Expected/best behavior would be pinned-over-unpinned (obviously) when only one is, but last-focused-on-top when neither/both is. But I seem to remember @baconpaul saying that's difficult to achieve, and present behavior is ok by me if so. 

I guess, if it's possible to make sure that all the tearouts default to pinned when the first time they're torn out, that would solve the tear-outs just vanishing. I could imagine that problem being annoying for new users, so maybe that's nice to do.

**Comment by mkruselj** [comment] 2022-11-30 20:00
I think something that also plays into this all is Reaper's window management on Mac is apparently not exactly pristine, nor matching behavior on Windows...

**Comment by baconpaul** [comment] 2023-01-08 23:10
@Andreya-Autumn @mkruselj I remember you both doing a lot on this when I was deep in rack land. What's left to be done here? Is it working as expected now?

**Comment by Andreya-Autumn** [comment] 2023-01-09 09:32
No, my previous comment above stills stands. Whenever both/neither tearouts and main window are pinned, the tearouts are always-behind.

ED seems willing to attribute that to reaper's window management, but I've never seen a problem like this anywhere else. 

If last-focused-on-top is difficult to achieve, we could just try to make sure the tearouts default to pinned on a fresh install. Those pin entries have an entry in user defaults, but before it's set the first time they're un-pinned I think. 
Changing that default to pinned, would solve the problem where you tear out and the window seemingly vanishes. 

(Unless the user has the main UI Pinned but you can't win em all I guess).

**Comment by baconpaul** [comment] 2023-01-09 13:42
Ok so the problem is pin both and the main window always wins?

**Comment by baconpaul** [comment] 2023-01-09 13:45
Ahhh and that’s in reaper mac right? Thanks

**Comment by mkruselj** [comment] 2023-01-09 13:47
Happens on Win too. Happens in Live and FL too. DAW doesn't matter apparently. So maybe for plugin only, we should default to having tearouts pinned.

That said, I can at least see the tearout window in the taskbar and can even Alt+Tab to it...

**Comment by baconpaul** [comment] 2023-01-09 13:51
Cool now I understand the problem 

so let me look. I wonder if I am being “on top of” the wrong window somehow when daw hosted

**Comment by baconpaul** [comment] 2023-01-25 02:53
OK so I just played with this in reaper 6.73

I think its just a daw behaviour. Reaper does it, Logic AU does it, bitwig doesn't, Live 11.2 does. Bespoke does, standalone doesn't. 

so that 'bitwig doesn't' makes me think somehow the fx window is getting 'sticky front' in the daw environments.

harumph. 

I can sort of fix this by calling `   dw->setAlwaysOnTop(true);` which sets it always on top. But that's pretty annoying since it floats over everything no matter what. Sort of the opposite problem.

alwaysOnTop calls `NSWindow setLevel` so wonder if theres some mac specific code I could write. But it's not super easy

The easiest thing to do is to have an 'tearouts always on front' option which defaults true for vst3 / au mac and false elsewhere but is togglable away.

hard.

**Comment by baconpaul** [comment] 2023-01-25 02:54
Another option is when i open the tarot, find the 'level' of my parent nsview and set the dw level to that. May work. Worth a try.

**Comment by Andreya-Autumn** [comment] 2023-01-25 10:53
Tarot lol! 

My cards are in favor of that last solution, if it works. :) 

Otherwise, since again the unpinned behavior in the problematic DAWs just isn't useful, I'm in favor "tarot cards always in front" as an option, and just removing the pin/unpin button when that option is selected.

**Comment by mkruselj** [comment] 2023-01-25 11:41
Tbh I don't think this should be an option. We should just always set tearouts as always on top in plugin case and keep the pin button there in case user wants it the other way. Leave nothing to chance.

**Comment by baconpaul** [comment] 2023-01-25 12:08
Yeah smart

**Comment by Andreya-Autumn** [comment] 2023-01-25 13:22
Sure, that works too. 👍🏻

**Comment by baconpaul** [comment] 2023-01-25 14:12
OK so let me see if the objective c magic can work. if i can't make it work in less than 20 minutes i'll just go to 'teraouts always pinned in plugins' mode.

**Comment by baconpaul** [comment] 2023-01-25 14:13
oh do we want that mac only or is it all platforms we want that behavior?

**Comment by mkruselj** [comment] 2023-01-25 14:15
It happens over here too.

**Comment by baconpaul** [comment] 2023-01-25 14:16
OK great thanks!

**Closed** 2023-01-25 15:57 UTC
Labels: UX, Bug Report
