### ISSUE TITLE
Filter subtype left click doesn't work

### ISSUE THREAD

**Issue by TorbjornHedberg** [surge-synthesizer/surge#6264] opened 2022-06-08 17:52 UTC
**Bug Description:**
Changing filter subtype (the numbers 1 - n) can only be done once by ordinary (left) mouse click. Selecting via right click menu works. 

Happens in Cubase 11 and 12. Works as expected in stand alone. 

**Surge XT Version**
Version: Surge XT 1.1.nightly.a110623
Build: 2022-06-08 @ 15:07:22 on 'fv-az423-560/pipeline' with 'MSVC-19.29.30145.0' using JUCE 6.1.6
System: Windows 64-bit VST3 on AMD Ryzen 9 3900X 12-Core Processor            
Host: Steinberg Cubase @ 48.0 kHz

* Version:
* Plugin Type: [VST3]
* Bitness: [64-bit]

**Reproduction Steps:**
1. Click on 'Filter subtype'

**Computer Information (please complete the following!):**
 - OS: Windows 11
 - Host: Cubase
 - Version: 11 /12

**Additional
Thanks for a great release!

**Comment by mkruselj** [comment] 2022-06-08 21:50
Hmmm, I can't confirm this across my DAWs (Reaper 6, Live 11, Bitwig 3, Studio One 5, FL20)...

**Comment by TorbjornHedberg** [comment] 2022-06-08 22:02
Hmmm… maybe its specific to this computer. I’ll try another tomorrow. Have no other DAW, though.

**Comment by baconpaul** [comment] 2022-06-09 10:44
yeah i bet thats it
open the vst3 in bws and click once on teh filter subype. the ui changes but the automation value doesnt
most daws will let the plugin win
but i bet cubase is being a stickler

somewhere in the path for this switch (which is implemented as a real hack) we have forgotten a notify begin / end edit and so on

**Comment by baconpaul** [comment] 2022-06-09 10:46
moreover, the RMB *does* update the parameter in the DAW. So I am almost 100% sure this is the cause.

Will look today. Have some tome for 11beta bugs

Thank you @TorbjornHedberg - will continue to update this issue if/when changes are available

**Comment by baconpaul** [comment] 2022-06-09 10:47
yup around line 3144 of SGEVC we update the param in the click mode but don't wrap it in a notify/etc...

**Comment by baconpaul** [comment] 2022-06-09 14:50
Hiya!

So the next nightly should resolve this if my theory is correct. While none of the other DAWs block an update, they all have an automation inconsistency. I don't have cubase but if you could give the nightly a whirl in a couple of hours once it builds, and let us know, i would appreciate it

**Comment by TorbjornHedberg** [comment] 2022-06-09 15:44
Same behavior with this build. But please note: it's obviously a teeny tiny inconvenience so don't waste too much time on it...

Version: Surge XT 1.1.nightly.f5678fc
Build: 2022-06-09 @ 13:11:50 on 'WIN-HMIBAHURQ74/pipeline' with 'MSVC-19.29.30145.0' using JUCE 6.1.6
System: Windows 64-bit VST3 on AMD Ryzen 9 3900X 12-Core Processor            
Host: Steinberg Cubase @ 48.0 kHz

**Comment by baconpaul** [comment] 2022-06-09 15:47
That build doesn’t have the fix - it’s from earlier in the day. The next one should be here in about 15 minutes. Will have version e3640e5

**Comment by baconpaul** [comment] 2022-06-09 16:28
Awesome! Thanks for the report. The fix is useful everywhere. 

Closing this.

**Closed by baconpaul** 2022-06-09 16:28 UTC
Labels: Host Specific, UX, Bug Report
