### ISSUE TITLE
Linux: Host crashes when using arrows to navigate menus

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#548] opened 2019-02-09 01:54 UTC
If trying to navigate through menus using up, down, left or right arrows the Host/Daw immediately crashes. Same result in Carla, Reaper, Waveform, Radium.

**Comment by tank-trax** [comment] 2019-02-09 02:26
Tested on Linux Mint 19.1 using Reaper with falktx's build and it does not crash when trying to navigate through menus using arrows. It does not function though. Using the arrow will shut down the menu and return to the main screen. 

Note: 
-> if the menu is not highlighted, the up and down arrows will navigate through the Patch list and left and right through the Category list without any issues on both Linux systems.

**Comment by tank-trax** [comment] 2019-02-13 16:41
In Windows it's possible to navigate menus using up, down, left, and right arrows to select a preset

![arrows menu windows](https://user-images.githubusercontent.com/41337033/52727684-c2630000-2f83-11e9-829b-c2f4679849a8.gif)

On Linux it is only possible to use the mouse wheel to get the menu items below the app's borders or to select presets

![menus mouse wheel 02](https://user-images.githubusercontent.com/41337033/52727806-00f8ba80-2f84-11e9-8a94-15b36feb1979.gif)

if the up, down, left, or right arrows are attempted on Linux it will freeze/crash

**Comment by baconpaul** [comment] 2019-02-14 20:24
1: I've confirmed this yes mouse wheel works and arrows crash
2: The crash is in CFrame::endModalViewSession
3: I can't get the stack because the crash in GDB hung my entire VM desktop!

**Comment by baconpaul** [comment] 2019-02-14 20:38
Stack:
```
Thread 1 "carla-bridge-na" received signal SIGSEGV, Segmentation fault.
0x00007ffff20532e4 in std::__uniq_ptr_impl<VSTGUI::ModalViewSession, std::default_delete<VSTGUI::ModalViewSession> >::_M_ptr (this=0x2f006c61636f6e26)
    at /usr/include/c++/7/bits/unique_ptr.h:147
147	      pointer    _M_ptr() const { return std::get<0>(_M_t); }
(gdb) where
#0  0x00007ffff20532e4 in std::__uniq_ptr_impl<VSTGUI::ModalViewSession, std::default_delete<VSTGUI::ModalViewSession> >::_M_ptr (this=0x2f006c61636f6e26)
    at /usr/include/c++/7/bits/unique_ptr.h:147
#1  0x00007ffff20448bc in std::unique_ptr<VSTGUI::ModalViewSession, std::default_delete<VSTGUI::ModalViewSession> >::get (this=0x2f006c61636f6e26)
    at /usr/include/c++/7/bits/unique_ptr.h:337
#2  0x00007ffff2053476 in std::unique_ptr<VSTGUI::ModalViewSession, std::default_delete<VSTGUI::ModalViewSession> >::operator bool (this=0x2f006c61636f6e26)
    at /usr/include/c++/7/bits/unique_ptr.h:351
#3  0x00007ffff2044a7a in std::operator==<VSTGUI::ModalViewSession, std::default_delete<VSTGUI::ModalViewSession> >(std::unique_ptr<VSTGUI::ModalViewSession, std::default_delete<VSTGUI::ModalViewSession> > const&, decltype(nullptr)) (__x=std::unique_ptr<VSTGUI::ModalViewSession> = {...}) at /usr/include/c++/7/bits/unique_ptr.h:690
#4  0x00007ffff1fd4397 in VSTGUI::CFrame::endModalViewSession (this=0x1363cb0, session=0x3cbd540) at vstgui.surge/vstgui/lib/cframe.cpp:976
#5  0x00007ffff1f9d663 in VSTGUI::GenericOptionMenu::<lambda(VSTGUI::CView*, VSTGUI::IdStringPtr, VSTGUI::Animation::IAnimationTarget*)>::operator()(VSTGUI::CView *, VSTGUI::IdStringPtr, VSTGUI::Animation::IAnimationTarget *) const (__closure=0x3c010f0) at vstgui.surge/vstgui/lib/platform/common/genericoptionmenu.cpp:597
#6  0x00007ffff1f9e950 in std::_Function_handler<void(VSTGUI::CView*, char const*, VSTGUI::Animation::IAnimationTarget*), VSTGUI::GenericOptionMenu::removeModalView(VSTGUI::PlatformOptionMenuResult)::<lambda(VSTGUI::CView*, VSTGUI::IdStringPtr, VSTGUI::Animation::IAnimationTarget*)> >::_M_invoke(const std::_Any_data &, VSTGUI::CView *&&, const char *&&, VSTGUI::Animation::IAnimationTarget *&&) (__functor=..., __args#0=@0x7fffffffd0c0: 0x1245ae0, __args#1=@0x7fffffffd0b8: 0x3ba4940 "OptionMenuDone", 
    __args#2=@0x7fffffffd0b0: 0x3cc7080) at /usr/include/c++/7/bits/std_function.h:316
#7  0x00007ffff204dcea in std::function<void (VSTGUI::CView*, char const*, VSTGUI::Animation::IAnimationTarget*)>::operator()(VSTGUI::CView*, char const*, VSTGUI::Animation::IAnimationTarget*) const (this=0x3ba4968, __args#0=0x1245ae0, __args#1=0x3ba4940 "OptionMenuDone", __args#2=0x3cc7080) at /usr/include/c++/7/bits/std_function.h:706
#8  0x00007ffff202ad57 in VSTGUI::Animation::Detail::Animation::~Animation (this=0x3ba4920, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at vstgui.surge/vstgui/lib/animation/animator.cpp:230
#9  0x00007ffff202aec0 in VSTGUI::Animation::Detail::Animation::~Animation (this=0x3ba4920, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at vstgui.surge/vstgui/lib/animation/animator.cpp:239
#10 0x00007ffff1ec21d6 in VSTGUI::ReferenceCounted<int>::forget (this=0x3ba4920) at vst3sdk/vstgui4/vstgui/lib/vstguibase.h:263
#11 0x00007ffff204e0fe in VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation>::~SharedPointer (this=0x3bfef80, __in_chrg=<optimized out>)
    at vstgui.surge/vstgui/lib/vstguibase.h:401
#12 0x00007ffff208ac1d in std::_Destroy<VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation> > (__pointer=0x3bfef80) at /usr/include/c++/7/bits/stl_construct.h:98
#13 0x00007ffff2082a03 in std::_Destroy_aux<false>::__destroy<VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation>*> (__first=0x3bfef80, __last=0x3bfef88)
    at /usr/include/c++/7/bits/stl_construct.h:108
#14 0x00007ffff2072c04 in std::_Destroy<VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation>*> (__first=0x3bfef80, __last=0x3bfef88)
    at /usr/include/c++/7/bits/stl_construct.h:137
#15 0x00007ffff205ed7f in std::_Destroy<VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation>*, VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation> > (
    __first=0x3bfef80, __last=0x3bfef88) at /usr/include/c++/7/bits/stl_construct.h:206
#16 0x00007ffff204de5d in std::vector<VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation>, std::allocator<VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation> > >::~vector (this=0x7fffffffd2b0, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:434
#17 0x00007ffff205f602 in VSTGUI::DispatchList<VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation> >::postForEach (this=0x11b8610)
    at vstgui.surge/vstgui/lib/controls/../dispatchlist.h:112
#18 0x00007ffff202f8d0 in VSTGUI::DispatchList<VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation> >::forEach<VSTGUI::Animation::Animator::removeAnimations(VSTGUI::CView*)::<lambda(const VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation>&)> >(VSTGUI::Animation::Animator::<lambda(const VSTGUI::SharedPointer<VSTGUI::Animation::Detail::Animation>&)>) (this=0x11b8610, proc=...) at vstgui.surge/vstgui/lib/controls/../dispatchlist.h:154
#19 0x00007ffff202b8cb in VSTGUI::Animation::Animator::removeAnimations (this=0x3b62620, view=0x1245ae0) at vstgui.surge/vstgui/lib/animation/animator.cpp:311
#20 0x00007ffff1fd4813 in VSTGUI::CFrame::onViewRemoved (this=0x1363cb0, pView=0x1245ae0) at vstgui.surge/vstgui/lib/cframe.cpp:1071
#21 0x00007ffff1fea0ae in VSTGUI::CView::removed (this=0x1245ae0, parent=0x1363cb0) at vstgui.surge/vstgui/lib/cview.cpp:436
#22 0x00007ffff1ff299d in VSTGUI::CViewContainer::removed (this=0x1245ae0, parent=0x1363cb0) at vstgui.surge/vstgui/lib/cviewcontainer.cpp:1432
#23 0x00007ffff1fd9214 in VSTGUI::CLayeredViewContainer::removed (this=0x1245ae0, parent=0x1363cb0) at vstgui.surge/vstgui/lib/clayeredviewcontainer.cpp:67
#24 0x00007ffff1feec30 in VSTGUI::CViewContainer::removeView (this=0x1363cb0, pView=0x1245ae0, withForget=true) at vstgui.surge/vstgui/lib/cviewcontainer.cpp:594
#25 0x00007ffff1fd5045 in VSTGUI::CFrame::removeView (this=0x1363cb0, pView=0x1245ae0, withForget=true) at vstgui.surge/vstgui/lib/cframe.cpp:1237
#26 0x00007ffff1fd4411 in VSTGUI::CFrame::endModalViewSession (this=0x1363cb0, session=0x3cbd540) at vstgui.surge/vstgui/lib/cframe.cpp:982
#27 0x00007ffff1fd41e3 in VSTGUI::CFrame::clearModalViewSessions (this=0x1363cb0) at vstgui.surge/vstgui/lib/cframe.cpp:951
#28 0x00007ffff1fd5074 in VSTGUI::CFrame::removeAll (this=0x1363cb0, withForget=true) at vstgui.surge/vstgui/lib/cframe.cpp:1243
#29 0x00007ffff1f2ece4 in SurgeGUIEditor::close_editor (this=0x127afd0) at src/common/gui/SurgeGUIEditor.cpp:1213
#30 0x00007ffff1f28f79 in SurgeGUIEditor::openOrRecreateEditor (this=0x127afd0) at src/common/gui/SurgeGUIEditor.cpp:510
#31 0x00007ffff1f27e42 in SurgeGUIEditor::idle (this=0x127afd0) at src/common/gui/SurgeGUIEditor.cpp:250
#32 0x00007ffff1f83fdc in AudioEffect::dispatcher (this=0x1188e50, opcode=19, index=0, value=0, ptr=0x0, opt=0)
```

**Comment by baconpaul** [comment] 2019-02-14 20:41
I wonder if this is because on Linux we handle the arrow keys in our app and it gets confused (on windows and mac it would be delivered to a little window). Just thinking out loud.

**Comment by baconpaul** [comment] 2019-02-14 20:43
Yup that's it.

OK I have a not-very-awesome fix for this coming in, but a fix.

**Closed** 2019-02-14 21:28 UTC
Labels: linux
