### ISSUE TITLE
VST2 64 bit .dll not recognised by FL Studio

### ISSUE THREAD

**Issue by Flayzen** [surge-synthesizer/surge#806] opened 2019-04-03 12:23 UTC
The VST2 64 bit version of Surge is not being detected by FL Studio 20.1.1 in Windows 10 when scanning for new plugins. Yes, I have configured the search to look in the correct folder - the .dll is is in my VST Plugins folder with all the others. The VST3 version is detected.

**Comment by baconpaul** [comment] 2019-04-03 12:30
Thanks. Several other folks have reported this. I have no idea how to debug it though! Are there any logos generated or anything? 

The good news is with beta 7 and beta 8, the VST3 is mostly complete. With the exception of maybe a couple of MPE edge cases it should be fine to use!

**Comment by baconpaul** [comment] 2019-04-06 02:34
So from KVR we discovered if dlls have the same name that FL only gets one of them. So I think the trick here is to rename your installed dll to surge-vst2.dll or some such and rescan. Can you let us know if that works?

**Comment by adriansuri** [comment] 2019-04-13 02:22
I had a similar issue with ableton, while the VSt3 version showed up in Ableton 10 beta, the VST2 did not install  and the c:\program files\VSTPlugins\Surge directory simply contained an uninstall program?  I searched the whole of my c: drive for surge-vst2.dll  but without luck

**Comment by baconpaul** [comment] 2019-04-13 11:43
The problem is for FL at least and for some other hosts that both the VST2 and VST3 are called “Surge.dll” (or Surge-x86.dll for the 32 bit version) and even though the installer installs them in distinct directories the hosts don’t use the directory name for distinctness. @adriansuri I’m not sure what you saw - we don’t even ship and uninstaller as far as I know - but you would not have found surge-vst2.dll if you ran the beta or nightly installers.

I wonder if we should change that behavior on windows for 1.6? I think we probably want to.

**Comment by adriansuri** [comment] 2019-04-14 00:31
Hi

Thanks I will download tomorrows build see if it work, and yes  it was an uninstaller for your vst/vst3 



Though to be honest  it’s not so important as the vst3 plugin works fine, very impressive piece of kit, thanks for your hard work pips 

Adrian

Sent from Mail for Windows 10

**Comment by baconpaul** [comment] 2019-04-14 11:33
You are welcome!

When you run thebinstaller it prompts for a vst2 directory. After the installer runs find the surge In that directory and just rename it - then we think both will be available. We haven’t changed the builds to do this though yet.

**Comment by baconpaul** [comment] 2019-05-01 19:44
<img width="304" alt="Screen Shot 2019-05-01 at 3 42 35 PM" src="https://user-images.githubusercontent.com/13387561/57038460-eef3f300-6c27-11e9-8de9-53fd1882770b.png">

I'm going to close this issue because I think it is just an FL choice. From chatting with some folks FL chooses VST3 over VST2 if both exist unless you edit the above setting. So should be possible either by renaming or by using that setting. 

Thanks!

**Closed by baconpaul** 2019-05-01 19:44 UTC
Labels: host issue
