### ISSUE TITLE
Wavetables > 1024 samples do not render correctly in Window oscillator

### ISSUE THREAD

**Issue by theofficialajyoung** [surge-synthesizer/surge#1170] opened 2019-09-15 03:09 UTC
First, the basics out of the way:

Surge NIGHTLY-2019-09-12-08cde89
64-bit Windows VST2
Built Sep 12 2019 22:05:35

Testing on Reaper Windows 64-bit v5.982

While using Surge with some Serum-created Wavetables, I noticed that they do not load as expected when using the "Window" oscillator mode. It does not load a full cycle of the wave, but instead seems to load a quietly amplified version of the window shape.

Here is a gif demonstrating the issue:

![Surge Window Serum Wavetables](https://user-images.githubusercontent.com/33675880/64916104-2af1a580-d73c-11e9-8c8f-be45759747ea.gif)

**Comment by mortfell** [comment] 2019-09-15 03:14
oh yeah woops I have noticed this before and forgot to report 😔
thanks @theofficialajyoung 

Window oscillator also doesn't work correctly as the Carrier in an FM routing configuration, I'm assuming that is by design though.

**Comment by baconpaul** [comment] 2019-09-15 11:20
Oh I bet it can’t extend the window to the size of the larger tables.

Do you have a test table around you can attach to this issue or does any 2048 wide serum table show the problem?

I’m not 100% sure I can resolve this for 1.6.2 but would sooner not ship with this bug so I’m going to optimisitically tag it for the upcoming release.

**Comment by baconpaul** [comment] 2019-09-15 13:32
Oh and yeah window totally ignores fm. We should make that a separate issue tha. This one.

**Comment by baconpaul** [comment] 2019-09-15 14:21
OK so good news. This is nothing to do with the Serum importer. I made a set of .wt files with 512 -> 4096 samples and the window oscillator fails above 1024 whereas the wavetable oscillator does not.

The reason for this is the window oscillator is basically using the windows in "resources/data/windows.wt" to pick the co-table which is used for interpolation (that's the window parameter) and in the event that the interpolated table is longer than the window table, it blows up.

So the solution here is either

1. stop it blowing up or
2. make a version of the windows which are 4096 samples long and use those if the input is a long one (but keep the current version at and below 1024 to not change the sound)

The second is easy enough but tedious; the first I'm not sure but I would rather do it if I can. So I will investigate the first and then go from there.

I also changed the title of the issue just FYI, to reflect this update. 

Thanks for the report!

**Comment by mortfell** [comment] 2019-09-15 15:13
Awesome work !

**Comment by baconpaul** [comment] 2019-09-15 19:11
Actually a super simple fix.

**Comment by baconpaul** [comment] 2019-09-15 19:25
Just pushed the fix to this. Should be in the nightly within the next 30-40 minutes.

Thanks for the excellent report.

**Closed** 2019-09-15 19:25 UTC
Labels: ui change
