### ISSUE TITLE
Look for resources in ${CMAKE_INSTALL_PREFIX}

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3641] opened 2021-01-15 15:43 UTC
**Bug Description:**
When I install using a different prefix, I get:
```
Surge was unable to load factory patches from '/usr/share/Surge/'. Please reinstall Surge!
Surge Error
Surge Resources Loading Error
Unable to load '/usr/share/Surge//windows.wt'. This file is required for Surge to work properly. This occurs when Surge is incorrectly installed and its resources are not found at /usr/share/Surge or ~/.local/share/Surge. Please reinstall Surge and try again!
Unable to load  '"/usr/share/Surge/paramdocumentation.xml"'!
```

So far I patched that in my package by replacing ``/usr/share/Surge`` with the correct path in src/common/SurgeStorage.cpp .
I'd be fine to keep using that patch, just wanted to let you know about it.

**Comment by baconpaul** [comment] 2021-01-15 16:02
What version of the code are you building?

Here's the code at head / 1.8. I'm surprised it doesn't work.

```
    if (!fs::is_directory(string_to_path(datapath)))
       {
          if (fs::is_directory(string_to_path(std::string(Surge::Build::CMAKE_INSTALL_PREFIX) + "/share/surge")))
          {
             datapath = std::string() + Surge::Build::CMAKE_INSTALL_PREFIX + "/share/surge";
          }
          else if (fs::is_directory(string_to_path(std::string(Surge::Build::CMAKE_INSTALL_PREFIX) + "/share/Surge")))
          {
             datapath = std::string() + Surge::Build::CMAKE_INSTALL_PREFIX + "/share/Surge";
          }
          else
          {
             std::string systemDataPath = "/usr/share/surge/";
             if (fs::is_directory(string_to_path(systemDataPath)))
                datapath = systemDataPath;
             else
                datapath = "/usr/share/Surge/";
          }
       }
```

**Comment by magnetophon** [comment] 2021-01-15 16:25
Surge Synthesizer
Plugin Host:	Ardour
System:	x86_64 CPU, Linux VST3, 64-bit
Build Info:	Built on 1980-01-01 at 00:00:00, using local host 'localhost'
Version:	1.8.fetchgit.6e0b130

That is my branch from https://github.com/surge-synthesizer/surge/pull/3640, based on 4c4f74196f199e1d199cc7b78fa2844446228c63

**Comment by baconpaul** [comment] 2021-01-15 16:33
huh i wonder why it is ignoring that CMAKE_ISNTALL_PREFIX

In your build directory is a file called `build/geninclude/version.cpp` which has the value for Surge::Build::CMAKE_INSTALL_PREFIX in it. Is that value set correctly?

**Comment by baconpaul** [comment] 2021-01-15 16:34
Oh I have a theory. Hold on.

**Comment by baconpaul** [comment] 2021-01-15 16:35
Yup I see the problem. Hold on.

**Comment by baconpaul** [comment] 2021-01-15 16:47
OK so I have a fix but I don't want to merge it for 18. 
Basically the problem is CMAKE_ISNTALL_PREFIX isn't passed to storage
but if I do pass it to storage I need to set it in our pipelines
which means retesting our deb and also re-configuring all the builds people do by hand
So for now, keep your patch, and I will fix this up in 19.

Or if you prefer, apply this patch

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6bab6c8d..105d51b9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -129,6 +129,7 @@ execute_process(
                            -D SURGESRC=${CMAKE_SOURCE_DIR} -D SURGEBLD=${CMAKE_BINARY_DIR}
                            -D AZURE_PIPELINE=${AZURE_PIPELINE}
                            -D WIN32=${WIN32}
+                           -D CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
                            -P ${CMAKE_SOURCE_DIR}/cmake/versiontools.cmake
                            )
 add_custom_target( git-info BYPRODUCTS ${CMAKE_BINARY_DIR}/geninclude/version.cpp
@@ -137,6 +138,7 @@ add_custom_target( git-info BYPRODUCTS ${CMAKE_BINARY_DIR}/geninclude/version.cp
                            -D SURGESRC=${CMAKE_SOURCE_DIR} -D SURGEBLD=${CMAKE_BINARY_DIR}
                            -D AZURE_PIPELINE=${AZURE_PIPELINE}
                            -D WIN32=${WIN32}
+                           -D CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
                            -P ${CMAKE_SOURCE_DIR}/cmake/versiontools.cmake
                            )
```

to 18 which will fix it

**Comment by magnetophon** [comment] 2021-01-15 16:48
Awesome, thanks!

**Comment by baconpaul** [comment] 2021-01-25 02:55
I plan to apply this diff after 1.8.1 into the 19 family but just a reminder to myself that when I do I need to set this variable in the release pipeline to /usr/ rather than /usr/local/ to make our deb work consistently.

**Comment by baconpaul** [comment] 2021-02-10 16:31
OK this will be in our 1.9 release in April. Adjusted pipelines and so forth.

**Closed** 2021-02-10 17:41 UTC
Labels: Bug Report
