### ISSUE TITLE
Cannot compile on ARM platfomr(RPI4)

### ISSUE THREAD

**Issue by phil123456** [surge-synthesizer/surge#4255] opened 2021-04-06 14:53 UTC
**Bug Description:**
The build fails on raspberry pi4

**Surge Version**
latest repository master @ 06/04/2021

* Version:
* Plugin Type: LV2
* Bitness: ARM

**Reproduction Steps:**

follow the build steps for linux on a raspberry pi4

**Expected Behavior:**
should build

**Error**
```
Scanning dependencies of target surge-shared
[ 53%] Building CXX object CMakeFiles/surge-shared.dir/src/common/dsp/effect/BBDEnsembleEffect.cpp.o
[ 53%] Building CXX object CMakeFiles/surge-shared.dir/src/common/dsp/effect/CombulatorEffect.cpp.o
/home/pi/surge/src/common/dsp/effect/CombulatorEffect.cpp: In member function ‘virtual void CombulatorEffect::process(float*, float*)’:
/home/pi/surge/src/common/dsp/effect/CombulatorEffect.cpp:167:46: error: requested alignment 16 is larger than 8 [-Werror=attributes]
     float dataOS alignas(16)[2][BLOCK_SIZE_OS];
                                              ^
In file included from /home/pi/surge/src/common/dsp/effect/chowdsp/bbd_utils/BBDFilterBank.h:3,
                 from /home/pi/surge/src/common/dsp/effect/chowdsp/bbd_utils/BBDDelayLine.h:9,
                 from /home/pi/surge/src/common/dsp/effect/BBDEnsembleEffect.h:28,
                 from /home/pi/surge/src/common/dsp/effect/BBDEnsembleEffect.cpp:16:
/home/pi/surge/src/common/dsp/SSEComplex.h: In constructor ‘SSEComplex::SSEComplex(std::initializer_list<float>, std::initializer_list<float>)’:
/home/pi/surge/src/common/dsp/SSEComplex.h:55:32: error: requested alignment 16 is larger than 8 [-Werror=attributes]
         float rfl alignas(16)[4], ifl alignas(16)[4];
                                ^
/home/pi/surge/src/common/dsp/SSEComplex.h:55:52: error: requested alignment 16 is larger than 8 [-Werror=attributes]
         float rfl alignas(16)[4], ifl alignas(16)[4];
                                                    ^
/home/pi/surge/src/common/dsp/SSEComplex.h: In member function ‘std::complex<float> SSEComplex::atIndex(int) const’:
/home/pi/surge/src/common/dsp/SSEComplex.h:74:32: error: requested alignment 16 is larger than 8 [-Werror=attributes]
         float rfl alignas(16)[4], ifl alignas(16)[4];
                                ^
/home/pi/surge/src/common/dsp/SSEComplex.h:74:52: error: requested alignment 16 is larger than 8 [-Werror=attributes]
         float rfl alignas(16)[4], ifl alignas(16)[4];
                                                    ^
/home/pi/surge/src/common/dsp/SSEComplex.h: In member function ‘SSEComplex SSEComplex::map(std::function<std::complex<float>(const std::complex<float>&)>)’:
/home/pi/surge/src/common/dsp/SSEComplex.h:88:32: error: requested alignment 16 is larger than 8 [-Werror=attributes]
         float rfl alignas(16)[4], ifl alignas(16)[4];
                                ^
/home/pi/surge/src/common/dsp/SSEComplex.h:88:52: error: requested alignment 16 is larger than 8 [-Werror=attributes]
         float rfl alignas(16)[4], ifl alignas(16)[4];
                                                    ^
/home/pi/surge/src/common/dsp/SSEComplex.h:92:33: error: requested alignment 16 is larger than 8 [-Werror=attributes]
         float rflR alignas(16)[4], iflR alignas(16)[4];
                                 ^
/home/pi/surge/src/common/dsp/SSEComplex.h:92:54: error: requested alignment 16 is larger than 8 [-Werror=attributes]
...
```

**screenshot**
https://i.postimg.cc/Yq2vcGym/Untitled.png

let me know if you need more informations

**Comment by mkruselj** [comment] 2021-04-06 15:02
You should have reopened your original issue #4206. Please continue there.

**Comment by baconpaul** [comment] 2021-04-06 15:48
Are you a 32 or 64 bit pi os 
What is your compiler version 
This looks like the compiler is mis complaining about a correct alignment directive to me and we compile with warnings are errors so in whatever config you are using (which my guess is a 32 bit pi os) we need to add the -Wno-attribute flag

**Comment by mkruselj** [comment] 2021-04-26 07:21
@phil123456 Did you get Surge to build on RPi in the end? Please report back. I'm tentatively closing this issue, but if you still cannot build on RPi, feel free to reopen it.

**Closed by mkruselj** 2021-04-26 07:21 UTC
Labels: Awaiting User Information, Bug Report

**Comment by hexdump0815** [comment] 2021-05-13 12:31
as the original poster did not respond anymore did not respond: i can confirm that disabling -Werror fixes the problem - it compiles fine then on 32bit arm as well and the resulting  surge is running well ... as the cmake stuff here does not really work well for me (maybe too old cmake on ubuntu 18.04) i just commented out this line: https://github.com/surge-synthesizer/surge/blob/main/CMakeLists.txt#L34

this is how building it works for me in the end: https://github.com/hexdump0815/surge-arm-build/blob/master/readme.txt

best wishes and all the best for this wonderful project - hexdump

**Comment by baconpaul** [comment] 2021-05-13 13:43
Hey great thanks @hexdump0815 and that's good to know!
