### ISSUE TITLE
"Macro" Controls 1-8 don't reset to when double clicked.

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1009] opened 2019-08-09 20:53 UTC
Now that Surge recalls "Control 1-8" settings from it's preset browser, I notice another quirk with the controls. Again not really a bug.... just an odd design decision.

Unlike every other knob in the interface Controls 1-8 do not reset to "0" when double clicked. Might be worth looking at. Seems like maybe that was done on purpose, but not sure why you'd want that.

To my thinking all "unipolar macro controls" should reset all the way to the left when double clicked, and "bipolar macro controls" should reset to the center when double clicked.

**Comment by baconpaul** [comment] 2019-08-09 21:00
That is inconsistent yeah
I would bet the reason for that is the controls are meant to be midi addressable so you want them controlled by the knob. But then why have them be mouse editable at all?

Either you are or you aren’t mouse editable and since you mostly are now being consistent seems smart

Agree?

**Comment by mortfell** [comment] 2019-08-09 21:35
Yea that is my thinking as well. 
Also midi CC messages generally just override the plugin state, so I can't see that interfering with anyone who is using it with midi anyway.

**Comment by baconpaul** [comment] 2019-08-09 21:58
Ageee
When I’m next in the code I’ll take a peek

**Comment by baconpaul** [comment] 2019-08-10 14:47
Just pushed a change that does this. Nightly rebuilding now.

Also: Thanks for the attention to detail. Every time we get a new person starting to give us detailed feedback we find things we hadn't seen before and it makes the synth better. Appreciated!

**Comment by mortfell** [comment] 2019-08-10 19:49
Awesome, no problem! Surge is becoming one of my favourites for sound design, so fast to use efficient, and lots of weird possibilities 

Yeah I've been designing a lot of presets in the last couple weeks, and I like to set Macros for my presets so that people who are less experienced or don't know the synth well have options for ways to quickly tweak the sound when the open it. Will post some here once I have them finished!

**Comment by baconpaul** [comment] 2019-08-10 22:03
Cool. If you end up with a set of presets you like we are happy to put em i. The third party library for 1.6.2

**Comment by mortfell** [comment] 2019-08-12 15:19
Totally want to do this, should be able to get a good set together by then!

Noticed last night the double click thing is now fully working on Mac OS for me, but not on Windows 10. Just double checked it's happening in Reaper, Renoise and Live 10.1, VST2 and VST3.

**Comment by mortfell** [comment] 2019-08-12 15:24
I also meant to mention (I thought I did but seems I forgot to post it)
Controls 1-8 also do not respond too "mouse-wheel" movement, which again is inconsistent with the rest of the sliders, and not desirable behavior in anyway I can think of.

Should that have it's own issue or just live here?

**Comment by baconpaul** [comment] 2019-08-12 15:26
I can just reuse this issue thanks!

**Comment by baconpaul** [comment] 2019-08-12 21:51
OK I've just coded a change to make the control wheel work there also. It's super nice on mac. My guess is it is in a nightly in about 45 minutes.

I tested the double click on windows / bitwig / vst3 and it worked no problem. When the new nightly is up, if you have one which works with mouse wheel and not double click could you let me know the version?

Also the double click only works on the 'bar' section not the 'label' section (just like the drag). Could that be it?

Thanks!

**Comment by mortfell** [comment] 2019-08-13 00:39
Ok yes! It was user error. I install to acustom VST location, and hadn't set the location correctly last time I installed. Sorry about that! Yeah works now on both platforms! This is great.

Its perfect with the trackpad on Mac, the mouse wheel on my windows is very slow however, only really good for fine adjustments. It seems to go the same speed as the other sliders in the interface go when doing the "mousewheel+shift key for fine adjustments" thing.

**Comment by baconpaul** [comment] 2019-08-13 01:40
Ahh it's hard for me to reproduce that - my VM is not great fidelity of trackpad -> mouse wheel virtualization in vm. Easy for me to speed it up with a #if windows tho. Will do so when I next do a push then will close this.

**Comment by baconpaul** [comment] 2019-08-13 02:24
Ahh was easy enough to put in an if. I did it before bed. Will merge the PR tonight so should be good with the next nightly. While I was in there I supported shift-wheel for fine adjustment also.

Look for a new nightly any time after about an hour from now.

**Closed** 2019-08-13 02:25 UTC
Labels: ui problem

**Comment by mortfell** [comment] 2019-08-13 17:47
Works perfectly now awesome
