### ISSUE TITLE
Pitch changes in the Delay FX when tempo changes

### ISSUE THREAD

**Issue by maxxatgit** [surge-synthesizer/surge#2628] opened 2020-09-17 04:36 UTC
First of all, Surge is a great synth! I appreciate the time and effort that the devs put into this project.

When playing sustained notes, or notes with long release time during a tempo change, the pitch changes. Upon testing this, I find it only occurs in some patches. There are too many patches to test them all, but here is what happens in a few of the factory presets:

Category: Leads - Patch: Bitten
 - As tempo decreases it introduces some kind of LFO modulation, you can see the scale changing in the box at the bottom of the screen.

Category: Brass - Patch OB-8 Jump - No Effect
Category: Brass - Patch Plastic Brass - No Effect

Category: Plucks - Patch Clean
 - As tempo decreases pitch goes down. I found this is connected to FX 1. When I set "Send FX 1 Level" to 0, the pitch shift does not happen.

Category: Plucks - Patch CLRKSWRD
 - As tempo decreases pitch goes down. I found this is also connected to FX 1. When I set "Send FX 1 Level" to 0, the pitch shift does not happen.

In both of the above patches , FX 1is a Delay. I would expect delay time to increase if it's synced, but not a pitch shift. That seems like a bug in the Delay FX.

None of the other VST synths do this

* Surge Version: 1.7.0.8fd9e76 x86_64 64-bit Linux
* Plugin type VST3
* Bits 64

1. Setup a tempo change
2. Record/enter some MIDI notes that occur during the tempo change
3. Select a patch
4. Start playback a few seconds before tempo change. When playback gets to tempo change, observe the behavior of different patches.

**Expected behavior**
In the delay FX, I would expect delay time to increase during a tempo change *if it's synced,* but not a pitch shift. 

**Desktop (please complete the following information):**
 - OS: 64-bit Ubuntu 19.10
 - Host Reaper
 - Version 64-bit 6.13

Thanks again!

**Comment by mkruselj** [comment] 2020-09-17 07:25
With delays, you have two choices when changing the delay time - either you get glitches due to lack of interpolation in delay time, or you get pitch shifts which are caused by the interpolated delay times. Changing the pitch is more musical (and in fact is how a lot of analog bucked brigade delays work!). This is not a bug, it's by design.

**Comment by baconpaul** [comment] 2020-09-17 22:06
yeah exactly you can also see this by just playing a note and wiggling around the delay lever. You are basically getting a doppler effect when you change delay time (rather than a discontinuity). So I agree this isn't a bug. It may not be a desired feature but in that case, another delay is probably appropriate. Let me close this, but thanks for the report!

I did a quick test on my mac. The Apple "AU Delay" does a hard reset as does the logic delay designer in feedback mode. So no retune but loads of potentially horrible sounding glitches. Valhalla Delay in tape mode is smooth but repitches much like surge does

**Closed by baconpaul** 2020-09-17 22:06 UTC
Labels: Bug Report

**Comment by mkruselj** [comment] 2020-09-18 12:11
Just some extra info for @baconpaul - NI Replika's "Modern" delay mode actually does change the delay time without any pitching artifacts OR glitches. I have no idea what they're doing there, but there it is.

**Comment by Radder79** [comment] 2020-09-18 12:23
Professional and Expensive effect plugin "timeless" from fabfilter has about the same pitch shift artifacts that surge has.

It's either this, or some glitchy sounding effect.

Nothing strange to keep the programmers busy.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maxxatgit** [comment] 2020-09-19 20:40
Hi everyone,
Sorry for the delayed response... I am able to simply turn the delay off for that particular patch/project. I really appreciate the helpful & knowledgeable feedback!
