### ISSUE TITLE
Review Close/Open Frame Management in all host styles (was Editor doesn't close)

### ISSUE THREAD

**Issue by audioboy77** [surge-synthesizer/surge#1406] opened 2019-12-07 07:40 UTC
**Description**
The window is not closed after closing the host window
Also, unsurprisingly, a crash is caused if the user clicks on any widget in these hanging windows.

**Surge Version**
1.6.4.1 
VST2
32bit

**To Reproduce**
1. Open the plugin in New Sonic Arts Freestyle (demo here: http://www.newsonicarts.com/html/try.php?productid=128534)
2. Close the window
4. See error (hanging window in top corner)

**Expected behavior**
Plugin editor should disappear from view

**Desktop**
Windows 10
New Sonic Arts Freestyle 32bit

**Comment by baconpaul** [comment] 2019-12-07 13:10
Thanks. I’ve never run this daw and haven’t built the 32 bit plugin in the last 6 months, so can’t exactly be sure what it is. First thing I’d try is to grab the DAW on my mac and see if it crashes there too. Any basic instructions on how to use the thing (like how do you even add a surge to the environment) would be appreciated.

**Comment by baconpaul** [comment] 2019-12-07 13:12
Also I wonder if this is related at all to the comment in #504 which I could never reproduce - but I beleive that user was also VST2 32 bit

**Comment by baconpaul** [comment] 2019-12-07 15:03
So wanted an email address which I gave but then wanted to run a rebooting installer with a quarter gig of content, on macOS so I'll pass on that for now.

**Comment by mkruselj** [comment] 2019-12-09 16:34
Usage is pretty simple, you let Freestyle scan your plugins then just drop one onto the grid. It is automatically routed to the output.

Also this is not a 32-bit only issue, happens with 64-bit over here too.

**Comment by baconpaul** [comment] 2019-12-09 18:20
Ok cool and surge crashes in the way oriiginal poster suggested? When I next have a windows vm running I will try again.

Don’t suppose it supports vst3 does it?

**Comment by mkruselj** [comment] 2019-12-09 18:27
It doesn't support VST3 as of yet.

**Comment by baconpaul** [comment] 2019-12-09 18:37
Gotcha thanks 

I’ll try and take a look this week or next like I said. I’m sure it’s something wonky in our ordering of messages and the host ordering

**Comment by baconpaul** [comment] 2019-12-10 22:02
Tagging this 1.6.5 in case debugging it finds a more general bug (as opposed to a host specific one). Not a commitment to fix but definitely a commitment to investigate before we ship the next version.

**Comment by baconpaul** [comment] 2019-12-17 21:38
Installed Freestyle on my windows VM and can't make it recognize surge

Is there some trick other than "put surge in the folder that FreeStyle thinks is a VST2 folder"?

Don't think I'll be fixing this one though. How do I even get a log out of freestyle? Totally inscrutable.

**Comment by mkruselj** [comment] 2019-12-17 21:53
The official version of Freestyle that is downloadable demo doesn't recognize Surge, this was fixed in the latest public beta (which is available in User Area)... maybe James could provide you with NFR for testing?

**Comment by baconpaul** [comment] 2019-12-17 22:09
Happy to - do you know james to ask him?

**Comment by mkruselj** [comment] 2019-12-17 22:12
I wonder if @audioboy77 is him, actually. :)

**Comment by baconpaul** [comment] 2019-12-17 22:15
Well that would be useful.

But right now I’m dead in the water on fixing this so somehow we need to get a person who is a developer and can run freestyle and surge at the same time.

I’d also be happy to take a PR from the team at NewSonicArts if they happen to figure out what’s different. I mean it has to be something in the “::close” area where they are calling differently than every other host we’ve used surge in; so what’s the magic they are doing we are mis-reacting to (or what’s the mistake they are making which we expose, I suppose, but probably more likely to be us)

**Comment by baconpaul** [comment] 2019-12-18 14:34
Alright I'll send this to support at newsonicarts.com also per a request https://www.kvraudio.com/forum/viewtopic.php?f=300&t=534057&p=7611618#p7611618

The problem is freestyle is using ::open and ::close differently than other daws. With the VST2 in Bitwig and Reaper here's the protocol with the VST2

- create track
   -  call ::initialize ::open and ::resume
- show the UI / close the UI 
   -  no interaction with the VST2. The hide and close of the component is handled by the daw
- remove the track
    - call :suspend and then ::close and then ~plugin

To handle that workflow, surge keeps its editor instance in a `std::unique_ptr<SurgeGUIEditor>` so the door actually kills the item. And the GUIEditor destructor cleans up frames and stuff. This pattern is why the VST2 works in every host except FreeStyle

Freestyle does something different. In the course of opening and pulling out a surge you create and destroy 2 surges and run in a third, but that third never gets ::close called.

I put log messages in the open close construct destroy of surge. You can see the hex id of the 'this' and basically the version you are running (in this session the e40 one) never gets close called.

So I think what is happening is

- In other daws when you press X the host is handling the hide of the component
- You are not. But you are also not calling ::close when the X is pressed so there's nothing I can do
- Like other daws you are only calling ::close when destroyed
- but since you are not hiding the component when the 'x' is pressed you end up with the lingering copy attached, basically, to a deleted object

If you'd like I can share a copy of surge which makes the log files or a branch so you can build.

```
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/51/a68b2e40]ctor
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/43]createEffectInstance [a68b2e40]
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/166/a68b2e40]open
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/180/a68b2e40]resume
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/51/a9f8f090]ctor
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/43]createEffectInstance [a9f8f090]
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/166/a9f8f090]open
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/180/a9f8f090]resume
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/149/a68b2e40]suspend
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/175/a68b2e40]close
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/109/a68b2e40]dtor
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/51/a68b2e40]ctor
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/43]createEffectInstance [a68b2e40]
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/166/a68b2e40]open
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/180/a68b2e40]resume
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/149/a9f8f090]suspend
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/175/a9f8f090]close
[c:\users\paul\desktop\surgedev\surge\src\vst2\vst2plugininstance.cpp/109/a9f8f090]dtor
```

**Comment by baconpaul** [comment] 2019-12-18 15:19
Yeah I am sure I’m doing something wrong which other DAWs are compensating for; I just don’t know what it is. 

This is helpful; let me look.

On Dec 18, 2019, at 10:16 AM, James @ New Sonic Arts <james@newsonicarts.com> wrote:

Hi Paul

I think you are mixing up AudioEffect::close, which is not for the editor, thats for closing the entire plugin (and is triggered by effClose from our side host).  For the window, we call effEditClose, which on your side ends up with AEffEditor::close being called (assuming you using hte vst standard classes)

Maybe other DAWs hide the child windows as a safety mechanism and/or workaround for certain plugins, but the purpose effEditClose is to tell the plugin that the 'we' (the host_ is about to close 'our' wrapper window.  You should thus destroy, or hide *your* child window(s).  It doesnt make sense that the host is responsible for hiding *your* window, for the following reasons:

(1) When we call effEditOpen, we create that wrapper window and tell you of its HWND.  You then create your window, and show it in our wrapper window.  We dont create your window, you do (of course) so therefore we dont take responsibility for it.  So taking that logic backwards, on effEditClose we tell you that we are going to close *our* wrapper window, and you inversely hide or destroy your window.

(2) When we call effEditOpen, there is no way in the VST2 protocol to get a handle to your created window.  So therefore, its nothing to do with the host.  In fact, its total legit that you recreate your window, (destroy the current one, create a new one, and re attaching it to our wrapper window).  So given that the protocol doesnt provide access to your window, it makes no sense that we are responsible for hiding it.  Sure, we could enumurate through all sub windows of our wrapper window and hide them...  I guess thats what soem other hosts are doing, but I assume this is only as a fallback to clean up buggy plugins. 

(3) Every other plugin behaves as expected.  Freestyle has been in the market for 3 years and this is the first time we encountered this issue...

(4) plugins can theoretically have more than one window.  For example Kontakt i believe can have undocked windows.  We cant 'detect' these 

(5) What else would the point of effEditClose / AEffEditor::close be, if not to tell you to hide your windows (which we cannot theoretically detect in all cases (see point 4) or even have a handle to (point 2).

So...  seems clear to me that the plugin should hide (or destroy, whatever) it's own window(s) in response to effEditClose / AEffEditor::close

Does that make sense?

best

James

**Comment by baconpaul** [comment] 2019-12-18 15:33
Jame's note was indeed very helpful
I have found the VST2 error.

**Comment by baconpaul** [comment] 2019-12-18 15:42
Oh but my fix now crashes reaper. "Cool".

**Comment by baconpaul** [comment] 2019-12-18 15:54
OK I now have a fix that basically works for VST2, but it makes me want to do some more testing. Sigh - this lifecycle code has never really been reviewed so do that. But I'll sweep that change to nightly before holidays.

**Comment by baconpaul** [comment] 2020-02-18 03:50
Sigh. Turns out this change actually breaks linux bitwig as in #1572 

For now I am backing out for linux, but let me re-open this issue because either the DAW in question here or our frame management is not correct.

**Closed by baconpaul** 2020-02-18 03:50 UTC
Labels: Host related, UI related
