### ISSUE TITLE
Surge doesn’t work as an audio effect in Cakewalk By Bandlab

### ISSUE THREAD

**Issue by fyrebreak** [surge-synthesizer/surge#903] opened 2019-06-09 04:32 UTC
How to reproduce:

- Drag Surge into an effects bin in any track (instrument or audio)
- Set surge’s first oscillator mode to audio input
- There is _no_ audio coming from the entire track

I might be wrong, but I thought I should be able to hear audio through the Surge plugin when I set the oscillator to audio input. So for now I can’t do any modulation of audio (or maybe vocoding) with Surge as it is right now, in this DAW.

**Comment by fyrebreak** [comment] 2019-06-09 04:33
Edit: I’m using the VST2 _fx version of Surge 1.6.0 in Windows

**Comment by baconpaul** [comment] 2019-06-09 13:45
Man we really need to recruit a person who has shipped a vst2 on windows in cakewalk. I know literally zero about that. And it seems the daw which gives us the most problems

That said: let me link to https://github.com/surge-synthesizer/surge/issues/893 also

**Comment by fyrebreak** [comment] 2019-06-09 18:39
Wish I could help, even though I’m just a musician with no knowledge of coding... (•ᴥ•)
Glad you replied though, Paul!

**Comment by baconpaul** [comment] 2019-06-09 20:33
Yeah I will look this summer one day when it is 100 degrees and humid and I'm inside in the AC and I feel like understanding cakewalk. But a user on KVR offered to take our summary of problems to the cakewalk team so that may also help. Thanks for the report!

**Comment by fyrebreak** [comment] 2019-06-15 08:28
No problems... sorry for late reply! I just found another issue to report, so I'll probably open another issue if no one's done it already. Has the user compiled already the list of issues (so far) with Cakewalk anywhere?

**Comment by baconpaul** [comment] 2019-06-15 11:05
I just added a GitHub tag "cakewalk" which I will apply to issues in that DAW when I sweep through issues next. For now it is on this issue and the one you just opened.

**Comment by fyrebreak** [comment] 2019-06-15 11:08
Awesome :) Glad to help

**Comment by mortfell** [comment] 2019-08-08 03:10
> I might be wrong, but I thought I should be able to hear audio through the Surge plugin when I set the oscillator to audio input. So for now I can’t do any modulation of audio (or maybe vocoding) with Surge as it is right now, in this DAW.

Hey @fyrebreak , Just checking, Do you have Surge set too "latch" mode (it's the last selection in the "Polymode" section)? Or are you sending it midi at all? 

In Audio pass thru mode, the "VCA" section of Surge is still in play, so the Amp envelope needs to  be triggered by a midi note in order to pass audio from the Oscillator section. (even though it's in audio pass through mode it still passes through the filter block in the way an Oscillator would).
As an alternative, latch mode will simulate a note being continually pressed.

**Comment by baconpaul** [comment] 2019-08-08 18:49
Linking this to #1005

**Comment by baconpaul** [comment] 2020-02-01 20:42
The 1.6.5 release puts an couple of key sidechain / sideband fixes into the VST3. Can you try this with the VST3 and a current nightly? Or does cakewalk not support VST3?

We know why the VST2 _fx we distribute doesn’t work we are going to be unable to fix it. But with the release this week, we also want to migrate all users to the VST3 anyway where possible.

**Comment by fyrebreak** [comment] 2020-02-07 02:01
Hi all, was away. Thanks for continuous updates on this issue. 

@mortfell I didn’t send in MIDI when I was trying to use it as an audio effect. I also rarely put Surge on Latch. I thought some effects would still work without MIDI input? You might have a point for subjects such as vocoding, etc.

@baconpaul Cakewalk does support VST3, in fact it’s preferred over VST2! I Update sounds good, I’ll be trying it out later. Looking forward to switching to VST3 from VST2. Thanks for working on this.

**Comment by fyrebreak** [comment] 2020-02-07 03:40
This is strange... @mortfell was right. @baconpaul , Surge is finally detecting audio from audio-thru, but only when in Latch mode. Is this functioning as intended? In the default Poly mode it cannot detect any audio.

**Comment by mortfell** [comment] 2020-02-07 07:51
Yeah, Surge is an instrument so it’s default vca gate state is set to “off”. That’s what you want in this case.

It would be possible to create a standalone effect version of Surge, but it would be a lot of extra maintenance work for everyone involved. (Paul did make a vst3 effect rack where you can use all the effects from the fx section of Surge but that is much simpler than Surge and doesn’t have all its modulation capabilities)

I just created a preset with exactly the setting I like for using Surge as effect. I load that when I wanna use it that way.

**Comment by baconpaul** [comment] 2020-02-07 12:11
Alternately don't use latch, and send it midi, and the audio will gate on and off with the envelope for the note you play. That's a really interesting effect too.

But since it is working as intended let me close this!

**Closed by baconpaul** 2020-02-07 12:11 UTC
Labels: Cakewalk, Surge as FX
