### ISSUE TITLE
GUI shrinks when reopening in Cubendo HiDPI mode

### ISSUE THREAD

**Issue by wwwFINKcz** [surge-synthesizer/surge#1460] opened 2020-01-09 05:27 UTC
Hi.. The Vsti doesn't hold its size (even I set it to default like 250%) on HiDPI mode in Nuendo/Cubase. If I close and open the window, the window shrinks.... and again, close open and it is double small and again... until it is supertiny. This problem I have also by IK multimedia VSTis and some VSTs.. other vstis and VSTs  are OK. I know, Cubase still not supports 150% DPI ... but other plugins work normally. Could be resized and doesn't shrink.

Thank you for solving this.

**Comment by baconpaul** [comment] 2020-01-10 02:45
Unfortunately I don't have a way to reproduce this since I don't have an HDPI windows environment. Does it appear the screen shrinks by the HDPI % you are showing? That is, if your HDPI ratio is 150% does it shrink by 75% on each axis each time?

**Comment by baconpaul** [comment] 2020-01-10 02:46
Oh also: Are you using the VST2 or the VST3? The VST3 has some smarter sizing logic in it - so please let us know and try that if you aren't on the VST3.

**Comment by wwwFINKcz** [comment] 2020-01-11 04:15
hello Paul..  Yes, I am using the VST3 version and yes, the ratio shrinks
about that size everytime --- I made a video for you, that you can see this
issue.
https://youtu.be/9B91RsYX19Y

thx.

pá 10. 1. 2020 v 3:45 odesílatel Paul <notifications@github.com> napsal:

**Comment by baconpaul** [comment] 2020-01-11 14:40
Ha! Super clear. 

I’m not quite sure how I would debug this since I don’t think my VM supports HDPI and I don’t think I can run nuendo but let me think about it as we approach 1.6.5.

Do you see this in any other daw on your system? Or just nuendo?

**Comment by wwwFINKcz** [comment] 2020-01-12 02:28
as I already told you, it is a common bug on cubase/nuendo only ... since
.... since ever, because it does not support 150% DPI. That means, that
some non optimised synths have this bug. But is possible to make it work.
Like many other with the same UI engine. They updated it, and it is ok now.
So I hope, you will be able to make this issue disappear soon because I
love your synth.

Music, love, and peace, Petr Fink

so 11. 1. 2020 v 15:40 odesílatel Paul <notifications@github.com> napsal:

**Comment by baconpaul** [comment] 2020-01-12 02:36
Oh yeah sorry you did say that

Well let me see if I can even make nuendo run in my vm this winter and repro! Thanks.

**Comment by Kingston1** [comment] 2020-11-20 19:31
Just popped in to comment that this still reproduces on Cubase 11 Pro. If it's of any use, when opening Surge VST3 editor in Cubase, the error message pops up exactly six times on any open. After this, dragging the window works great. But closing the window, it does not matter what zoom setting I select or what window size there is on close, six error message come.

125% DPI setting on Windows 10 in use. If there is any debug info to provide, I'd be happy to help.

**Comment by wwwFINKcz** [comment] 2020-11-21 06:15
yep.. this issue (with forevershrinking plugins) is still there in Cubase 11pro. Even when the windows Dpi is set to any size (like 150% 200%). I thought, it disappers in the new update, but not :(( Sad.

**Comment by baconpaul** [comment] 2020-11-21 13:11
If I had hardware and software so I could replicate it I might stand a chance but I don’t - I’m a Mac user who just has windows in a vm and then just with reaper and Bitwig - I did however give @Kingston1 some tips on how I would debug it and they have dev experience so maybe they will be able to help?

**Closed** 2020-11-23 10:40 UTC
Labels: Cubase, Path To Zoom, Windows
