### ISSUE TITLE
CTRL+Drag-Copy of AW Point resets parameters to defaults

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#6317] opened 2022-06-26 14:54 UTC
Version: Surge XT 1.1.nightly.7826189
Build: 2022-06-25 @ 15:39:43 on 'WIN-NIPMIESLENS/pipeline' with 'MSVC-19.29.30145.0' using JUCE 6.1.6
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

From the Surge XT Discord bug-reports channel:

To reproduce:

1. Load AW Dynamics/Point into an FX slot and change some of the slider parameters.

2. CTRL-Drag-Copy to another slot...

Notice here that the slider changes are reset to defaults.

**Comment by mkruselj** [comment] 2022-06-26 15:02
Duplicate of #6300

**Closed by mkruselj** 2022-06-26 15:02 UTC
Labels: Bug Report
