### ISSUE TITLE
Surge XT presets

### ISSUE THREAD

**Issue by DTBaker1118** [surge-synthesizer/surge#6900] opened 2023-03-31 03:05 UTC
Surge XT 1.1.2 running in Reaper v.6.78 in Windows 11. Used to work fine, but now presets not working. In Surge XT VST3i (screenshot attached), presets do not appear to be there. In Surge XT CLAPi, presets appear to load onto midi file (CLAPi - 1), but then defaults every time to same preset (CLAPi - 2). Is installation not working? I have tried reinstalling, and get same problem.
![Surge XT VST3i](https://user-images.githubusercontent.com/129475026/229012571-912397e2-711b-4277-b00a-3d4eda7a5c98.jpg)
![Surge XT CLAPi - 1](https://user-images.githubusercontent.com/129475026/229012574-4e0c3257-59fe-450c-a0a7-35fc5d596ef9.jpg)
![Surge XT CLAPi - 2](https://user-images.githubusercontent.com/129475026/229012576-08ec44e8-be4d-441c-98bd-65224ddf1404.jpg)

**Comment by baconpaul** [comment] 2023-03-31 12:20
Can you screen shot the about screen? It will show you the user directory and have that as a hyperlink; if you click that link is the directory valid?

**Comment by DTBaker1118** [comment] 2023-03-31 19:26
Thanks for your reply. As you can see in the attached, I was able to link to the folder from the hyperlink on the About page. But even after directing my DAW to rescan, I still get the preset defaulting to the same preset as before.

**Comment by mkruselj** [comment] 2023-04-01 10:59
We don't see any screenshot attached?

**Comment by DTBaker1118** [comment] 2023-04-01 14:03
Attached, and pasted below as well.

**Comment by mkruselj** [comment] 2023-04-01 14:14
We still don't see it. I don't think e-mail attachments are coming through, you should post it over github's website rather than respond via e-mail, it seems...

**Comment by DTBaker1118** [comment] 2023-04-01 14:52
![Link from About page](https://user-images.githubusercontent.com/129475026/229296434-de26c3c7-f43c-428d-ad2b-4508bb48a8e0.jpg)

did this work?

**Comment by baconpaul** [comment] 2023-04-01 14:57
Yes

You see how the user directory at the bottom of the screen says “something/Onedrive/blah” - I bet that something about that cloud documents setup is making our recurse down the path not work

I have no idea how to test that but I do know some rack users also had a problem with onedrive drives

hmmm…. So how can we do a test I wonder if that’s what is happening

**Comment by mkruselj** [comment] 2023-04-01 15:15
Yes I bet OneDrive is set to only show references to files without having them actually on the hard drive.

Please don't use OneDrive as user data folder. it's bound to produce issues, as you can see.

**Comment by DTBaker1118** [comment] 2023-04-01 15:44
I copied the One Drive folder to a hard drive, and re-directed my DAW to look in the new folder, and restarted and retried Surge. Still no change. Is there a way of redirecting Surge to use the copied folder as a path for user data?

**Comment by baconpaul** [comment] 2023-04-01 16:02
Yeah there’s an opti N in the menus to choose a different user folder. In user data or workflow or something 

it will write one file to the onedrive but it won’t traverse 

it might work - if it doesn’t we will need a code change of some form to look elsewhere

**Comment by DTBaker1118** [comment] 2023-04-01 16:10
![RedirectedPath](https://user-images.githubusercontent.com/129475026/229301902-c989590f-aab3-4d77-b6cc-827ec4c15b60.jpg)

You were right. I was able to redirect the path for the file to the one I copied to the hard drive folder, but nothing in Surge changed.

**Comment by baconpaul** [comment] 2023-04-01 16:14
Huh that’s not what I was expecting - it found the redirect 

If you save a patch does it show up in the e: directory? 

What a mystery

**Comment by DTBaker1118** [comment] 2023-04-01 17:03
I was able to save the patch to the hard drive folder I created. 

When I went to load the patch, it did, in fact, default to the hard drive folder I created. I loaded the patch from that, but still, it did not play that patch, and defaulted once again to the Sub Square preset.

**Comment by baconpaul** [comment] 2023-04-01 17:32
huh i don' understand what would change the patch
you don't have, like, a reaper program change or anything?
I'm really stumped.

**Comment by mkruselj** [comment] 2023-04-01 18:49
Program change wouldn't work with VST3 anyway, it's not that.

Can you post some screenshots of the file layout of the new user data folder you've copied stuff from OneDrive to?

**Comment by DTBaker1118** [comment] 2023-04-01 19:18
I can give you the path. Not sure what screenshots I could give you. 

What I did was link to the One Drive folder from the hyperlink in Surge, then created a folder on a hard drive. In order to maximize space on my laptop's hard drive, I have as much of my music project stuff on a separate hard drive. So I created a folder on that hard drive, and copied everything that was in the One Drive folder to the folder I created on my hard drive. Then I went into CLAPi Surge XT, went to menu, went to Data Folders, then Set Custom User Data Folder, and linked that to my hard drive folder. 

Does that help?

**Comment by DTBaker1118** [comment] 2023-04-02 15:10
![SurgeOptions](https://user-images.githubusercontent.com/129475026/229361694-2d951d1f-7ebb-4e80-a441-83a011b3146a.jpg)

When I create a track in Reaper, I access my plugins by pressing the FX button. I can search "Surge," and when I do, these are the options I get (you can tell I've been using Surge for a while, and I really like it, which makes my current difficulties frustrating). Does this tell you anything?

**Comment by mkruselj** [comment] 2023-04-03 07:39
I meant if you go to the CLAP install folder on your hard drive, not inside Reaper's FX browser.

**Comment by DTBaker1118** [comment] 2023-04-04 21:25
![CLAPfolder](https://user-images.githubusercontent.com/129475026/229926146-ac3c52e4-4218-478d-b269-29a450402e5c.jpg)
Does this tell you anything? Note that the folder itself seems to be empty.

**Comment by baconpaul** [comment] 2023-04-04 21:55
Right remove that SurgeXTData directory and see what happens maybe? It looks like a sort of broken portable install.

I wonder if the hardlink can't work to cloud drives.

**Comment by mkruselj** [comment] 2023-04-04 22:09
Hardlink can def work with cloud drives, provided there are actual files there, rather than reserved files that are only downloaded upon access.

**Comment by DTBaker1118** [comment] 2023-04-04 22:17
I'm not sure I know what "reserved files that are only downloaded upon access" means, I'm afraid. Sorry, but previous incarnations of Surge XT have worked for me before, so I don't know why I can't do what I had previously been able to do. Is it a Windows 11 hiccup? I had originally installed Surge XT on a Windows 10 machine, so not sure if that's an issue. 

And is there a solution?

**Comment by mkruselj** [comment] 2023-04-05 05:13
Well the problem here is that we cannot reproduce your issue, so we dont know what the solution would be. Did you try to remove C:\Users\<your username>\Documents\Surge XT (or better, move that folder somewhere else), then uninstall and reinstall Surge?

**Comment by mkruselj** [comment] 2023-04-05 08:46
> I'm not sure I know what "reserved files that are only downloaded upon access" means,

Go to OneDrive settings, under Sync and backup you have Advanced settings. One of options there is called Files On-Demand. You probably have it enabled. Disable it. Then OneDrive will actually sync the files to your hard drive, physically, instead of only downloading them when you want to open a particular file.

**Comment by baconpaul** [comment] 2023-04-05 12:02
I also wonder if the hard link is a problem 
Perhaps blow away the vst3 and clap surge synth team folder and reinstall and in the last step don’t choose portable 

if that doesn’t work I can add some logging to the scan after we release 1.2 also

this one is tricky

**Comment by mkruselj** [comment] 2023-04-05 12:02
I don't think it's tricky, I just think the files are not actually there on the hard drive because of OneDrive's files on-demand option being enabled.

**Comment by baconpaul** [comment] 2023-04-05 12:10
Oh yeah that would do it!

**Comment by DTBaker1118** [comment] 2023-04-08 01:16
The re-install seems to have worked. 

I will make the appropriate sacrifices to the gods at the appointed hour in the proper graveyard. 

Man, I hope this works. Thanks very much for your patience and your assistance.

**Comment by Andreya-Autumn** [comment] 2023-04-09 08:15
> The re-install seems to have worked.>

Great! Closing this issue then. Feel free to re-open should the problem re-emerge in spite of your mystical efforts. ;)

**Closed by Andreya-Autumn** 2023-04-09 08:15 UTC
Labels: User Support Request, Discussion
