### ISSUE TITLE
Clear invalid modulations on unstream

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4211] opened 2021-03-29 13:47 UTC
Based on #4207, we should simply remove all impossible modulation assignments that could've somehow happened in 1.8 (i.e. modulating Classic osc width then changing to Sine, makes Shape modulatable, which is integer param so it doesn't modulate).

Do this before 1.9 is out, happy days.

**Comment by baconpaul** [comment] 2021-03-31 20:22
ugh this one turns out to be mildly annoying
the problem is when we unstream we have not set up the OSC yet so we don't know the ctrytypes so we don't know if the modulation is valid
will ponder. thought it would be easy but its not.

**Comment by mkruselj** [comment] 2021-04-02 07:39
Maybe a gross idea: when we unstream, we DO know the osc type, though (it's stored in XML, `a_osc1_type` etc.!), so maybe we can use that info to scan ctrltypes and if they are `vt_int` axe any likely modulations?

**Comment by baconpaul** [comment] 2021-04-02 12:58
Yeah so there's a variety of problems with that, including re-implementing all of init_ctrltypes and also not catching all the invalid modulations. So the 'scan to figure out vt_int' is the same as 'make an oscillator'

I think the trick is actually when we do a spawn_osc to make sure all the modulations attached after the spawn are valid. But I want to make sure that doesn't actually clear valid modulations!

**Comment by baconpaul** [comment] 2021-04-02 13:55
Anyway so the answer is to check modulations onto osc and fx are valid at the end of SurgePatch::update_controls so I'll do that now.

**Comment by baconpaul** [comment] 2021-04-02 14:12
Nope that's wrong. We need to check it at the end of loadRaw - update_controls is too early and we don't always have a synth instance then.

**Comment by baconpaul** [comment] 2021-04-02 14:21
OK this is too hard.

I'm pushing it out of 1.9. I may close it as a "wont fix".

The reason it is hard is

Once we are fully set up we can't tell if we are unstreaming
When we are upstreaming we are not fully set up enough to check valid modulation

Basically we need to find the spot *after* all the init ctrytypes but only when we are streaming

ugh - it is lifecycle hell.

If you saved an invalid patch with 1.8 or earlier, fix it is the answer here. Not worth the risk for this edge case now. May be not worth it ever

**Comment by mkruselj** [comment] 2021-04-02 16:31
I guess another possible solution is to just make integer params modulatable :grin:

**Comment by baconpaul** [comment] 2021-04-02 17:26
Indeed! But this still doesn't mean that other invalid modulations in the file (like vlfo mod -> scene param) couldn't be in the XML.

**Comment by mkruselj** [comment] 2021-04-06 12:23
![image](https://user-images.githubusercontent.com/2393720/113710038-7c2d0580-96e3-11eb-9a95-6eee353f7782.png)

Here's how an invalid modulation looks in the patch XML. So the solution is to, since at parse time we know the parameters and their types, to drop all `<modrouting>` entries for `vt_int` parameters!

**Closed** 2021-04-06 13:00 UTC
Labels: Feature Request, UX
