### ISSUE TITLE
Stuck on Super Oscillator mode in Cakewalk, also unable to add any effects

### ISSUE THREAD

**Issue by fyrebreak** [surge-synthesizer/surge#2400] opened 2020-07-30 14:44 UTC
**Describe the bug**
On Cakewalk by Bandlab ONLY (plugin functioning in LMMS, etc.), functions such as changing oscillator mode, and adding effects to the instrument cannot be done. Instead of a UI change. all that is observed is the same appearance the plugin had at init. config.

* Surge Version: 1.7.0.8fd9e67, latest stable build
* Plugin type (VST2, 3 or AU): VST3
* Bits (32/64): 64 bit

**To Reproduce Oscillator Error:**
1. Open Cakewalk by Bandlab (Early Access build, 2020.07)
2. Open Surge as an instrument
3. Attempt to change oscillator mode from Classic to other modes, like Audio Input or Wavetable
4. Observe that nothing happens

**Expected behavior**
The oscillator sector on the left should change from Classic to Wavetable, and you should not be stuck on Classic oscillator mode.

**To Reproduce Effects Error:**
1. Open Cakewalk by Bandlab (Early Access build, 2020.07)
2. Open Surge as an instrument
3. Attempt to add effects such as reverb, flanger, anything into effects slots
4. Observe that nothing happens

**Expected behavior**
Effects modules should display that respective different effects have been inserted, and you should not still see a blank effects sector with no effects inserted.

**Screenshots**
![image](https://user-images.githubusercontent.com/33426270/88936635-afe2a080-d2b5-11ea-9fd7-aed438ac5915.png)
^The two modules which I have found errors with so far.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: Cakewalk by Bandlab
 - Version: 2020.07, build 086, 64 bit

**Additional context**
I understand there aren't many Cakewalk users, and Cakewalk somehow creates its own array of errors with VST plugins that other hosts don't. Since it's the DAW that I turn to as my current default, I do hope you'll pay some attention to this.

**Comment by baconpaul** [comment] 2020-07-30 15:43
Remind me is cakewalk free?

**Comment by fyrebreak** [comment] 2020-07-30 15:44
It is yea

**Comment by baconpaul** [comment] 2020-07-30 16:41
<img width="274" alt="Screen Shot 2020-07-30 at 12 39 36 PM" src="https://user-images.githubusercontent.com/13387561/88949884-dc6ccd00-d261-11ea-987a-c168b2dd810d.png">

So I downloaded this version of cakewalk and surge 1.7.0 seems to work fine - all the menus swapped FX and oscillators no problem. (I'm on the nightly but that's super close to the release). How do I download that preview version? Or does it work for you if you use that version? My VM is windows 10 64 bit.

**Comment by fyrebreak** [comment] 2020-07-31 00:54
https://discuss.cakewalk.com/index.php?/topic/17619-202007-early-access/ Here it is. I didn't get to try Surge before I installed the Early Access build of Cakewalk, so I can't answer. Your VM seems to be using the correct OS.

**Comment by mkruselj** [comment] 2020-12-23 16:58
Issue caused by audio engine not running. As soon as audio engine is running, everything is fine. Surge requires audio engine to run when setting parameters through the UI. So, closing the issue as it's not a bug in the end.

However we do need to improve UX for audio engine unavailable.

**Closed by mkruselj** 2020-12-23 16:58 UTC
Labels: Bug Report, Cakewalk, Host Automation
