### ISSUE TITLE
XT Standalone Crash when unmute Input

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4581] opened 2021-05-22 16:05 UTC
Linux 64Bit
9ce88da8

-Click Options/Reset to default state (crucial step)
-In Audio/Midi Settings uncheck "Mute Audio Input"
-crash
[XT_Standalone_Crash.txt](https://github.com/surge-synthesizer/surge/files/6526756/XT_Standalone_Crash.txt)

**Comment by baconpaul** [comment] 2021-05-22 16:09
Oooh this one looks a bit trickier - from the stack it looks like the reset-to-default (which recreates an instance) is leaving a pointer to the old instance around somehow. Thank you.

**Comment by baconpaul** [comment] 2021-05-23 16:20
Totally reproducible in macOS also at head

**Comment by baconpaul** [comment] 2021-05-23 19:39
oh huh interestingly SFX does the same
I wonder if this is a juce bug...

**Comment by baconpaul** [comment] 2021-05-23 19:45
Huh yeah if I add an input to tuningWorkbenchSynth it also explodes in the same way. 

So cool. not a surge bug per se.

**Comment by baconpaul** [comment] 2021-05-23 19:49
oh and if i go juce 6.0.7 -> juce 6.0.8 it goes away with TWS

**Comment by baconpaul** [comment] 2021-05-23 20:00
but upgrading surge to 6.0.8 it still breaks.

Hmm. Tricky. May need to hop into juce forum for this.

**Comment by mynameismuhl** [comment] 2021-05-25 12:29
lldb in this case gives one more bit of info
[XT_Standalone_Crash_lldb.txt](https://github.com/surge-synthesizer/surge/files/6539212/XT_Standalone_Crash_lldb.txt)
and points here:
https://github.com/juce-framework/JUCE/blob/99112cf71f0cc3aafa4622b62cf81f2b7df38f0b/modules/juce_audio_plugin_client/Standalone/juce_StandaloneFilterWindow.h#L832

Another observation:
If I toggle Mute Input (without resetting)
the window needs to resize because of the disappearance/reappearance of the additional info bar.
If I unmute/mute it does not resize/redraw as long as the curser hovers over the checkbox.
Only after I move the mouse it resizes corectly.

**Comment by baconpaul** [comment] 2021-07-15 11:48
This is definitely a juce bug. Reported it over in their forum. 

https://forum.juce.com/t/reliable-crash-in-standalone/46953

**Comment by baconpaul** [comment] 2021-07-15 15:15
https://github.com/juce-framework/JUCE/commit/e467473157f6051b8aac19da3626e189de53eb4b fixes this in the JUCE develop branch, which will be 6.1 in the next 3-4 weeks; and we will upgrade to it then.

So closing this (even though it will still crash at head). Thanks!

**Closed by baconpaul** 2021-07-15 15:15 UTC
Labels: Bug Report, Rebuild with JUCE
