### ISSUE TITLE
Patch reset on Reaper

### ISSUE THREAD

**Issue by codepressor** [surge-synthesizer/surge#6173] opened 2022-05-17 09:52 UTC
I have a project on Reaper where I prepared 20 tracks, each one with a SurgeXT instance, a different patch and some effects.
I created these tracks one by one, duplicating the current track to the next.

From a point where I automated the waveshaper gain on a track, all the next tracks got this automation too, by the duplicating process.
I realized this and deleted the automation lanes from these tracks.

I've only noticed the problem after saving the project and opening it again, but not really sure when it started.
SurgeXT on most of the tracks was resetted to the default patch. All other project items (VST fx, etc) where fine.

Not sure what really happened, I mentioned the automation duplicating and deleting process because I think that the resetted patches where on that tracks, but can't be absolutely sure because I had reordered the tracks in the meantime.

I hope this helps in finding and solving a bug on this amazing synth (if it is a synth problem), for sure was a bummer event for me :P

Thanks

**Comment by baconpaul** [comment] 2022-05-17 10:21
Can you share the version from the about screen? I did a fix I think for this problem a day or two ago. 

I’m sorry yu lost your patches.

**Comment by codepressor** [comment] 2022-05-17 10:26
Thanks for the quick reply!

Can't share the about screen now, but I can see that I'm running version 1.0.0 (from the last downloaded installer name)

**Comment by baconpaul** [comment] 2022-05-17 10:35
Oh interesting! 

And what’s your so? Thanks

**Comment by codepressor** [comment] 2022-05-17 10:37
Windows 10 + Reaper (updated version) + Steinberg UR22 mkII audio interface

**Comment by mkruselj** [comment] 2022-05-17 11:13
Please try the latest nightly and see if it happens again or not!

**Comment by codepressor** [comment] 2022-05-17 11:15
Thanks, will do

**Comment by codepressor** [comment] 2022-05-17 17:06
hey, tried to reproduce the error in a test project with no result, then tried on the main project and still can't reproduce it using version 1.0.0

I'll let you know if it happens again and try to capture the actions that lead to it better, and then try to do the same with the latest nightly build

thanks!

**Comment by codepressor** [comment] 2022-05-17 17:45
I managed to reproduce it with v1.0.0, lost the patch association again. 
I've installed the nightly version, but lost my favourite patches list... 
Is there any way I can recover it? If you prefer I can create a new issue just for that.

Thanks

**Comment by codepressor** [comment] 2022-05-17 21:16
with the latest nightly it happened again

**Comment by baconpaul** [comment] 2022-05-17 21:21
Darn

so do you mind sharing your rpp file?

**Comment by baconpaul** [comment] 2022-05-17 21:22
Also your favorites list should still be there!? That’s really odd and should indeed be a separate issue.

**Comment by baconpaul** [comment] 2022-05-17 21:28
Your favorites are still there, by the way, in the database. I think the problem is because we have corrected the windows portable install so the path to items has changed and so they don't show. But I checked the code and run 1.0 vs nightly here and saw the db is untouched.

to get them to show up will require a code change. I'll open an issue for that. but if you re-installe 1.0.1 they will return.

**Comment by baconpaul** [comment] 2022-05-17 21:32
#6177 explains the favorite problem. I'll try to fix *that* this week

The loading problem is more concerning. If you would share your rpp file it would be rather helpful! If not a sort of description of it would also be useful. Is it really just 30 tracks and you load em up? Do you use wavetables a lot? etc...

**Comment by baconpaul** [comment] 2022-05-17 21:50
Oh and hey that favorites problem was super easy to fix! I have a PR in and the next nightly will solve it for you, so either go back to 1.0.1 or forward to the future and your favorites are back (but the future doesn't arrive for a couple of hours while our builds run).

Thanks!

**Comment by codepressor** [comment] 2022-05-17 23:26
Hey, thanks for the help! Attached is my RPP file
[energy-body-3-design.zip](https://github.com/surge-synthesizer/surge/files/8712122/energy-body-3-design.zip)
.

This time I reselected som patches in some instances, started scrolling patches and favorite them in one of the instances and, when I checked one of the tracks that should be with a new patch, it was with the default patch.
Checked others that I had changed the path and the same.
Never closed the project but saved it a few times.
I hope it helps!

I'll check the new nightly whenever it is available

**Comment by baconpaul** [comment] 2022-05-17 23:37
Very useful thank you 

i have some time to look tomorrow and Thursday morning and will report back here

appreciate the help and patience

**Comment by baconpaul** [comment] 2022-05-17 23:37
Oh and @mkruselj if you could give it a whirl on your side also it would be great to know if you see same

**Comment by mkruselj** [comment] 2022-05-18 09:28
Yeah not sure, I can't seem to be able to trigger it over here.

**Comment by baconpaul** [comment] 2022-05-18 11:21
Does reaper have different sandbox modes? Or does it have a mode like suspend on idle?

**Comment by mkruselj** [comment] 2022-05-18 11:35
Yeah you can run plugins in process, separate process per plugin, separate process for all plugins. I'm not using that for Surge tho.

Suspended processing can happen on muted and/on unarmed tracks, depending on certain settings in Reaper.

**Comment by codepressor** [comment] 2022-05-18 11:46
In my Reaper settings I suspend processing when a track is muted, and I had a lot of tracks muted when the problem happened, if it helps

**Comment by baconpaul** [comment] 2022-05-18 11:56
yes very much thank you

@mkruselj if you can show me how to set that up in discord i bet i can get this today. it matches my theory of thread contention when suspended.

**Comment by baconpaul** [comment] 2022-05-18 17:06
OK here's what it was, if curious

When we load a patch from binary we want to load it on the audio thread but if the audio thread isn't running we load it outside the audio thread. I thought that was racing with the init patch, but it wasn't

*but* in `prepareToPlay` we set our sample rate and activate audio processing.

Reaper, for a muted track you load, has the following call path into a VST3

- prepareToPlay
- setStateInformation
- never call ::processBlock

but this means that the prepareToPlay says audio is active, so setStateInformation just pushes the info the the audio thread to load, but there is no audio thread, so it never loads.

This is why if you load and unmute you get your patch.

But if you never unmute and save again, the surge will stream the init patch, blowing away your patch

My fix was really simple. Don't have prepareToPlay set audio processing true. Just have process block set it true.

**Comment by codepressor** [comment] 2022-05-18 17:09
Great news, thanks for the effort and for the quick fix!
Will wait for the next nightly

**Comment by baconpaul** [comment] 2022-05-18 19:05
Nightly is up with this change in place! Please let us know if it works. And thanks for all the help!

**Comment by codepressor** [comment] 2022-05-20 14:55
Worked on my track for 2 days, tried to force the error, but everything seems fine with the last nightly.
Thanks again for the help!

**Comment by baconpaul** [comment] 2022-05-20 15:08
Awesome. I’ll close this. Will wait to hear a bit more from ontrackp before closing the logic one but I think it is the same problem

**Comment by baconpaul** [comment] 2022-05-20 15:08
And thanks again for all the help! Good bug reports make good software!

**Closed by baconpaul** 2022-05-20 15:08 UTC
Labels: Bug Report, Resolved
