### ISSUE TITLE
1440x877 cannot be resized higher than 135% - not even 145%.

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#477] opened 2019-02-03 10:19 UTC
Overall feels like Zoom could be a bit more dangerous, and maybe a bit more precise:

When resizing to 150%

`You attempted to resize Surge to a size larger than your screen. Your screen is 1440x877 and your zoom of 150% would make your Surge 1356x-813`

When resizing from 135% to 145%..

`You attempted to resize Surge to a size larger than your screen. Your screen is 1440x877 and your zoom of 145% would make your Surge 1310.8x-785.9 - Retaining current zoom of 135%.`

**Comment by baconpaul** [comment] 2019-02-03 11:45
Isn't this a duplicate of #457?

**Comment by baconpaul** [comment] 2019-02-03 11:47
I mean#433

**Comment by baconpaul** [comment] 2019-02-03 11:47
#433

**Comment by esaruoho** [comment] 2019-02-03 11:48
closed and moved convoto #433

**Closed** 2019-02-03 11:48 UTC
Labels: path to zoom
