### ISSUE TITLE
MSEG should not retrigger when in Legato mode

### ISSUE THREAD

**Issue by h-v-b** [surge-synthesizer/surge#2987] opened 2020-10-27 21:28 UTC
**Is your feature request related to a problem? Please describe.**
In legato mode, the MSEG currently retriggers on ever keypress. 

**Describe the solution you'd like:**
The expected behaviour, when legato is on, would be possible to have it only trigger on the the first note On

**Comment by mkruselj** [comment] 2020-10-27 21:38
Tested, works as intended actually. So closing this one :)

**Closed by mkruselj** 2020-10-27 21:38 UTC
