### ISSUE TITLE
Skin Objects

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2763] opened 2020-10-02 00:39 UTC
Have the skin *data* represented in C++ objects for defaults. 

This will just make everything else so much less clumsy.

Only two things left to close this are

- [ ] Tune button blinkyblink and
- [ ] Disable FX doesn't disable effect panel

**Comment by baconpaul** [comment] 2020-10-07 19:13
With #2799 we have most of this done but a few things left on my list

- [ ] Groups for mixer, LFO Rate, LFO Env in the C++
- [ ] Tutorials written and tutorials -> webdoc
- [ ] kNoPopup; kSemiTone
- [ ] bugs glorious bugs

**Comment by Jacky-Ligon** [comment] 2020-10-07 21:10
**Surge-NIGHTLY-2020-10-07-59db47b | Windows 10, x64, VST3i, Reaper**

Sticking modulation source controls have returned in this build.

To reproduce:
1. Pull down Mixer Channel 1 to -inf.
2. Assign ENV1 to Mixer Channel 1 and try to move the slide upward to set the modulation range.

Observe here that the Mixer channel slider is stuck and cannot be moved upward from -inf to set the modulation range.

**Comment by K0rrid0r** [comment] 2020-10-07 21:17
hash 59db47b

![215](https://user-images.githubusercontent.com/56724286/95388345-713f1700-08f2-11eb-9af0-68b862c813b5.gif)

MPE 
Tune
Zoom

now looks like this.

![216](https://user-images.githubusercontent.com/56724286/95388725-0a6e2d80-08f3-11eb-871d-cb4a7e9d2257.gif)

clicking on FM depth or Filter config makes a crash.

![217](https://user-images.githubusercontent.com/56724286/95388821-2e317380-08f3-11eb-92e8-15bc4f2c7b99.gif)

On UI rebuild buttons Tune blinks once.

**Comment by Jacky-Ligon** [comment] 2020-10-07 21:20
@baconpaul

**Surge-NIGHTLY-2020-10-07-59db47b | Windows 10, x64, VST3i, Reaper**

FYI: The above detailed issues about controls getting stuck when making modulation assignments, seems to extend more broadly across the UI. 

For example, the same behavior can be observed when attempting to assign an LFO to Filter Cutoff Frequency.

**Comment by K0rrid0r** [comment] 2020-10-07 21:23
![218](https://user-images.githubusercontent.com/56724286/95389428-18707e00-08f4-11eb-87c6-aaccf6718dff.gif)

having problems with the Menu not appearing anymore when doing certain things.

**Comment by baconpaul** [comment] 2020-10-07 21:25
OK!
Well you change 10% of the codebase in a single commit and you will get bugs.

Thank you for these reports. They are top of my stack.

**Comment by baconpaul** [comment] 2020-10-07 21:34
OK both @K0rrid0r crash and @Jacky-Ligon stuck modulation are the same thing and have a 4 character fix. I removed one too many lines of code when cleaning up. Pushing now.

**Comment by K0rrid0r** [comment] 2020-10-07 21:50
![219](https://user-images.githubusercontent.com/56724286/95391759-e4975780-08f7-11eb-9f1a-e3e3a5f79acf.gif)

this Menu not appearing bug is wierd. clicking outside it will not make it appear anymore until clicking it several times, but once it appears again it will always appear.

**Comment by VincyZed** [comment] 2020-10-07 22:15
@surge-synthesizer/surge-test-team Can reproduce on my side as well.

**Comment by VincyZed** [comment] 2020-10-07 22:19
There is still the weird ghost hover bugs as well. Here for instance I am right-clicking on F1 Keytrack amount, and it highlights S-LFO 5.: 
![image](https://user-images.githubusercontent.com/50145178/95393982-8784ad00-08c9-11eb-9cb2-f81a799ac0a2.png)

**Comment by Jacky-Ligon** [comment] 2020-10-07 22:24
@baconpaul 

Confirming that stuck controls are fixed in: **Surge-NIGHTLY-2020-10-07-21e80ce, Win-10, VST3i**...

Will continue to test and report any further findings.

**Comment by baconpaul** [comment] 2020-10-07 22:55
Excellent. And sorry! I tested that a million times, then did my final cleanup and didn't re-test rigorously :(

**Comment by baconpaul** [comment] 2020-10-07 22:55
> this Menu not appearing bug is wierd. clicking outside it will not make it appear anymore until clicking it several times, but once it appears again it will always appear.

Oh I know exactly what that is. Stay tuned.

**Comment by K0rrid0r** [comment] 2020-10-07 22:57
@VincyZed 

I dont get that "F1 Keytrack amount, and it highlights S-LFO" bug here, but im on VST2 32 bit

**Comment by VincyZed** [comment] 2020-10-07 23:04
@K0rrid0r Right, might be related to VST format and / or zoom too...

**Comment by K0rrid0r** [comment] 2020-10-07 23:07
i just tried VST3, not there either. what zoom level you saw that on?

**Comment by K0rrid0r** [comment] 2020-10-07 23:11
oh! i do get it, but on "Lowest Key" instead

![222](https://user-images.githubusercontent.com/56724286/95397281-1bbf3600-0903-11eb-8c69-626f914d84de.gif)

Zoom level 125%

**Comment by K0rrid0r** [comment] 2020-10-07 23:17
![223](https://user-images.githubusercontent.com/56724286/95397650-0c8cb800-0904-11eb-9e88-9c942cadb5b0.gif)

ha! look at this!

**Comment by baconpaul** [comment] 2020-10-07 23:18
#2804 fixes the menu bug

That hover bug is clear as day. It must be VSTGUI ignoring a transform on windows.

**Comment by baconpaul** [comment] 2020-10-07 23:19
Mac doesn't do it, which makes it even more likely that there is a platform-dependent lack of a transform in the gui layer.

I don't think this is new with my changes though is it?

**Comment by K0rrid0r** [comment] 2020-10-07 23:21
@baconpaul it probably isint. I have never noticed this though

**Comment by baconpaul** [comment] 2020-10-08 00:35
<img width="510" alt="Screen Shot 2020-10-07 at 8 05 12 PM" src="https://user-images.githubusercontent.com/13387561/95401976-99238000-08dc-11eb-88d6-0673669ca27d.png">

The fake hovers' not skin objects but here's the stack when it occurs

**Comment by baconpaul** [comment] 2020-10-08 00:36
Oh an @K0rrid0r i think maybe you didn't notice it because the hover colors weren't super clear until a few recent fixes (new colors and no more aliased draws on the CMS). Maybe?

**Comment by VincyZed** [comment] 2020-10-08 03:21
Yeah probably. Sorry if I mentioned this on the wrong issue, since it's not related to the recent changes..

**Comment by baconpaul** [comment] 2020-10-08 03:34
No need to apologize! Bet that stack lets me get it

**Comment by Jacky-Ligon** [comment] 2020-10-08 10:56
@baconpaul **Surge-NIGHTLY-2020-10-08-dc4fbac | Win-10, x64, VST3i, Reaper**

Adding some information to @K0rrid0r 's screenshot above from a previous build...

- The **MPE**, **Tune** and **Zoom** buttons appear to use a different, regular (non-bolded) font.

- Labels for all are a few pixels too high.

- The **Zoom** button label is justified to the right.

**Comment by baconpaul** [comment] 2020-10-08 11:01
Yeah sorry I rewrote that component and am using placeholder graphics right now. It’s an easy fix once we get the svgs. Thanks!!


Also about screen has version copy now don’t know if you saw 👍

**Comment by Jacky-Ligon** [comment] 2020-10-08 11:05
Thanks...

Have always pasted it from the installer name before, but...

Version 1.8.nightly.dc4fbac (Intel 64-bit Windows VST3 in REAPER. Built 2020-10-08 at 00:48:02 on pipeline host 'fv-az68'

**Comment by baconpaul** [comment] 2020-10-08 12:48
Yes I noticed you had some mechanism to do uniform version reporting (which I *really* appreciate). I just wanted to let you know it got potentially easier (or: that it didn't and you had something cleverer we should put in the code :) )

Anyway placeholder graphics getting replaced in next nightly along with undoing slider swap

**Comment by K0rrid0r** [comment] 2020-10-08 13:07
So the only thin left i can see now after this big change is that MPE lights up automatically when surge is launched, is that correct?

and that "Tune" blinks on every UI rebuild action.

![224](https://user-images.githubusercontent.com/56724286/95462603-01736f80-0978-11eb-860c-9d1f39b421f8.gif)

**Comment by K0rrid0r** [comment] 2020-10-08 13:24
![225](https://user-images.githubusercontent.com/56724286/95464528-57491700-097a-11eb-9e10-d8f598ee959f.gif)

oh and also a few missing pixels on the Bright button

**Comment by Jacky-Ligon** [comment] 2020-10-08 15:09
@baconpaul 
**Version 1.8.nightly.4fedfb2 (Intel 64-bit Windows VST3 in REAPER. Built 2020-10-08 at 13:01:10 on pipeline host 'WIN-50SOA1GMF8B')**

Orange color values for MPE, Tune and Zoom differ from other elements:

![image](https://user-images.githubusercontent.com/66483816/95477828-c3198880-0956-11eb-810d-bef0e3d41fd2.png)

**Comment by mkruselj** [comment] 2020-10-08 15:35
Yes the dark skin needs to be updated for those buttons, I am aware.

**Comment by baconpaul** [comment] 2020-10-08 16:55
Yeah the MPE button is not reflecting the internal state correctly; thanks @K0rrid0r I will look! As to tune blinking I have an idea. Sticking both on my todo.

**Comment by mkruselj** [comment] 2020-10-10 14:32
@baconpaul FX bypass button doesn't update FX grid picture states now.

**Closed** 2020-10-13 21:33 UTC
Labels: Skinning Engine
