### ISSUE TITLE
Dual button switches to chan split when draging sliders but then switch back, VST2

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#3157] opened 2020-11-15 05:20 UTC
**Bug Description:**
open surge
put surge in dual mode on both scenes
touch any slider and dual will switch to chan split
switch to scene B
touch any slider and dual will switch to chan split
switch to scene A and chan split has now moved back to dual
touch any slider and dual will switch to chan split
switch to scene B and chan split has now moved back to dual

![66666](https://user-images.githubusercontent.com/56724286/99173776-a8cb8b00-270a-11eb-8fba-47b54faf7848.gif)

**Surge Version**
Surge Synthesizer
Version:	1.8.HEAD.6957460a
Build Info:	Built on 2020-11-14 at 23:56:20, using local host 'KORRIDOR'
System:	Intel CPU, Windows VST2 (unsupported), 32-bit
Plugin Host:	Image-Line Fruity Wrapper

**Comment by mkruselj** [comment] 2020-11-15 10:10
I bet this is the same thing as #3096!

**Comment by baconpaul** [comment] 2020-11-15 13:29
Maybe but I think it is more likely the fact that that switch is not ordered in display same as value

Does it happen in the vst3?

**Comment by K0rrid0r** [comment] 2020-11-16 01:56
yeah hmm forgot to check the vst3 when i wrote this issue. it behaves differently.

![66666 4444](https://user-images.githubusercontent.com/56724286/99204850-2e0c7980-27b7-11eb-8d4c-0c63edfcf656.gif)

need to click chan split to even reach dual
then click anything and the button highlight will switch back to chan split

**Comment by K0rrid0r** [comment] 2020-11-16 03:15
Interesting, dual will only switch to chan split if i move a slider in a certain speed

![dual switch in a certain speed](https://user-images.githubusercontent.com/56724286/99208965-4930b680-27c2-11eb-9fba-f288b6dc11c2.gif)
slow

![dual switch in a certain speed 2](https://user-images.githubusercontent.com/56724286/99208985-5057c480-27c2-11eb-8df6-0020c0e9d3b5.gif)
fast

**Comment by K0rrid0r** [comment] 2020-11-16 03:16
> Maybe but I think it is more likely the fact that that switch is not ordered in display same as value
> 
> Does it happen in the vst3?

vst3 is behaving in a different way, but will make a new issue for that one

**Comment by baconpaul** [comment] 2020-11-22 00:53
OK I think 1085e8c fixes this but I couldn't reproduce exactly what you saw (but could do something different which I think was the same bug in mac reaper). And should fix it for VST2 and VST3. Can you check @K0rrid0r and if it is fixed we can close this.

**Comment by baconpaul** [comment] 2020-11-22 13:16
Confirmed above fixes the problem at hand.

**Closed by baconpaul** 2020-11-22 13:16 UTC
Labels: Bug Report
