### ISSUE TITLE
Incorrect frequencies assigned for 31edo2 tuning and subset keyboard mapping

### ISSUE THREAD

**Issue by rcook** [surge-synthesizer/surge#7822] opened 2024-10-07 02:22 UTC
**Bug Description:**
On importing a custom microtuning and keyboard mapping (attached as 31edo2.scl and 31edo2-subset.kbm) some keys have the incorrect mapped frequency. Most notably C4 shows up as 400 Hz which is a discontinuity compared to the keys either side of it. According to my calculations this key should be mapped to 200 Hz.

**Surge XT Version**
* Version: 1.3.2.f5bd0e1
* Plugin Type: Standalone
* Bitness: 64-bit

**Reproduction Steps:**
Steps to reproduce the behaviour:
1. Click on _Menu_
2. Go to _Tuning_ | _Load .scl tuning..._
3. Select `31edo2.scl` ([31edo2.scl.txt](https://github.com/user-attachments/files/17271948/31edo2.scl.txt))
4. Click on _Menu_
5. Go to _Tuning_ | _Load .kbm keyboard mapping..._
6. Select `31edo2-subset.scl` ([31edo2-subset.kbm.txt](https://github.com/user-attachments/files/17271950/31edo2-subset.kbm.txt))
7. Click on _Menu_
8. Go to _Tuning_ | _Open tuning editor..._

**Expected Behaviour:**
C4 should be mapped to 200 Hz. Here (
[surge-tuning-table.html.txt](https://github.com/user-attachments/files/17272004/surge-tuning-table.html.txt)) is the full tuning table exported as HTML. It's also possible that other mappings are incorrect but I have not exhaustively checked them. This ([scala-frequencies.txt](https://github.com/user-attachments/files/17272523/scala-frequencies.txt)) shows the frequencies generated by Scala for this scale and keyboard mapping.

**Screenshots:**
![Capture](https://github.com/user-attachments/assets/a201024c-6493-45f0-9915-3e32ee3004de)

If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 * OS: Windows 10
 * Host: Standalone

**Comment by baconpaul** [comment] 2024-10-07 10:47
Well I think the reason note 60 shows as 400 is because the kbm says note 60 should be 400. The thing I’m not sure of is why note 61 is then based from the octave below. I’ll take a look though 

if I had to guess it was the kbm note 0 interacting with the tuning center and causing an octave wrap back and the tuning center winning on just that note

**Comment by baconpaul** [comment] 2024-10-07 10:49
Yeah comparing with the scala that’s definitely it. Surge note 61 is scala note 49 so I have an extra octave wrap somewhere - only note 400 is correct the rest are off by a turn

**Comment by baconpaul** [comment] 2024-10-07 13:31
OK I've found the bug but it will take me a bit of time today to add it to our regtest suite and stage it into the nightly. But the bug has a clear workaround in the 1.3 family.

Basically the problem is if your keyboard mapping is (1) non-uniform and (2) doesn't span the tuning note then we have an off-by-one octave problem.

So your original KBM has the tuning note of 60. But the scale mapping starts at note 69. So you are mapping the 12 notes from 69 -> 81 with the tuning center at 60. That gets the 60 right but gets everything else off by an octave. (I have a fix for this now).

If instead you start your mapping at note 57 (so you are mapping 57->69) then the mapping spans the tuning center of 60 and we will get the right frequencies.

Anyway so its a real bug but an easy one to work around in the 1.3 family and we can get a fix staged to the 1.4 family and the nightlies today.

Thanks for the good bug report.

**Comment by baconpaul** [comment] 2024-10-07 13:49
Ahh bummer my fix breaks another one of our regtests. OK this one will take a while.

**Comment by baconpaul** [comment] 2024-10-07 14:10
OK got it. Fix to the nightly should be there by lunchtime. I also added your example to our test suite and fixed up another test or two which were under-testing the feature. Thanks for the excellent bug report.

We don't know when we will ship 1.4 and you may not want to run a nightly. In the interim, like I said, just make sure your mapping spans your tone center.

**Closed** 2024-10-07 14:19 UTC
Labels: Tuning, Bug Report

**Comment by rcook** [comment] 2024-10-07 16:01
Thanks @baconpaul!
