### ISSUE TITLE
loud dc burst over right channel 

### ISSUE THREAD

**Issue by gentleclockdivider** [surge-synthesizer/surge#790] opened 2019-03-26 12:10 UTC
A loud click , plop  , dc offset ... appears over the right channel .
Mostly happens when playing some notes in fast succession , difficult to replicate the bug

**Comment by esaruoho** [comment] 2019-03-26 12:28
duplicate of #699, #698, #662, #753, #660

**Closed** 2019-04-01 16:29 UTC
Labels: clicks n pops
