### ISSUE TITLE
My patch suddenly went completely silent

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge#4024] opened 2021-03-04 12:05 UTC
**Bug Description:**
Unexpectedly while I've been tweaking my patch it stopped making any sound what so ever.
At first it was still producing some inaudible (but visible on the level meter) sounds, but after a short while nothing was left.
Even when I switch to Scene B (that was unused before) it's completely silent.
After I saved the preset, replaced the Surge instance and loaded it up again Scene B makes sound, but Scene A is silent again.

I've tried bypassing all effects, switching Filter Configuration etc - to no avail.

My patch has deployed a self-destruct.

**Surge Version**

* Version: 1.8.1.9de9336
* Plugin Type:  VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Download this patch: 
[Charging Up.fxp.zip](https://github.com/surge-synthesizer/surge/files/6083468/Charging.Up.fxp.zip)
2. Load it up and play
3. Hear nothing

**Computer Information (please complete the following information):**
 - OS: Manjaro Linux
 - Host: Ardour
 - Version: 6.5

**Comment by unfa** [comment] 2021-03-04 12:07
Ok, now it seems my filters just removed all sound.
I am not sure if anything abnormal isn't going on.

**Comment by baconpaul** [comment] 2021-03-04 12:51
So I don't think surge is misbehaving here; I think you've just set it up so that it doesn't make any sound through the layers of filters and stuff.

It seems (roughly in order) the things which are eating your sound are

1. The wave shaper all the way up as the sin wave shaper - basically turns any inbound signal kinda into noise. If you flip that to off, then
2. The two offset bandpass filters don't seem to let much pass, then
3. The last airwindows capacitor eats a bunch of sound.

so if I load your patch and

1. Turn wave shaper from sine -> off still no sound
2. Turn filter one from BP12 to off -> bit of sound
3. Turn last AW capacitor off -> quite a bit of sound
4. Turn filter two from BP24 to off -> lot of growing sound

So my rough diagnosis here is "you have created enough obstacles in the signal path to let no signal through, and surge is obeying that instruction" :)

The real culprit though is the wave shaper. If I turn off all the fx and filters with the wave shaper on I still get no sound. The sine wave shaper driven that hard is just giving you super high frequency noise. You can see this by going to scene b, turning master volume down, turning pre-filter gain all the way up, turning wave shape all the way up, and picking sine.

Does that help?

**Comment by K0rrid0r** [comment] 2021-03-04 13:06
trying to get the sound back to init sound from the classic osc in this patch led me to find out that a combination of the following things turned to sound completely away.

1. Mixer Gain on max
2. Waveshaper at max
3. Scene Volume very low

and a number of other things

**Comment by mkruselj** [comment] 2021-03-04 13:22
That's probably because of some sort of overflow after waveshaper did its thing (stuff probably went hard to DC only).

**Comment by baconpaul** [comment] 2021-03-04 13:38
the problem definitely originates with driving sine that hard, which generates somewhere between DC +1 and DC -1 and random noise at basically infinite frequency. I think start by not doing that.

**Comment by mkruselj** [comment] 2021-03-04 13:53
"Apply the doctor joke" 🙂 

Well, not a bug, so closing the issue!

**Closed by mkruselj** 2021-03-04 13:53 UTC
