### ISSUE TITLE
Square LFO spikes in vector rendered waveform

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1438] opened 2019-12-20 06:34 UTC
![image](https://user-images.githubusercontent.com/2393720/71235005-23bdd300-22fb-11ea-8d43-9a358b34b4fb.png)

Maybe valid for #1390?

**Comment by baconpaul** [comment] 2020-01-16 01:29
Ha it's not an LFO spike; it's the axis tick marks. Licecap doesn't work on catalina for me right now but trust me. I will lighten that tick color and close this issue.

**Comment by baconpaul** [comment] 2020-01-16 01:37
Nope. On windows it actually shows that spike. woof.

**Comment by VincyZed** [comment] 2020-01-16 02:01
Confirmed. Just got 1.6.3 running and it's still present!

**Comment by VincyZed** [comment] 2020-01-16 02:07
Turns out this has been introduced all the way back in 1.6.2, which is when the LFO display has been vectorialized!

**Comment by baconpaul** [comment] 2020-01-16 02:28
OK!
Well let me try and reproduce it.

**Comment by sense-amr** [comment] 2020-01-21 05:38
yeh i dont see this at all .. on my Square wave.. 
![squarefine_11012020](https://user-images.githubusercontent.com/1504019/72778205-55181e80-3c6c-11ea-8b4f-3236c9e660ba.png)

i built this on 11th of Jan 2020

**Comment by VincyZed** [comment] 2020-01-21 05:52
Are you on Windows?

**Comment by sense-amr** [comment] 2020-01-21 06:10
yes windows 10 .. 
launched surge inside bitwig .. 3.1.2

**Comment by esaruoho** [comment] 2020-01-21 06:49
> Ha it's not an LFO spike; it's the axis tick marks. Licecap doesn't work on catalina for me right now but trust me. I will lighten that tick color and close this issue.

Protip: get newest licecap and dont forget to type .gif by hand at the end of the filename when setting gif recording filename.

**Comment by baconpaul** [comment] 2020-01-21 13:51
@sense-amr that looks like the bitmap display not the vector one. Are you on a recent version of surge? Also sometimes with slower renders it falls back to bitmap.

**Comment by sense-amr** [comment] 2020-01-21 13:54
@baconpaul this build i did .. was just from the update of the repo in visual studio .. i was quite surprised it actually worked too :) .. but yeh i dont see any of those same anomolies on my end.. maybe my build is old? .. i didnt do git submodule update --init --recursive .. but it still built sucessfully anyway .. would i need to update it ? ..

**Comment by baconpaul** [comment] 2020-01-21 13:59
Look in "Menu / UI Options" - Do you see a choice like "use vector LFO display"? If so click that. If not then you aren't fully up to date yeah

**Comment by sense-amr** [comment] 2020-01-21 14:03
ahh hmm i dont see that in the menu .. but ive been out of the loop for a while now :) ..

**Comment by baconpaul** [comment] 2020-01-21 14:08
Yeah so you need to update your source! Or just grab the nightly.

**Comment by sense-amr** [comment] 2020-01-21 14:09
im updating now :)

hmm
error: Server does not allow request for unadvertised object 10287bc37bbb34324b8097369e2ec4eb73a51d65
Fetched in submodule path 'vst3sdk', but it did not contain 10287bc37bbb34324b8097369e2ec4eb73a51d65. Direct fetching of that commit failed.

**Comment by sense-amr** [comment] 2020-01-21 14:14
hmm ill just grab the latest master i guess 
is there anything i need to know about building it now?

**Comment by baconpaul** [comment] 2020-01-21 14:18
Building is all the same
yeah just grab master from refresh your fork and it is all the same.

**Comment by sense-amr** [comment] 2020-01-21 14:32
ok . sorry about all that.. now i have the latest build .. oh and yes i see this very strange anomoly .. on the square LFO .. using bitmap LFO display 
![LFOsq_BitmapUI](https://user-images.githubusercontent.com/1504019/72813160-02178900-3cb7-11ea-9da7-e190b971382c.jpg)

**Comment by baconpaul** [comment] 2020-01-21 14:35
Yeah ok so it is real for sure. I need to get a windows environment running again to figure it out since Mac doesn’t do it.

**Comment by sense-amr** [comment] 2020-01-21 14:39
i noticed it goes away if magnitude is under 10%

**Comment by baconpaul** [comment] 2020-01-21 14:41
Yeah I bet it is just some dumb rounding thing when I make the waveform by pulling the lfo that is compiled dependent or some such. The hardest part of fixing is going to be setting up windows! But I have to do that anyway so

**Comment by baconpaul** [comment] 2020-01-21 14:42
Oh curious if you put a long attack on do the spikes pop above the envelope during the attack phase?

**Comment by sense-amr** [comment] 2020-01-21 14:45
![sqLFO10_1](https://user-images.githubusercontent.com/1504019/72814175-b8c83900-3cb8-11ea-9789-9373db7200e5.jpg)
this is 10.1% and magically it appears.. 

lets try with attack

**Comment by sense-amr** [comment] 2020-01-21 14:47
![sqLFO_withatt](https://user-images.githubusercontent.com/1504019/72814401-1bb9d000-3cb9-11ea-8cd4-406a303b7031.jpg)

**Comment by sense-amr** [comment] 2020-01-21 15:01
hmm its appearing everywhere, as a general out of graphical boundary error.. 
![S HtooLFO](https://user-images.githubusercontent.com/1504019/72815652-12c9fe00-3cbb-11ea-9954-fd1e04cc241e.jpg)

**Comment by sense-amr** [comment] 2020-01-21 15:17
![RampFairlynormalLOrateLFO](https://user-images.githubusercontent.com/1504019/72817038-3a21ca80-3cbd-11ea-92ca-5596e0d60d8f.jpg)
Fairly Normal Low Rate.. Not outside of bounds.. 
![hairmonsterLFO_highRate](https://user-images.githubusercontent.com/1504019/72817069-49087d00-3cbd-11ea-96cc-36f5b6aedee3.jpg)
Scary Hairy Monster High Rate LFO

**Comment by sense-amr** [comment] 2020-01-21 15:25
so i can confirm its NOT just square..

**Comment by VincyZed** [comment] 2020-01-21 16:10
If you take the square wave (or the other ones that do this), and change the frequency precisely ever so slowly using shift, they will actually pop in and out.

**Comment by baconpaul** [comment] 2020-01-21 16:10
Very very useful thank you

**Comment by baconpaul** [comment] 2020-01-21 16:10
I wonder when I find it what silly mistake it will be! Exciting!

**Comment by baconpaul** [comment] 2020-01-21 16:11
Oh and welcome back @sense-amr - hope all is well!!

**Comment by sense-amr** [comment] 2020-01-21 16:17
Thanks @baconpaul good to see you and happy to be able to give some more time to surge ! ..great to see its still growing.. if i remember we ALWAYS had funny things with the LFO gui..

**Comment by baconpaul** [comment] 2020-01-21 16:18
Yeah but then I rewrote it and I thought fixed all of them. But apparently fixed almost all of them.

For fun temposync the rate and you can see musical time axis too!

**Comment by sense-amr** [comment] 2020-01-21 16:21
yeh i noticed that and the (T|S)  on the slider.. :) .. interesting .. with the tempo sync now displayed in time.. over the waveform.

im wondering .. if this is just graphical .. or if the way it looks in the lfo with the spikes etc.. .. corresponds to the actual used shape of the lfo when routed to a parameter..

**Comment by baconpaul** [comment] 2020-01-21 16:34
That was first thing I checked but you can pull it up in rack and the lfo has no spike. It’s just something in my path creation code with downsamoling for graphics

**Comment by baconpaul** [comment] 2020-01-21 16:39
My bet is I screwed up something here https://github.com/surge-synthesizer/surge/blob/b6134fa4ce2c74958714b368612a6cc8171b5dda/src/common/gui/CLFOGui.cpp#L212 since this branch only kicks in when there’s a big change

**Comment by baconpaul** [comment] 2020-01-22 16:02
Found it! Fix incoming.

**Closed** 2020-01-22 16:07 UTC
Labels: ui change

**Comment by sense-amr** [comment] 2020-01-23 02:25
awesome @baconpaul .. great work as always .. im gonna build the new one right now.. and test..

**Comment by baconpaul** [comment] 2020-01-23 02:26
Yeah this fix is so 10 hours ago - wait until you see the other goodies in the new build! Try modulating some stuff and say “ooh” “ahh”. Chuckle.
