### ISSUE TITLE
A4 remapping fails on a specific Hz value

### ISSUE THREAD

**Issue by kheptagon** [surge-synthesizer/surge#4332] opened 2021-04-20 16:41 UTC
**Bug Description:**
When retuning using an scl file, the default reference pitch is C4 (midi pitch 60) = 261.626 Hz. There is an option to remap A4 (midi pitch 69) to a Hz value of the user's choosing. This works for most Hz values, but if the user inputs A4 = 440 Hz, surge doesn't register the input, usually defaulting to C4 = 261.626 Hz. This C4 reference pitch tunes A4 to 440 Hz only in the default 12edo tuning.

**Surge Version**
1.6.6

* Version:
VSTi/AU
64-bit

**Reproduction Steps:**
1. Click on "Apply scl file tuning" and input an scl that is not 12edo
2. Click on "Remap A4 (MIDI note 69) frequency directly to..." and enter 440 Hz
3. A4 will not be mapped to 440 Hz.

**Expected Behavior:**
I expected A4 to be mapped to 440 Hz, as the menu suggests.

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - Windows
 - Reaper version 6.27

**Comment by baconpaul** [comment] 2021-04-20 16:44
Are you really running surge 1.6.6?

**Comment by Jacky-Ligon** [comment] 2021-04-20 16:47
1.6.6 Didn't have SCL-KBM microtuning features right?

**Comment by baconpaul** [comment] 2021-04-20 16:47
Anyway with the nightly (which will be 1.9) tomorrow I just tried this

1. Load ED2-08.scl from the tuning library
2. Play Note 60 (C4) and get C4; Play note 69 and in a tuner see a 50c flat D5
3. Choose the menu A4 -> 440
4. Play note 60 (C4) and get a 50c flat G3; Play note 60 and get 440
5. Choose the menu A4 -> 261
6. Play note 69 and get C4 (4cents off since I typed 261 not 261.5blah); play Note 60 and get 100c sharp A#2

So really seems like it is all working in the latest version

**Comment by Jacky-Ligon** [comment] 2021-04-20 16:48
@kheptagon 

I'd suggest installing Surge 1.9 beta from here:

https://surge-synthesizer.github.io/nightly

This is very likely going to be the release version getting published tomorrow 4/21/2021.

**Comment by baconpaul** [comment] 2021-04-20 16:49
@Jacky-Ligon yeah the first SCL implementation was in 1.6.2 but it didn't have as robust a one as we do now. 

If @kheptagon is using 1.6.6 the solution is "upgrade" I think. Feature seems to work fine in 1.8.1 and in the nightly.

**Comment by Jacky-Ligon** [comment] 2021-04-20 16:49
Here's the original thread from XA:

Jacky L.
 — 
Today at 11:40 AM
RMB on the Tune button, and select, Factory Tuning Library/KBM. Drag-and-Drop: 69-440-69 Concert A.kbm, onto the Tune button, and this will change the mapping where the 1/1 is on A.69 at 440 Hz.
...

It's helpful in working with Surge and its SCL-KBM implementation - analogous to the way Pianoteq works as well - to always load SCL and KBM pairs, which effectively works in the manner of locking the tuning in other VIs, where the loaded SCL-KBM pair will stay fixed as one explores the patch-bank or works with sound-design...

It's also best-practices to save such configurations as track or project templates (Reaper-speak), where they can be recalled without having to recreate the wheel each time...

In Ableton Live though, it's saving such configurations in the User Library, and loading them from there, where one wants the mapping on A.69 at 440 Hz.
HEHEHE I AM A SUPAHSTAR SAGA
 — 
Today at 11:48 AM
Thanks for your help!
It would be nicer to have the issue fixed, but this is a good workaround
Jacky L.
 — 
Today at 11:48 AM
My pleasure.
The mapping has to default to something when no KBM are loaded, and we went with C.60 at 261.626 Hz as that default, since it's fairly common in other software...

It's not a bug though.
HEHEHE I AM A SUPAHSTAR SAGA
 — 
Today at 11:50 AM
The bug is that the in-software A tuning option doesn't work at A440
even though it works for other values
Jacky L.
 — 
Today at 11:52 AM
If you have a GitHub account setup, make an issue about it, so we can get it in the tracking system for a fix in the next version.
HEHEHE I AM A SUPAHSTAR SAGA
 — 
Today at 11:52 AM
I'll do that if I get the time
it's not such a big issue
Jacky L.
 — 
Today at 12:07 PM
So, just for clarity, your expectation is that after you load a SCL of whatever size, you want to be able to RMB/Tune Button/"Remap A.4 (MIDI Note 69) Directly To..."

440 Hz?

If so, yes, use KBM to change the mapping as above. 

When you can make a GitHub issue about your findings and requirements, it could be that Surge can be evolved to allow user configurable default diapason mappings, but the way it works currently is based on the Scala SCL-KBM standard, so it'll require changing the mapping with KBM files...

I'd strongly encourage making an issue though, since it'd be good to discuss this even now in that context.

Again, not a bug.

@baconpaul FYI: See a couple of the preceding messages.
HEHEHE I AM A SUPAHSTAR SAGA
 — 
Today at 12:19 PM
If a user clicks "Remap A.4 (MIDI Note 69) Directly To...", types in 440 Hz, and presses enter, A4 will not be mapped to 440 Hz. If that's intentional design, it's very unintuitive.
Jacky L.
 — 
Today at 12:24 PM
The way it should probably work, is if an SCL is loaded, that option is grayed out, or hidden entirely.

I agree that it's a source of confusion. 

Please take a moment to make a GitHub issue, and then we'll have it in the queue; hard to manage development in other forum venues, as I'm sure you can empathize with. Here's the optimal place for this discussion:

**Comment by Jacky-Ligon** [comment] 2021-04-20 16:51
@baconpaul 

IMHO: "Remap A.4 (MIDI Note 69) Directly To...", should be grayed out, or hidden altogether, when a SCL is loaded, so as to avoid confusion, and enable users to change the mapping using KBM.

**Comment by baconpaul** [comment] 2021-04-20 16:55
@Jacky-Ligon that function just creates a KBM file and applies it as if you loaded one!  And it works too when I just tested it.

Basically set A4 to just calls `auto kb = Tunings::tuneA69To(freq);` which generates a KBM which is basically 'root-at-60 / tuning-center-at-69 / freq'

**Comment by Jacky-Ligon** [comment] 2021-04-20 16:56
That's interesting then...

What @kheptagon it indicating, is that when they load an SCL, and set that to 440 Hz, it is not tuning A.69 correctly to 440 Hz.

**Comment by baconpaul** [comment] 2021-04-20 16:57
right
but they are using a version of surge that is 18 months old
if they try a new version it works fine!

**Comment by baconpaul** [comment] 2021-04-20 16:58
or at least it does for me!

**Comment by Jacky-Ligon** [comment] 2021-04-20 17:00
Yes, @kheptagon , please upgrade your Surge to the above mentioned version, then check the behavior again, and if it's not fixed in the current 1.9 version, drop your SCL files here, so we can test them...

But in agreement with @baconpaul, this sounds like the behavior of an older version of Surge, and not the one we are going to release tomorrow with many microtuning enhancements.

I regret not thinking to ask you what version you were using, but this is why it's best to have these discussions on our SST Discord.

**Comment by baconpaul** [comment] 2021-04-20 17:02
Can you confirm it works for you Jacky? That would help also!

**Comment by Jacky-Ligon** [comment] 2021-04-20 17:02
Yes, give me a moment...

**Comment by Jacky-Ligon** [comment] 2021-04-20 17:06
Yes, @baconpaul and @kheptagon ...

I just dropped a 31 equal SCL onto Surge, then manually changed A.69 to 440 Hz, and as Paul has stated, I can also confirm it's working here in :

Surge Synthesizer
Plugin Host:	REAPER
System:	Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Build Info:	Built on 2021-04-18 at 12:42:17, using pipeline host 'WIN-RNTNKFRMDNI' with 'MSVC-19.16.27045.0'
Version:	**1.9.nightly.3aa9986**

So, it's clear that updating to the current version will fix the issue.

**Comment by baconpaul** [comment] 2021-04-20 17:56
OK wonderful, so let me close this then. @kheptagon if you find otherwise at latest rev, please do reopen!

**Closed by baconpaul** 2021-04-20 17:56 UTC
Labels: Bug Report
