### ISSUE TITLE
kernelbase crash in cakewalk

### ISSUE THREAD

**Issue by HangulAndComputer** [surge-synthesizer/surge#4838] opened 2021-08-13 05:08 UTC
**Bug Description:**
when i open surge in cakewalk, cakewalk crash.

**Surge Version**

* Version:1.9.0
* Plugin Type: vst3
* Bitness: 64

**Reproduction Steps:**
1. install surge
2. open cakewalk
3. scan vst
4. wow cakewalk found surge
5. add new instrument(click +)
6. select surge
7. click small sqare piano button in surge track(open surge)
8. see error

**Expected Behavior:**
surge open and i can make sounds and see what are in surge

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.
<img width="422" alt="케이크웤" src="https://user-images.githubusercontent.com/88872285/129307294-1899db49-ca95-4813-be35-44f5905d587d.PNG">
this is error screen.
**Computer Information (please complete the following information):**
 - OS: [e.g. Windows 10] yes
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper] cakewalk (by bandlab? sonar?)
 - Version: [e.g. 2.4] i couldnt find but it was up to date.

**Additional Information:**

**Comment by mvf** [comment] 2021-08-13 16:22
Thanks for reporting this. Unfortunately I can't seem to reproduce it. I also tried starting Cakewalk with Korean code page, but couldn't get it to crash for me.

Is there a chance you could share the `.dmp` file mentioned in the error message?

**Comment by HangulAndComputer** [comment] 2021-08-13 23:27
[Untitled_08142021_081853.zip](https://github.com/surge-synthesizer/surge/files/6985562/Untitled_08142021_081853.zip)
here is the dmp file.

**Comment by mvf** [comment] 2021-08-24 19:44
Thank you for the minidump, finally had some time to look into this. As suspected, it's a Unicode issue. Uncaught `std::system_error` with message _"No mapping for the Unicode character exists in the target multi-byte code page."_ As mentioned, setting the system code page to 949 doesn't repro it for me, so maybe this really does take a Korean Windows.

Unfortunately, Surge releases are built without symbols, so the call stack is not immediately helpful:

```
KERNELBASE!RaiseException+0x69
Surge!ExitDll+0x275ef5
Surge+0x2ae7a
Surge+0x83cd0
Surge+0x89964
Surge+0x875be
Surge+0x82632
Surge+0xef7aa
Surge+0x10068e
Surge+0xfdcd2
Surge!GetPluginFactory+0x4ee4
Cakewalk!m7_ippsLn_32f_A21+0x3d39bc
```

Things to try next:

- Fix `RelWithDebInfo` builds. Currently these are not fully optimized due to a combination of MSVC's weird parameter semantics and CMake defaults. With a proper `RelWithDebInfo` build, it should be possible to manually reconstruct line info for the call stack above. It would also be great to build future final releases as `RelWithDebInfo` and keep the PDBs for cases like this.
- Failing that, we could try to produce another minidump on OP's machine using a build with symbols.

**Comment by baconpaul** [comment] 2021-08-24 19:46
Wonder if xt nightly works in this environment. That may be another quick thing to check

**Comment by mkruselj** [comment] 2021-12-29 19:10
@HangulAndComputer @kujira70 Can you please test if Surge XT works for you perhaps? Thank you!

https://surge-synthesizer.github.io/nightly_XT

**Comment by baconpaul** [comment] 2022-01-05 00:08
Over in 5724 we have confirmation that Japanese charset xt cakewalk works and 19 fails so I’m going to close this

**Closed by baconpaul** 2022-01-05 00:08 UTC
Labels: Host Specific, Windows, Bug Report

**Comment by Quickle007** [comment] 2025-01-02 15:52
I'm facing to same issue on my Cakewalk.
Same Crash code : e06d7363
Surge XT version: 1.3.4.f7b97c6
PC: Windows 11 Home (24H2), Core i7-10750H, 16GB

I found, it crashes on the project which uses several instances of Surge XT. With single instance of this plugin, Cakewalk opens normally.

Here is my dump file. Thanks!
[_01032025_003922.zip](https://github.com/user-attachments/files/18292194/_01032025_003922.zip)

**Comment by Quickle007** [comment] 2025-01-05 02:06
My PC crashed, so I can't reproduce this problem any more.
This problem could be specific for my PC.
So, I'd like to make this report closed.
Thanks.
