### ISSUE TITLE
Scene copy and paste doesn't always work

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3309] opened 2020-11-30 20:59 UTC
Copying scenes doesn't always work. It sometimes doesn't copy the scene it all, sometimes it copies the wrong scene and sometimes it just works.
Copying scenes also used to sometimes crash Surge, but that was resolved with this commit: https://github.com/surge-synthesizer/surge/commit/c7a597d5e74420d7a5babf019b40ac2b32bf74d2
I don't know if that's related in any way.

1: Load a fresh instance
2: Make some changes to Scene A
3: Try to copy it to scene B

I wish I could give more information, but I can't really figure out when it happens.

Surge Synthesizer
Version: 1.8.nightly.c72f35c
Build Info: Built on 2020-11-30 at 13:58:27, using pipeline host 'WIN-NSSBUUS6UC1'
System: Intel CPU, Windows VST3, 64-bit
Plugin Host: Ableton Live 10.1

**Comment by baconpaul** [comment] 2020-12-01 01:16
So that crash fixes a nasty memory bug in initialized msegs
It is, however,the case that if you ran a patch with that bug and saved it, then copy and paste would use the corrupted msegs.
Is it possible for you to take one of the sessions or patches where things are broken and stream it to an fxp?

Basically copy scene copies all the msegs. Before that patch, the msegs were not initialized. So my theory is: If you have a patch you made before c7a597d it has corrupted msegs (but who cares right since you weren’t in MSEG mode!) but then you copy it and it copies all the msegs including the corrupted ones and blammo.

Of course the fix here is for me to not copy the MSEG state if your LFO isn’t mseg. I will put that into the copy code . https://github.com/surge-synthesizer/surge/blob/809a376ba9a9a4dd54d234d4de7d5195abd0cf7a/src/common/SurgeStorage.cpp#L1046 which I bet will fix your problem, but I bet the commit above means you can’t make the problem from a *new* surge just from a saved older session

**Comment by TheNerdyMusicGuy** [comment] 2020-12-01 02:27
Sadly, that doesn't seem to be the case. Like I described above, this also happens on a completely fresh instance with the init preset that loads by default.

To reproduce (sometimes): Open a fresh instance, move some fader and try to copy the scene to scene B.

**Comment by baconpaul** [comment] 2020-12-01 02:28
Should have read more carefully sorry
Will try and capture it in a unit test then

**Comment by TheNerdyMusicGuy** [comment] 2020-12-01 02:29
No problem!

**Comment by mkruselj** [comment] 2020-12-01 21:07
Confirmed fixed by #3319!

**Closed by mkruselj** 2020-12-01 21:07 UTC
Labels: Bug Report

**Comment by XtremeSounds** [comment] 2021-04-25 11:57
Is it possible to load a scene from a preset and paste it into another instance of surges scene A or B?   In other words can we mix scenes from 2 different presets?

**Comment by baconpaul** [comment] 2021-04-25 12:16
Not right now. I think there’s an issue on this somewhere but not in immediate plans to address
