### ISSUE TITLE
1.7.1 crashes in FL Studio 20, Windows 10

### ISSUE THREAD

**Issue by MaZe6K** [surge-synthesizer/surge#2466] opened 2020-08-10 15:46 UTC
I have two projects in FL Studio, using Surge as the only sound source. One crashes upon loading the project, the other one can still be opened and played, but crashes when I try to open Surge.

Surge 1.7.1, VST3 64 bit
Windows 10, FL Studio 20.7.1

If you want I can send you the project files (.flp's)

**Comment by MaZe6K** [comment] 2020-08-10 15:54
[crashing FL Studio projects using surge.zip](https://github.com/surge-synthesizer/surge/files/5051900/crashing.FL.Studio.projects.using.surge.zip)

**Comment by VincyZed** [comment] 2020-08-10 16:27
I can reproduce on my side.

**Comment by MaZe6K** [comment] 2020-08-11 17:55
Clarification: By "crash" I meant the screen freezes and mouse and keyboard stop working, the audio is still running and if it is running while loading the project it will still play it back.

Additional Info:
It was suspected that my FL Studio template or the airwindows Tape plugin in those two projects might be causing the issue. Also opening end closing plugin instances at first seemed to work better when the "auto select plugin" option in FL was switched off.
But after further tests I have encountered the same problems again with a completely fresh empty project with just a few instances of Surge and no other plugins at all freezing upon loading.

**Comment by MaZe6K** [comment] 2020-08-15 09:53
Update:
I tested further and the error only occurs when I deactivate individual outputs.
If you want to reproduce it on a new project, deactivate the A and B individual outputs, then it will hang when opening.

**Comment by VincyZed** [comment] 2020-08-21 01:02
I have opened an older project which had Surge instances that are dating from 1.6.X. Every single one of them crashes when opening their GUI as well, so I'm unable to change any Surge setting nor plugin wrapper setting, so this is pretty bad..

@MaZe6K This may be related to the wrapper menu (the cog wheel icon in the window bar of the plugin window). It may have been opened on the ones that crash, but it wasn't on the one that didn't..  Maybe, I'm not sure.

**Comment by VincyZed** [comment] 2020-08-21 01:03
I'm going to do more testing, possibly temporarily downgrade to 1.6 if needed to get them to open and see if I can find the problem..

**Comment by VincyZed** [comment] 2020-08-21 01:27
I tried in to downgrade to both 1.7 and 1.6.6, and the same thing still happens. I'm really not sure what's going on at that point..

**Comment by K0rrid0r** [comment] 2020-08-21 01:33
try open it in 32 bit?

**Comment by baconpaul** [comment] 2020-08-21 01:43
Can you attach here a file that I could try and open in my VM? Is there *any* stack trace available?

**Comment by VincyZed** [comment] 2020-08-21 01:58
OK so good news, I found what causes the problem. Here's how to reproduce:

1. Open Surge.
2. Open the VST "Detailed Settings" menu.
![image](https://user-images.githubusercontent.com/50145178/90843138-f5cbdb00-e32e-11ea-9e6c-ca51737d6718.png)

3. Click on either the second or third tab of options.
![image](https://user-images.githubusercontent.com/50145178/90843243-36c3ef80-e32f-11ea-9265-7c022eb98146.png)

4. Close the Detailed Settings by pressing on the cogwheel again.
![image](https://user-images.githubusercontent.com/50145178/90843295-4a6f5600-e32f-11ea-8e29-09bdf376b38e.png)

5. Close the plugin GUI.

6. Re-open the plugin GUI. FL's GUI will freeze completely, the sound engine still works. Only way to kill FL is through task manager, it will not "stop responding".


The way to avoid the issue is to go back to the "Plugin Editor" tab first, AND THEN closing the Detailed Settings with the cogwheel button.
![image](https://user-images.githubusercontent.com/50145178/90843468-b356ce00-e32f-11ea-9695-83216adb8de7.png)

Otherwise, I was able to open the GUIs of the bugged ones by loading the project in 32-bit FL (thank you @K0rrid0r !), which basically bridged all Surge instances. This allowed me to open them up without them freezing, and it went directly to the other 2 tabs I had opened. I just had to go to the plugin editor page before closing the menu, and to do this for all instances of Surge in the project to fix it.

I'm not sure if this is an FL or a Surge problem, but I've tested with other synths and it doesn't seem to affect them.

Hope all of this helps!

**Comment by baconpaul** [comment] 2020-08-21 02:01
Very useful. I will try and repro in my VM. Thank you.

**Comment by baconpaul** [comment] 2020-08-21 02:04
What are those controls supposed to do by the way?

**Comment by VincyZed** [comment] 2020-08-21 02:09
Those contain a bunch of general VST settings for the wrapper. See the [plugin Wrapper page in the FL Manual](https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/plugins/wrapper.htm?utm_source=daw&utm_medium=offline&utm_campaign=flstudio_20).

**Comment by K0rrid0r** [comment] 2020-11-14 03:31
little bit more info on this problem. It only occur in VST3. Cant reproduce this issue in 64 bit FL 20 vst2 64 bit

**Comment by baconpaul** [comment] 2020-11-14 03:57
Thanks

My guess is https://github.com/surge-synthesizer/surge/blob/6957460a891523852d6e38218aa8836d1ab5984e/src/common/gui/SurgeGUIEditor.cpp#L1874 is where we will find the problem

**Comment by K0rrid0r** [comment] 2020-11-14 04:44
i tried commenting it out, didnt solve the issue, but i guess that was not the correct fix anyway.

**Comment by K0rrid0r** [comment] 2020-11-14 04:52
Also getting the 'crash' on FL 20 32 bit VST3 32 bit 

hash 6957460

so def only a vst3 issue

**Comment by K0rrid0r** [comment] 2020-11-14 05:28
some additional info.

playing around with surge and opening and closing those VST setting wrapper tabs does this when i loaded FL into debug mode in VS.

![skinproblem q0](https://user-images.githubusercontent.com/56724286/99140357-91749b00-2641-11eb-81f3-b58f794680e8.gif)

obviously something is going on with 

'FL.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\d3d10warp.dll'
'FL.exe' (Win32): Loaded 'C:\Windows\SysWOW64\d3d10warp.dll'. 


BUT!

if i also open up a second vst3 plugin like stochas vst3 for example we can see that 

'FL.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\d3d10warp.dll'
'FL.exe' (Win32): Loaded 'C:\Windows\SysWOW64\d3d10warp.dll'. 

is not engaged when i open and close the VST setting wrapper tabs in surge.

![skinproblem q0 2](https://user-images.githubusercontent.com/56724286/99140382-da2c5400-2641-11eb-9e31-d7c2f9d20d89.gif)

**Comment by K0rrid0r** [comment] 2020-11-14 07:34
![skinproblem q0 4](https://user-images.githubusercontent.com/56724286/99142309-2ed8ca80-2654-11eb-8713-790460ca1a26.gif)
this was the closest i got with my limited knowledge in this heh!

**Comment by baconpaul** [comment] 2020-11-24 17:55
So I don't know what this is and I am not going to be able to debug it but: It is not the lifecycle stuff

Open and Close and Create and Destroy gets called at the right time. When you re-open after closing in a flipped-from-control-back state the creation and open succeeded, the frame parents, but just we end up stuck on the UI thread in a place the debugger can't find and I can't fix.

So basically: no clue here. There's a workaround but someone with better win debugging skills than me will have to crack this one.

**Comment by baconpaul** [comment] 2020-11-25 15:27
Since I can't solve this one, I'm going to move it out of the 18 pipeline to currently unscheduled.

**Comment by mvf** [comment] 2020-11-26 08:24
Can confirm this is VST3-only. The repro steps (kudos btw!) break something, and then FL and Surge can't agree on a window size anymore. Here's what happens when reopening the plugin window:

1. FL calls `SurgeGUIEditor::checkSizeConstraint` with `newSize->bottom` being the current height of the Surge window
2. Surge accepts the height
3. FL calls `SurgeGUIEditor::checkSizeConstraint` again with the height reduced by a few pixels
4. Surge insists on the initial height
5. `goto` 1

Changing `SurgeGUIEditor::checkSizeConstraint` to leave `newSize->bottom` alone works around the freeze, but of course this unlocks the width/height ratio and everything outside the Surge client area renders black:

![surge](https://user-images.githubusercontent.com/304760/100321840-9e8b7580-2fc3-11eb-9a68-670ed6891249.png)

**Comment by baconpaul** [comment] 2020-11-26 12:44
Oh excellent.

We have if fruity code elsewhere. We could add if in check size constraint also with a link to this issue. Thoughts?

**Comment by Kingston1** [comment] 2020-11-26 13:01
@mvf was the above VST3 issue with all the recent window size changes, or 1.7.1 release code?

**Comment by baconpaul** [comment] 2020-11-26 13:25
Yeah this bug has been there forever @Kingston1

**Comment by baconpaul** [comment] 2020-11-26 13:27
I really think we fix this one with `hostProgram.find( "Fruit" ) != std::string::npos` in the VST3 and then perhaps report it to the FL devs.

**Comment by baconpaul** [comment] 2020-11-26 13:27
(now that @mvf has found the infinite loop of course. Thank you again @mvf!)

**Closed** 2020-11-28 04:35 UTC
Labels: Bug Report, Host Specific

**Comment by faseh329** [comment] 2024-12-10 15:51
Download 🟢Link👉👉[FL Studio 2025 Activated Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment] 2024-12-10 15:51
Download 🟢Link👉👉[FL Studio 2025 Activated](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment] 2024-12-10 15:52
Download 🟢Link👉👉[FL Studio Crack Activated Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment] 2024-12-10 15:52
Download 🟢Link👉👉[FL Studio Key Activated Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment] 2024-12-10 15:52
Download 🟢Link👉👉[FL Studio Reg Key 2025 Activated Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢
