### ISSUE TITLE
Oscillator signalflow POST mixer when Oscillator FM Routing is on.

### ISSUE THREAD

**Issue by CurlyMC** [surge-synthesizer/surge#2884] opened 2020-10-16 17:33 UTC
When Oscillator FM Routing is on, right now it's impossible to adjust the volume amount of individual oscillators, send to other oscillators ( with creates the typical beautifull fm sound ).
The FM Depth slider controls a global volume from ALL oscillators.
The volume sliders on the mixer have no effect on the amount of 'fm volume' send from one to another oscillator.
It would be really nice if the mixer would allow to adjust the volumes of each INDIVIDUAL oscillator ( audio post mixer instead of pre mixer, when Osc FM Routing is not NO FM ).

Quick example :
osc routing 2>1, FM Depth -10dB : moving the osc 2 slider in the mixer has NO effect on the amount of volume send from osc 2 to osc 1.
Especially in 3>2>1 or 2>1<3 oscillator fm routing, controlling signalflow volumes send between oscillators via the mixer would create some extra sonic possibilities.

Don"t know if this is be a bug or a feature request :-)
I would like to wish the Surge Team a happy weekend !  Kind Regards, Luc.

**Comment by baconpaul** [comment] 2020-10-16 18:44
Hi Luc

Thanks for the idea and kind words.

We've thought about this before (and I think we even have some other issues on it). The problem is right now it is basically impossible to add parameters to surge without breaking backwards compatibility. I'm working on fixing that in our upcoming 1.8 release (scheduled for January) and with that release solidified we hope to do a variety of things in 1.9 which add params including: Individual FM depth sliders, and more filter options (so we can do things like a formant filter #1584 or expose more of the OBX-d filter morph options).

So let me tag this 1.9 and FM and stuff and once our 1.8 release is out the door we can take a look in early '21.

**Comment by CurlyMC** [comment] 2020-10-16 19:05
Thanks Paul, although I'm not a programmer of course I understand !
So... just let's skip the 1.8 and direct go to the 1.9 ? :-)
A joke of course, when I see all the 1.80 features and additions, its crazy to see what the Surge Team is creating !!!
Thank you all so much !

**Comment by mkruselj** [comment] 2020-10-16 20:09
The mixer in Surge comes after the FM oscillator routing, it's by design. As Paul mentioned, there's a host of FM related things that we have in the issue tracker (please search the tracker, the thing you are thinking about might have already been suggested, and it helps us not have duplicate issues, thanks!). For example, just see what's under FM Enhancements label:

https://github.com/surge-synthesizer/surge/labels/FM%20Enhancements

**Comment by CurlyMC** [comment] 2020-10-16 20:18
@mkruselj, Since I'm a new github user I didn't do enough research. I'm sorry for that !
You're completely right in the above reply, thanks for FM Enhancements link and your reaction !

**Comment by baconpaul** [comment] 2020-10-16 22:34
@CurlyMC no worries! Always welcome to open an issue just we might close or remap them since we use issues as work list as well as user communication and design documents

**Comment by mkruselj** [comment] 2020-10-24 14:06
So, ultimately this is asking for a FM matrix, which is basically then a duplicate of #1031, so closing this one.

**Closed** 2020-10-24 14:06 UTC
Labels: FM Enhancements, Feature Request
