### ISSUE TITLE
add "-no-pie" to CMAKE_EXE_LINKER_FLAGS for executable Standalone Linux

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#5653] opened 2021-12-19 20:24 UTC
Currently the Standalone for Surge XT and Surge XT FX compile as shared libraries

when adding `-fPIE -no-pie` to `CMAKE_CXX_FLAGS` Surge XT and and Surge XT FX Standalones compile as executable

the advantage of the binary being executable rather than a shared library is that it can be opened by double-clicking or click -> Enter from the GUI or file manager

however, these flags appear to need to be removed from or not added to the cmake.flags for the plugins (VST, VST3, AU and LV2), which should remain shared libraries

**Comment by tank-trax** [comment] 2021-12-19 21:01
this also works.... building `--target surge-staged-assets`

in the files
```
surge-fx_VST3.dir/flags.make
surge-fx_VST3.dir/link.txt

surge-xt_VST3.dir/flags.make
surge-xt_VST3.dir/link.txt
```
replacing **-no-pie** with **-pie**

`CXX_FLAGS = -fPIE -pie`

-no-pie creates executable
-pie creates shared library

**Comment by tank-trax** [comment] 2021-12-20 03:40
this also works and may be a better way to go

`cmake -Bbuild -DCMAKE_CXX_FLAGS="-fPIE -pie"`

then replace **-pie** with **-no-pie** 

in

```
surge-fx_Standalone.dir/flags.make
surge-fx_Standalone.dir/link.txt

surge-fx_Standalone.dir/flags.make
surge-fx_Standalone.dir/link.txt
```

[fpie](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/data-options/fpie.html)
[pie](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/linking-or-linker-options/pie.html#pie)

**Comment by baconpaul** [comment] 2021-12-20 15:07
I think I see the magic to add this to just the standalone in cmake but need Linux which I won’t have for a few days

**Comment by tank-trax** [comment] 2021-12-21 02:03
-fPIE is already there in the Standalone **flags.make** files, without adding `-DCMAKE_CXX_FLAGS="-fPIE -no-pie"`

am testing to see if all it was missing was **-no-pie**

**Comment by tank-trax** [comment] 2021-12-21 03:29
this [thread](https://forum.juce.com/t/code-blocks-and-x-shared-lib-app/24932/9) may be of interest

as well as this [one](https://forum.juce.com/t/cmake-executable-build-shows-up-as-shared-library-on-linux-mint/45503/3)

**Comment by tank-trax** [comment] 2021-12-21 03:42
it's the gcc compiler, it has **--enable-default-pie** configured 
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
```

**Comment by tank-trax** [comment] 2021-12-23 04:15
one or all of the following...

```
-DCMAKE_BUILD_TYPE=Release 
-DCMAKE_SHARED_LINKER_FLAGS="-no-pie" 
-DCMAKE_SHARED_LINKER_FLAGS_RELEASE="-no-pie" 
-DCMAKE_EXE_LINKER_FLAGS="-no-pie"
```
after trying only

`cmake -Bbuild -DCMAKE_EXE_LINKER_FLAGS="-no-pie"` 

looks to be enough

**Comment by baconpaul** [comment] 2021-12-29 01:19
So to be clear: if you use `CMAKE_EXE_LINKER_FLAGS="-no-pie"` on linux, the problem is solved?

Does this just get solved with editing the README and the azure pipelines script then?

**Comment by baconpaul** [comment] 2021-12-29 01:23
I think the fix might be, in `./CMakeLists.txt' to add 

```
if(UNIX AND NOT APPLE)
   set(CMAKE_EXE_LINKER_FLAGS "-no-pie")
endif()
```

around line 38 (after the version 17 flag) but I'm really not sure what this will do to every distro out there and all their various configurations and don't know how to test it in all those build envs, which is why I am more leaning towards "README and Azure" btw

**Comment by tank-trax** [comment] 2021-12-29 03:09
> So to be clear: if you use CMAKE_EXE_LINKER_FLAGS="-no-pie" on linux, the problem is solved?

it appears to be, I think it is something that behaves similarly across all Linux distros, if I am reading things correctly it is a GCC issue (-pie is default) as Clang builds the executable without the switch, but I could be wrong about that

the files

**surge/build/src/surge-xt/CMakeFiles/surge-xt_Standalone.dir/flags.make**
**surge/build/src/surge-xt/CMakeFiles/surge-fxt_Standalone.dir/flags.make**

for the Standalone have -fPIE rather than -fPIC

`CXX_FLAGS = -O3 -DNDEBUG -fPIE... `

for the Standalones to be an executable rather than a shared library, it requires -no-pie, so 

`cmake -Bbuild -DCMAKE_EXE_LINKER_FLAGS="-no-pie"`

or
```
if(UNIX AND NOT APPLE)
   set(CMAKE_EXE_LINKER_FLAGS "-no-pie")
endif()
```

will add -no-pie into the links.txt file that is in the same folder as the Standalones as follows:

`/usr/bin/c++  -O3 -DNDEBUG  -no-pie -Wl,--no-undefined...`

this builds both XT and FX Standalones as an executable and the VST3's as shared libraries

**Comment by baconpaul** [comment] 2021-12-29 03:23
right OK so then the test is unix and not apple and gcc and not some-get-out-of-jail-ree-cmake-option set it 

OK lemme fire up linux and see if i can close this.

**Comment by baconpaul** [comment] 2021-12-29 03:38
```
paul@paul-linux:~/dev/surge$ file ignore/nopie/surge_xt_products/Surge\ XT
ignore/nopie/surge_xt_products/Surge XT: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=dd10a3f7e95ded839bb10e36671a58fc8439f63f, for GNU/Linux 3.2.0, with debug_info, not stripped
paul@paul-linux:~/dev/surge$ file ignore/nopie/surge_xt_products/Surge\ XT.vst3/Contents/x86_64-linux/Surge\ XT.so 
ignore/nopie/surge_xt_products/Surge XT.vst3/Contents/x86_64-linux/Surge XT.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=dcbe8e111d766ce0f25617dfa48b7cb6325de601, with debug_info, not stripped
```

great so if CI works on 5678 we shoud be good

i added a get-out-of-jail-free override option as well in case it blows up some distro after the 1.0 release.

**Closed** 2021-12-29 04:13 UTC
Labels: Feature Request, Linux, Infrastructure
