### ISSUE TITLE
GUI Blurry when mixing Retina and Non-Retina displays on MacOS on Launch

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#952] opened 2019-07-11 16:52 UTC
What I saw:
Build and validate AU
Launch Logic and bring up Surge GUI
At initial zoom (whatever I have set as default) % some of the text in the GUI that has been converted to outlines still looks uggo.
Zoom up to 125% text look nice and crisp
Zoom back to 100% now text look nice and crisp there as well.

Its almost like at the initial load of GUI its falling back to bitmaps then on scale switching over to the .svg assets. Would that even be possible?

Regardless, once Im down on the machine I was seeing this on Ill open an issue with screenshots.

baconpaul [8:09 AM]
Oh ha I bet I ignore the pixel density on the initial zoom

That would explain what you see at least

Or more accurately set it before I have a window so I get back a “1”

So it’s using svg but not retina in initial state - probably more fallout from the initial zoom dance fix

If you can reproduce please just add that comment to the issue and I’ll look when I’m back!

Oh nope I anticipated that! 

https://github.com/surge-synthesizer/surge/blob/d6de8aed3e47a01da676059c69f06beb24b0272e/src/mac/DisplayInfoMac.mm#L32
src/mac/DisplayInfoMac.mm:32

    ```float defaultBackingScale = 2.0;``` 
surge-synthesizer/surge | Added by GitHub

Well vacay is good enough that my in my head debugging is now rusty :)

**Comment by itsmedavep** [comment] 2019-07-11 16:54
<img width="1133" alt="Screen Shot 2019-07-11 at 11 47 26 AM" src="https://user-images.githubusercontent.com/11078351/61069669-6ab1af00-a3d2-11e9-94bd-802c947987f8.png">

Compare the patch "Category" text to the OSC labels. In that screen I have set 125% zoom as my default BUT this also happens if at 100%.

**Comment by baconpaul** [comment] 2019-07-11 17:10
Thanks. Super clear.

**Comment by baconpaul** [comment] 2019-07-11 17:46
So I can't reliably reproduce this but in debugging I did find a bit of uninitialized memory in the cache handler for the offscreen draws which I think may be the problem. Should have a new nightly soon with the memory fix in place. If that works for you we can close this. If not I'll make a branch for you with some debug prints.

**Comment by baconpaul** [comment] 2019-07-11 17:52
OK @itsmedavep can you try this with latest master at your convenience?

**Comment by itsmedavep** [comment] 2019-07-13 14:07
I was able to try this out. Im still seeing the issue.

<img width="700" alt="Screen Shot 2019-07-13 at 9 05 41 AM" src="https://user-images.githubusercontent.com/11078351/61172688-986f3300-a54d-11e9-8529-7cfca67684c7.png">
<img width="1132" alt="Screen Shot 2019-07-13 at 9 05 54 AM" src="https://user-images.githubusercontent.com/11078351/61172692-9c9b5080-a54d-11e9-8e77-95052259d4be.png">

**Comment by baconpaul** [comment] 2019-07-13 15:15
Ok then! So let me make you a branch with some debug prints in it and we can see what they say.

**Comment by baconpaul** [comment] 2019-07-14 16:54
Ok @itsmedavep I pushed a version with debugging information for you. It's on baconpaul branch `blur-for-dave-952`

As a reminder here's how you check it out

```
git remote add baconpaul https://github.com/baconpaul/surge
git fetch baconpaul
git checkout baconpaul/blur-for-dave-952
```

then do a clean build and build. If you build successfully you should see a chunk of the UI go pink. Cool. Screenshot below.

Now you need to run a host with the terminal output captured. Easiest way to do this is just run logic from the terminal then add a surge.

```
/Applications/Logic\ Pro\ X.app/Contents/MacOS/Logic\ Pro\ X 
```

from the terminal will start logic with logic attached. You will then see output when you open surge that looks like the [DBG] messages in the screenshot below. (That was run in Hosting AU but it works in Logic too; I just checked).

Do your various resizes and copy and paste the DBG statements over to me? In Hosting AU just now I saw this:

```
[DBG] SurgeGUIEditor::setZoomFactor(190)
[DBG] SurgeGUIEditor::setZoomFactor post fun sets zoomFactor=190
[DBG] SurgeGUIEditor::setZoomFactor(190)
[DBG] SurgeGUIEditor::setZoomFactor post fun sets zoomFactor=190
[DBG] HI DAVE. These are the debug messages
[DBG} Tried to parse from '/Users/paul/Library/Audio/Plug-Ins/Components/Surge.component/Contents/Resources/svg/bmp00102.svg'
[DBG] Got a valid SVG
[DBG] SurgeGUIEditor::setZoomFactor(190)
[DBG] SurgeGUIEditor::setZoomFactor post fun sets zoomFactor=190
[DBG] CScalableBitmap::draw for bg (x=0,y=0)+(w=1717,h=1029) 140411688635680
[DBG] LASTSEEN blowing us out lsz=-1  cpz=380
[DBG] Redrawing exs=190 lsz=380 rect=(x=0,y=0)+(w=1717,h=1029)
[DBG] Offscreen is 3434x2058
[DBG] SurgeGUIEditor::setZoomFactor(190)
[DBG] SurgeGUIEditor::setZoomFactor post fun sets zoomFactor=190
[DBG] CScalableBitmap::draw for bg (x=0,y=0)+(w=1717,h=1029) 140411688635680
[DBG] CScalableBitmap::draw for bg (x=129,y=131)+(w=143,h=25) 140411688635680
[DBG] SurgeGUIEditor::setZoomFactor(180)
[DBG] SurgeGUIEditor::setZoomFactor post fun sets zoomFactor=180
[DBG] CScalableBitmap::draw for bg (x=0,y=0)+(w=1627,h=975) 140411688635680
[DBG] LASTSEEN blowing us out lsz=380  cpz=360
[DBG] Redrawing exs=180 lsz=360 rect=(x=0,y=0)+(w=1627,h=975)
[DBG] Offscreen is 3254x1950
[DBG] CScalableBitmap::draw for bg (x=122,y=124)+(w=135,h=24) 140411688635680
[DBG] CScalableBitmap::draw for bg (x=122,y=124)+(w=135,h=24) 140411688635680
```


<img width="753" alt="Screen Shot 2019-07-14 at 12 45 43 PM" src="https://user-images.githubusercontent.com/13387561/61186641-b6b05e00-a635-11e9-8b5a-854ebbd076d9.png">

**Comment by itsmedavep** [comment] 2019-07-14 16:58
TY! Ill get some time to try this out today (in a couple hours). Ill report back later.

**Comment by baconpaul** [comment] 2019-07-15 01:10
Dave and I have figured out that this happens when you have a mac with one retina and one non-retina display. Clearly somewhere in the startup path we choose the wrong screen so use the 1x rather than 2x resolution.

**Comment by baconpaul** [comment] 2019-08-20 14:09
@itsmedavep this one is a bit tricky to fix (need to re-scan backing store at one point). Mind if I bump it to 1.6.3? Let me know if that's a problem.

**Comment by itsmedavep** [comment] 2019-08-20 16:14
I'll survive!

**Comment by mkruselj** [comment] 2021-03-18 13:08
@baconpaul Wonder if JUCE is already doing the right thing in this situation here? So maybe this one is already self-fixed in XT?

**Comment by baconpaul** [comment] 2021-03-18 14:16
I have a non-retina display at another spot I can use and test yeah. Lets tag it into XT to close-as-fixed-or-figure-out.

**Comment by mkruselj** [comment] 2021-04-27 07:53
@baconpaul Are you able to test this one so that we can (probably) close it? 😀

**Comment by baconpaul** [comment] 2021-04-27 13:58
yeah i can test later today. i have a non-retina monitor at one of my locations.

**Comment by baconpaul** [comment] 2021-04-28 02:02
Confirmed all ok

**Closed by baconpaul** 2021-04-28 02:02 UTC
Labels: Bug Report, JUCE ex machina, UI
