### ISSUE TITLE
Distortion DC blowup when toggling on/off

### ISSUE THREAD

**Issue by KosmiKFead** [surge-synthesizer/surge#4565] opened 2021-05-19 13:32 UTC
[PRESETS.zip](https://github.com/surge-synthesizer/surge/files/6509068/PRESETS.zip)

Distortion FX blows up (extreme DC offset) when switching it on

**Surge Version**
1.9.0
vst3
64bit

1. Open "Neuro Grease" Preset
2. Turn dist FX on
3. Blow Up!

To recover switch off the dist FX and also the send FX freq Shifter

Expected Distortion to switch on and distort the audio. After distortion failed i expected audio to pop back on when it is again switched off.

**Computer Information (please complete the following information):**
 - Win7 64bit
 - FL Studio 20.8.3

**Comment by baconpaul** [comment] 2021-07-15 00:34
This was a remarkably useful bug report, thank you. Sorry it took us a couple of months to get to it

I've merged a fix which will be in our next release. The problem is with the two SSE-based wave shapers (Sine and Digi) in distortion. If you take your patch with 1.9 and change the wave shaper to hard or soft instead then you should avoid the blowup in the 1.9 vintage.

**Closed** 2021-07-15 00:56 UTC
Labels: Bug Report, Effects
